//! `susie` — a pure-Rust port of the **algorithm API** of the R package
//! [`susieR`](https://github.com/stephenslab/susieR) (Wang et al., *JRSSB* 2020),
//! focused exclusively on **GWAS summary-statistics fine-mapping** via
//! [`susie_rss`](crate::susie_rss).
//!
//! ## Scope
//!
//! This crate ports the **standard RSS likelihood** path (`susie_rss` with
//! `lambda = 0`): the Sum of Single Effects (SuSiE) variational model fit via
//! Iterative Bayesian Stepwise Selection (IBSS), using z-scores + an LD
//! correlation matrix R.
//!
//! **In scope:**
//! - `optim`, `EM`, `simple` prior-variance estimation methods
//! - z-score, bhat/shat, and bhat/shat/var_y input paths
//! - PVE adjustment (Wald vs score z-method)
//! - Fixed / estimated residual variance
//! - Prior weights, null weight, non-uniform scaled prior variance
//! - Credible sets with purity filtering (min_abs_corr / median_abs_corr)
//! - PIP computation with prior_tol trimming
//!
//! **Out of scope** (not ported): `susie_rss_lambda`, infinitesimal/ash
//! unmappable effects, NIG residual prior, R-mismatch / finite-reference
//! correction, multi-panel mixture, slot priors, refinement, trend filtering,
//! `mr.ash`, individual-level `susie()`/`susie_ss()`.
//!
//! ## Faithfulness
//!
//! - Linear algebra runs on [`faer`].
//! - `NA` is `f64::NAN`.
//! - The scalar prior-variance optimizer reproduces R `optim(method="Brent")`
//!   via a faithful Brent golden-section + successive-parabolic port.
//! - Cross-validated against 40 golden scenarios generated by `susieR` 0.16.6
//!   on the exact simulation seeds used by susieR's own reference tests.

pub mod brent;
pub mod cs;
pub mod data;
pub mod model;
pub mod ser;

pub use cs::{CredibleSet, CredibleSets};
pub use data::{PriorMethod, RssInput, ZMethod};
pub use model::{SusieFit, SusieParams};

use thiserror::Error;

/// Errors produced by the SuSiE-RSS fitting procedure.
#[derive(Debug, Error)]
pub enum SusieError {
    #[error("z and R must have compatible lengths: z has {z_len}, R is {r_n}x{r_n}")]
    DimMismatch { z_len: usize, r_n: usize },

    #[error("R must be square")]
    RNotSquare,

    #[error("R must be symmetric")]
    RNotSymmetric,

    #[error("n must be greater than 1")]
    InvalidN,

    #[error("shat must be positive")]
    InvalidShat,

    #[error("Input z and (bhat, shat) are mutually exclusive")]
    AmbiguousInput,

    #[error("Either z or (bhat, shat) must be provided")]
    MissingInput,

    #[error("L must be at least 1")]
    InvalidL,

    #[error("coverage must be in (0, 1)")]
    InvalidCoverage,

    #[error("ELBO became infinite during fitting")]
    InfiniteElbo,

    #[error(transparent)]
    Json(#[from] serde_json::Error),
}

// ─── numerics helpers shared across modules ─────────────────────────────────

/// Machine epsilon, matching R's `.Machine$double.eps`.
pub(crate) const EPS: f64 = f64::EPSILON;

/// sqrt(.Machine$double.eps) ≈ 1.49e-8 — used as a stabilizer in log-space.
pub(crate) const SQRT_EPS: f64 = 1.4901161193847656e-8;

/// Numerically stable log-sum-exp of a slice.
#[inline]
pub(crate) fn log_sum_exp(vals: &[f64]) -> f64 {
    if vals.is_empty() {
        return f64::NEG_INFINITY;
    }
    let m = vals.iter().copied().fold(f64::NEG_INFINITY, f64::max);
    if m == f64::NEG_INFINITY {
        return f64::NEG_INFINITY;
    }
    let s: f64 = vals.iter().map(|&v| (v - m).exp()).sum();
    m + s.ln()
}

// ─── public entry point ──────────────────────────────────────────────────────

/// Fit SuSiE from GWAS regression summary statistics.
///
/// This is the Rust analogue of `susieR::susie_rss(z=, R=, n=, ...)`.
///
/// See [`RssInput`] for the full parameter set and [`SusieFit`] for the
/// returned model.
pub fn susie_rss(input: &RssInput) -> Result<SusieFit, SusieError> {
    let (data, mut params) = data::build_rss_data(input)?;
    model::fit(&data, &mut params)
}
