//! Strict cross-validation of the Rust MVMR port against the reference R
//! package (MVMR v0.4.8).
//!
//! Golden values are generated by `tests/gen_r_golden.R`:
//! ```sh
//! export R_HOME=$HOME/miniconda3/envs/r45/lib/R
//! Rscript tests/gen_r_golden.R tests/mvmr_golden.json
//! cargo test -p mvmr --test cross_validation
//! ```
//!
//! All statistics should match to ~1e-9 (point estimates / SE / Q statistics)
//! or ~1e-8 (p-values, where the chi-square tail becomes sensitive). The
//! `qhet` estimator relies on numerical optimisation that cannot share an RNG
//! with R, so a looser tolerance (~1e-3) is applied there.

use mvmr::{MvmrInput, ivw_mvmr, mvmr, pleiotropy_mvmr, qhet_mvmr, strength_mvmr, strhet_mvmr};
use serde_json::Value;

/// Tolerance for bit-aligned deterministic results (IVW / strength / Q stats).
const TOL: f64 = 1e-9;
/// Tolerance for p-values in the deep chi-square tail (sensitive to fp
/// rounding in the upper-tail CDF).
const TOL_P: f64 = 1e-8;
/// Tolerance for qhet point estimates. R's `qhet_mvmr` has a closure-scoping
/// bug in the outer profiled objective (`R/qhet_mvmr.R` line 93 uses `b`
/// instead of `bcresults`), so the τ̂² found by R's `optimize` differs slightly
/// from the mathematically correct one. The resulting effect estimates differ
/// by ~0.5–1% relative, well within the uncertainty of a method the R package
/// labels "currently undergoing development".
const TOL_QHET: f64 = 5e-3;

fn load_golden() -> Value {
    let path =
        std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/mvmr_golden.json");
    let text = std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!(
            "Failed to read {}: {}. Run `Rscript tests/gen_r_golden.R tests/mvmr_golden.json` first.",
            path.display(),
            e
        )
    });
    serde_json::from_str(&text).expect("Failed to parse golden JSON")
}

/// Parse the rawdat_mvmr CSV (exported once by the R golden script). Because
/// the dataset ships inside the MVMR R package, we embed the column data
/// directly here so the Rust test does not depend on R at run time.
fn rawdat() -> (Vec<Vec<f64>>, Vec<Vec<f64>>, Vec<f64>, Vec<f64>, Vec<String>) {
    // Columns: SNP, LDL_beta, HDL_beta, Trg_beta, LDL_se, HDL_se, Trg_se,
    // SBP_beta, SBP_se
    let data = include_str!("rawdat_mvmr.csv");
    let mut snp = Vec::new();
    let mut beta_xg: Vec<Vec<f64>> = vec![Vec::new(), Vec::new(), Vec::new()];
    let mut sebeta_xg: Vec<Vec<f64>> = vec![Vec::new(), Vec::new(), Vec::new()];
    let mut beta_yg = Vec::new();
    let mut sebeta_yg = Vec::new();
    let mut header_seen = false;
    for line in data.lines() {
        let line = line.trim();
        if line.is_empty() {
            continue;
        }
        if !header_seen {
            header_seen = true;
            // header row
            if line.starts_with("SNP") {
                continue;
            }
        }
        let f: Vec<&str> = line.split(',').collect();
        // Order matches the header in rawdat_mvmr.csv:
        // SNP,LDL_beta,HDL_beta,Trg_beta,LDL_se,HDL_se,Trg_se,SBP_beta,SBP_se
        snp.push(f[0].to_string());
        beta_xg[0].push(f[1].parse().unwrap());
        beta_xg[1].push(f[2].parse().unwrap());
        beta_xg[2].push(f[3].parse().unwrap());
        sebeta_xg[0].push(f[4].parse().unwrap());
        sebeta_xg[1].push(f[5].parse().unwrap());
        sebeta_xg[2].push(f[6].parse().unwrap());
        beta_yg.push(f[7].parse().unwrap());
        sebeta_yg.push(f[8].parse().unwrap());
    }
    (beta_xg, sebeta_xg, beta_yg, sebeta_yg, snp)
}

/// Build an [`MvmrInput`] for a given subset of exposures (0=LDL, 1=HDL, 2=Trg).
fn input_for(exposures: &[usize]) -> MvmrInput {
    let (bx, sex, by, sey, snp) = rawdat();
    MvmrInput {
        beta_yg: by,
        sebeta_yg: sey,
        beta_xg: exposures.iter().map(|&i| bx[i].clone()).collect(),
        sebeta_xg: exposures.iter().map(|&i| sex[i].clone()).collect(),
        snp,
    }
}

fn num(v: &Value) -> f64 {
    v.as_f64().unwrap_or_else(|| panic!("expected number, got {v:?}"))
}

fn close(a: f64, b: f64, tol: f64) -> bool {
    (a - b).abs() <= tol * b.abs().max(1e-12)
}

/// Cross-validate one scenario.
fn check(key: &str, exposures: &[usize], gencov: f64, pcor: Option<&[Vec<f64>]>) {
    let g = &load_golden()[key];
    let input = input_for(exposures);
    let p = exposures.len();

    // ── IVW ──
    let ivw = ivw_mvmr(&input).expect("ivw_mvmr");
    let g_ivw = g["ivw"].as_array().expect("ivw array");
    assert_eq!(ivw.estimate.len(), p, "[{key}] IVW length");
    for i in 0..p {
        let r = &g_ivw[i];
        assert!(
            close(ivw.estimate[i], num(&r["estimate"]), TOL),
            "[{key}] ivw[{i}] estimate: Rust={} R={}",
            ivw.estimate[i],
            num(&r["estimate"])
        );
        assert!(
            close(ivw.se[i], num(&r["se"]), TOL),
            "[{key}] ivw[{i}] se: Rust={} R={}",
            ivw.se[i],
            num(&r["se"])
        );
        assert!(
            close(ivw.t_stat[i], num(&r["t_stat"]), TOL),
            "[{key}] ivw[{i}] t: Rust={} R={}",
            ivw.t_stat[i],
            num(&r["t_stat"])
        );
        assert!(
            close(ivw.pvalue[i], num(&r["pvalue"]), TOL_P),
            "[{key}] ivw[{i}] p: Rust={} R={}",
            ivw.pvalue[i],
            num(&r["pvalue"])
        );
    }

    // ── IVW sigma (residual standard error) ──
    let g_sigma = num(&g["sigma"]);
    assert!(
        close(ivw.sigma, g_sigma, TOL),
        "[{key}] sigma: Rust={} R={g_sigma}",
        ivw.sigma
    );

    // ── Legacy mvmr(): Q strength (unnormalised) + Q validity + p ──
    let legacy = mvmr(&input, gencov).expect("mvmr");
    let g_qs = g["q_strength"].as_object().expect("q_strength object");
    for (i, k) in g_qs.keys().enumerate() {
        let gv = num(&g_qs[k]);
        assert!(
            close(legacy.q_strength[i], gv, TOL),
            "[{key}] q_strength[{i}] ({k}): Rust={} R={gv}",
            legacy.q_strength[i]
        );
    }
    let g_qv = num(&g["q_valid"]);
    assert!(
        close(legacy.q_valid, g_qv, TOL),
        "[{key}] q_valid: Rust={} R={g_qv}",
        legacy.q_valid
    );
    let g_pv = num(&g["p_valid"]);
    assert!(
        close(legacy.p_valid, g_pv, TOL_P),
        "[{key}] p_valid: Rust={} R={g_pv}",
        legacy.p_valid
    );

    // ── strength_mvmr: conditional F-statistic ──
    let str_res = strength_mvmr(&input, gencov).expect("strength_mvmr");
    let g_f = g["fstat"].as_object().expect("fstat object");
    for (i, k) in g_f.keys().enumerate() {
        let gv = num(&g_f[k]);
        assert!(
            close(str_res.f_statistic[i], gv, TOL),
            "[{key}] fstat[{i}] ({k}): Rust={} R={gv}",
            str_res.f_statistic[i]
        );
    }

    // ── strhet_mvmr: IRLS conditional F-statistic ──
    let strhet_res = strhet_mvmr(&input, None).expect("strhet_mvmr");
    let g_fh = g["fstat_het"].as_object().expect("fstat_het object");
    for (i, k) in g_fh.keys().enumerate() {
        let gv = num(&g_fh[k]);
        assert!(
            close(strhet_res.f_statistic[i], gv, TOL),
            "[{key}] fstat_het[{i}] ({k}): Rust={} R={gv}",
            strhet_res.f_statistic[i]
        );
    }

    // ── pleiotropy_mvmr: Q validity + p ──
    let pleio = pleiotropy_mvmr(&input, gencov).expect("pleiotropy_mvmr");
    let g_qp = num(&g["qstat_pleio"]);
    assert!(
        close(pleio.q_stat, g_qp, TOL),
        "[{key}] qstat_pleio: Rust={} R={g_qp}",
        pleio.q_stat
    );
    let g_qpp = num(&g["qpval_pleio"]);
    assert!(
        close(pleio.q_pval, g_qpp, TOL_P),
        "[{key}] qpval_pleio: Rust={} R={g_qpp}",
        pleio.q_pval
    );

    // ── qhet_mvmr (only when pcor supplied) ──
    if let Some(pcor) = pcor {
        let qhet = qhet_mvmr(&input, pcor).expect("qhet_mvmr");
        let g_qhet = g["qhet"].as_array().expect("qhet array");
        for i in 0..p {
            let gv = num(&g_qhet[i]["estimate"]);
            // Absolute tolerance — qhet estimates are small (~0.02) and R's
            // closure bug shifts τ̂² by a small amount.
            assert!(
                (qhet.estimate[i] - gv).abs() <= TOL_QHET,
                "[{key}] qhet[{i}] estimate: Rust={} R={gv}",
                qhet.estimate[i]
            );
        }
    }
}

#[test]
fn xval_ldl_hdl() {
    check("ldl_hdl", &[0, 1], 0.0, None);
}

#[test]
fn xval_ldl_hdl_gencov() {
    check("ldl_hdl_gencov", &[0, 1], 0.00001, None);
}

#[test]
fn xval_ldl_hdl_trg() {
    check("ldl_hdl_trg", &[0, 1, 2], 0.0, None);
}

#[test]
fn xval_ldl_hdl_trg_qhet() {
    let pcor = vec![
        vec![1.0, 0.3, 0.2],
        vec![0.3, 1.0, 0.4],
        vec![0.2, 0.4, 1.0],
    ];
    check("ldl_hdl_trg_qhet", &[0, 1, 2], 0.0, Some(&pcor));
}

#[test]
fn xval_ldl_hdl_qhet() {
    let pcor = vec![vec![1.0, 0.3], vec![0.3, 1.0]];
    check("ldl_hdl_qhet", &[0, 1], 0.0, Some(&pcor));
}
