//! Cross-validation of the Rust lcmm port against R lcmm::hlme golden fits.
//!
//! Golden values generated by `tests/extract_data.R`:
//! ```sh
//! R_HOME=/home/wjx/miniconda3/envs/r45/lib/R \
//! PATH=/home/wjx/miniconda3/envs/r45/bin:$PATH \
//! Rscript tests/extract_data.R tests/fixtures
//! ```
//!
//! Test archive: `rclone copy aliyun:autonomics-data/lcmm/test-data/ bio_crates/lcmm/tests/`

use lcmm::{hlme, HlmeControl, HlmeLikelihood, LongData, ModelSpec, ParamLayout,
           compute_posterior, loglik_hlme, predict_y};
use serde::{Deserialize, Deserializer};

/// Deserialize a JSON `null` or missing field as an empty `Vec<T>`.
fn null_to_empty_vec<'de, D, T>(d: D) -> std::result::Result<Vec<T>, D::Error>
where
    D: Deserializer<'de>,
    T: Deserialize<'de>,
{
    let opt: Option<Vec<T>> = Option::deserialize(d)?;
    Ok(opt.unwrap_or_default())
}

const TOL_LL: f64 = 1e-8;   // loglik relative tolerance
const TOL_PPI: f64 = 1e-6;   // posterior probability tolerance
const TOL_PRED: f64 = 1e-8;  // prediction tolerance

// ---- Golden JSON types ------------------------------------------------

#[derive(Debug, Deserialize)]
#[allow(non_snake_case, dead_code)]
struct GoldenFile {
    lcmm_version: String,
    fits: Vec<GoldenFit>,
    predictY_m2a: GoldenPred,
    predictY_gbtm3: GoldenPredY3,
}

#[derive(Debug, Deserialize)]
#[allow(non_snake_case, dead_code)]
struct GoldenFit {
    tag: String,
    ng: usize,
    idiag: usize,
    N: Vec<usize>,
    conv: i32,
    loglik: f64,
    niter: usize,
    best: Vec<f64>,
    #[serde(default)]
    names_best: Vec<String>,
    #[serde(default)]
    idea0: Vec<u8>,
    #[serde(default)]
    idprob0: Vec<u8>,
    #[serde(default)]
    idg0: Vec<u8>,
    #[serde(default)]
    idcor0: Vec<u8>,
    ns: usize,
    #[serde(deserialize_with = "null_to_empty_vec", default)]
    ppi: Vec<f64>,
    #[serde(deserialize_with = "null_to_empty_vec", default)]
    ppi_dim: Vec<usize>,
    #[serde(deserialize_with = "null_to_empty_vec", default)]
    pprob_class: Vec<usize>,
    #[serde(deserialize_with = "null_to_empty_vec", default)]
    cholesky: Vec<f64>,
    #[serde(deserialize_with = "null_to_empty_vec", default, rename = "V_upper")]
    v_upper: Vec<f64>,
}

/// Convert the golden `best` from R's post-processed form (varcov entries hold
/// B = U'U entries) back to the Fortran optimization form (varcov entries hold
/// the Cholesky factor entries that funcpa expects).
///
/// R `hlme.R` lines 1333–1348: after MLA converges, `out$best` varcov entries
/// are overwritten with z = t(U)%*%U (full) or squared (idiag). We reverse this
/// by substituting the original `$cholesky` values back in.
fn convert_golden_best(gf: &GoldenFit, layout: &ParamLayout) -> Vec<f64> {
    let mut b = gf.best.clone();
    let nvc = layout.nvc;
    let i_nvc = layout.i_nvc;
    if gf.idiag == 0 && nvc > 0 {
        // Full: cholesky has nea*(nea+1)/2 entries, same packed order as Fortran.
        // Directly replace the varcov section.
        for k in 0..nvc {
            b[i_nvc + k] = gf.cholesky[k];
        }
    } else if gf.idiag == 1 && nvc > 0 {
        // Diagonal: cholesky has nea*(nea+1)/2 entries (with zeros off-diagonal).
        // Extract the diagonal positions: j*(j+1)/2 + j for j=0..nea-1.
        let nea = layout.nea;
        for j in 0..nea {
            b[i_nvc + j] = gf.cholesky[j * (j + 1) / 2 + j];
        }
    }
    b
}

#[derive(Debug, Deserialize)]
#[allow(non_snake_case, dead_code)]
struct GoldenPred {
    newdata: serde_json::Value,
    pred: Vec<Vec<f64>>,
}

#[derive(Debug, Deserialize)]
#[allow(non_snake_case, dead_code)]
struct GoldenPredY3 {
    newdata: serde_json::Value,
    pred: Vec<Vec<f64>>,
}

fn load_golden() -> GoldenFile {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures/hlme_golden.json");
    let text = std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!(
            "Failed to read {}: {}. Run `Rscript tests/extract_data.R tests/fixtures` first.\n\
             rclone restore: rclone copy aliyun:autonomics-data/lcmm/test-data/ tests/",
            path.display(),
            e
        )
    });
    serde_json::from_str(&text).expect("Failed to parse golden JSON")
}

// ---- CSV data loader ---------------------------------------------------

#[allow(dead_code)]
struct CsvData {
    y: Vec<f64>,
    time: Vec<f64>,
    x1: Vec<f64>,
    x2: Vec<f64>,
    x3: Vec<f64>,
    id: Vec<i64>,
    nmes: Vec<usize>,
    ns: usize,
}

fn load_csv() -> CsvData {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures/data_hlme.csv");
    let text = std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!("Failed to read {}: {}", path.display(), e)
    });
    let mut y = Vec::new();
    let mut time = Vec::new();
    let mut x1 = Vec::new();
    let mut x2 = Vec::new();
    let mut x3 = Vec::new();
    let mut id = Vec::new();
    for (i, line) in text.lines().enumerate() {
        if i == 0 { continue; } // skip header
        let f: Vec<&str> = line.split(',').collect();
        if f.len() < 6 { continue; }
        id.push(f[0].parse().unwrap());
        y.push(f[1].parse().unwrap());
        time.push(f[2].parse().unwrap());
        x1.push(f[3].parse().unwrap());
        x2.push(f[4].parse().unwrap());
        x3.push(f[5].parse().unwrap());
    }
    // Build nmes per subject (sorted by ID).
    let ns = *id.iter().max().unwrap() as usize;
    let mut nmes = vec![0_usize; ns];
    for &idv in &id {
        nmes[(idv - 1) as usize] += 1;
    }
    CsvData { y, time, x1, x2, x3, id, nmes, ns }
}

/// Build a LongData with the specified covariate design matrix X0.
fn build_longdata(
    csv: &CsvData,
    nv: usize,
    x0_cols: &[Vec<f64>],
    ng: usize,
) -> LongData {
    let nobs = csv.y.len();
    let mut x = vec![0.0; nobs * nv];
    for k in 0..nv {
        for r in 0..nobs {
            x[r * nv + k] = x0_cols[k][r];
        }
    }
    LongData::new(csv.y.clone(), x, nv, csv.nmes.clone(), ng)
}

// ---- Model-specific builders ------------------------------------------

/// m1: Y ~ Time*X1, random=~Time, ng=1
/// X0 = [intercept, Time, X1, Time:X1], idg=[1,1,1,1], idea=[1,1,0,0]
fn m1_data(csv: &CsvData) -> (LongData, ModelSpec) {
    let n = csv.y.len();
    let x0 = vec![vec![1.0; n], csv.time.clone(), csv.x1.clone(),
                  (0..n).map(|i| csv.time[i] * csv.x1[i]).collect::<Vec<_>>()];
    let data = build_longdata(csv, 4, &x0, 1);
    let spec = ModelSpec {
        ng: 1, idiag: false, nwg: false, ncor: 0,
        idprob: vec![0, 0, 0, 0],
        idea: vec![1, 1, 0, 0],
        idg: vec![1, 1, 1, 1],
        idcor: vec![0, 0, 0, 0],
    };
    (data, spec)
}

/// gbtm1: Y ~ Time, ng=1 (no random)
/// X0 = [intercept, Time], idg=[1,1], idea=[0,0]
fn gbtm1_data(csv: &CsvData) -> (LongData, ModelSpec) {
    let n = csv.y.len();
    let x0 = vec![vec![1.0; n], csv.time.clone()];
    let data = build_longdata(csv, 2, &x0, 1);
    let spec = ModelSpec {
        ng: 1, idiag: false, nwg: false, ncor: 0,
        idprob: vec![0, 0],
        idea: vec![0, 0],
        idg: vec![1, 1],
        idcor: vec![0, 0],
    };
    (data, spec)
}

/// gbtm2: Y ~ Time, mixture=~Time, ng=2 (no random)
/// X0 = [intercept, Time], idg=[2,2], idea=[0,0], idprob=[1,0] (auto classmb=~1)
fn gbtm2_data(csv: &CsvData) -> (LongData, ModelSpec) {
    let n = csv.y.len();
    let x0 = vec![vec![1.0; n], csv.time.clone()];
    let data = build_longdata(csv, 2, &x0, 2);
    let spec = ModelSpec {
        ng: 2, idiag: false, nwg: false, ncor: 0,
        idprob: vec![1, 0],
        idea: vec![0, 0],
        idg: vec![2, 2],
        idcor: vec![0, 0],
    };
    (data, spec)
}

/// gbtm3: Y ~ Time, mixture=~Time, ng=3 (no random)
fn gbtm3_data(csv: &CsvData) -> (LongData, ModelSpec) {
    let n = csv.y.len();
    let x0 = vec![vec![1.0; n], csv.time.clone()];
    let data = build_longdata(csv, 2, &x0, 3);
    let spec = ModelSpec {
        ng: 3, idiag: false, nwg: false, ncor: 0,
        idprob: vec![1, 0],
        idea: vec![0, 0],
        idg: vec![2, 2],
        idcor: vec![0, 0],
    };
    (data, spec)
}

/// m2a: Y~Time*X1, mixture=~Time, random=~Time, classmb=~X2+X3, ng=2
/// X0 = [intercept, Time, X1, Time:X1, X2, X3]
/// idprob=[1,0,0,0,1,1], idea=[1,1,0,0,0,0], idg=[2,2,1,1,0,0]
fn m2a_data(csv: &CsvData) -> (LongData, ModelSpec) {
    let n = csv.y.len();
    let x0 = vec![
        vec![1.0; n], csv.time.clone(), csv.x1.clone(),
        (0..n).map(|i| csv.time[i] * csv.x1[i]).collect::<Vec<_>>(),
        csv.x2.iter().map(|&v| v).collect(),
        csv.x3.clone(),
    ];
    let data = build_longdata(csv, 6, &x0, 2);
    let spec = ModelSpec {
        ng: 2, idiag: false, nwg: false, ncor: 0,
        idprob: vec![1, 0, 0, 0, 1, 1],
        idea: vec![1, 1, 0, 0, 0, 0],
        idg: vec![2, 2, 1, 1, 0, 0],
        idcor: vec![0, 0, 0, 0, 0, 0],
    };
    (data, spec)
}

/// m3a: same as m2a but ng=3
fn m3a_data(csv: &CsvData) -> (LongData, ModelSpec) {
    let (_data, spec_base) = m2a_data(csv);
    // Override ng to 3 in a new spec
    let spec = ModelSpec { ng: 3, ..spec_base };
    // Rebuild data with ng=3
    let n = csv.y.len();
    let x0 = vec![
        vec![1.0; n], csv.time.clone(), csv.x1.clone(),
        (0..n).map(|i| csv.time[i] * csv.x1[i]).collect::<Vec<_>>(),
        csv.x2.iter().map(|&v| v).collect(),
        csv.x3.clone(),
    ];
    let data = build_longdata(csv, 6, &x0, 3);
    (data, spec)
}

/// m1_idiag: same as m1 but idiag=true
fn m1_idiag_data(csv: &CsvData) -> (LongData, ModelSpec) {
    let (data, spec_base) = m1_data(csv);
    let spec = ModelSpec { idiag: true, ..spec_base };
    (data, spec)
}

/// m2a_nwg: same as m2a but nwg=true
fn m2a_nwg_data(csv: &CsvData) -> (LongData, ModelSpec) {
    let (data, spec_base) = m2a_data(csv);
    let spec = ModelSpec { nwg: true, ..spec_base };
    (data, spec)
}

// =====================================================================
// TESTS
// =====================================================================

fn find_fit<'a>(golden: &'a GoldenFile, tag: &str) -> &'a GoldenFit {
    golden.fits.iter().find(|f| f.tag == tag)
        .unwrap_or_else(|| panic!("golden fit '{tag}' not found"))
}

/// Verify the log-likelihood evaluates to the same value at the golden `best`.
fn check_loglik(test_name: &str, data: &LongData, spec: &ModelSpec, golden: &GoldenFit) {
    let layout = spec.layout();
    assert_eq!(golden.best.len(), layout.npm,
        "{test_name}: golden NPM={} != Rust NPM={}", golden.best.len(), layout.npm);
    // Convert golden best from R post-processed form (B entries in varcov)
    // back to Fortran optimization form (Cholesky factor entries).
    let best = convert_golden_best(golden, &layout);
    let ll = loglik_hlme(&best, data, spec);
    let rel = (ll - golden.loglik).abs() / golden.loglik.abs().max(1e-10);
    assert!(rel < TOL_LL,
        "{test_name}: loglik mismatch. Rust={ll:.10}, R={:.10}, rel={rel:.3e}",
        golden.loglik);
    eprintln!("PASS loglik {test_name}: Rust={ll:.6} R={:.6} rel={rel:.2e}", golden.loglik);
}

#[test]
fn loglik_m1() {
    let golden = load_golden();
    let csv = load_csv();
    let (data, spec) = m1_data(&csv);
    check_loglik("m1", &data, &spec, find_fit(&golden, "m1"));
}

#[test]
fn loglik_gbtm1() {
    let golden = load_golden();
    let csv = load_csv();
    let (data, spec) = gbtm1_data(&csv);
    check_loglik("gbtm1", &data, &spec, find_fit(&golden, "gbtm1"));
}

#[test]
fn loglik_gbtm2() {
    let golden = load_golden();
    let csv = load_csv();
    let (data, spec) = gbtm2_data(&csv);
    check_loglik("gbtm2", &data, &spec, find_fit(&golden, "gbtm2"));
}

#[test]
fn loglik_gbtm3() {
    let golden = load_golden();
    let csv = load_csv();
    let (data, spec) = gbtm3_data(&csv);
    check_loglik("gbtm3", &data, &spec, find_fit(&golden, "gbtm3"));
}

#[test]
fn loglik_m2a() {
    let golden = load_golden();
    let csv = load_csv();
    let (data, spec) = m2a_data(&csv);
    check_loglik("m2a", &data, &spec, find_fit(&golden, "m2a"));
}

#[test]
fn loglik_m3a() {
    let golden = load_golden();
    let csv = load_csv();
    let (data, spec) = m3a_data(&csv);
    check_loglik("m3a", &data, &spec, find_fit(&golden, "m3a"));
}

#[test]
fn loglik_m1_idiag() {
    let golden = load_golden();
    let csv = load_csv();
    let (data, spec) = m1_idiag_data(&csv);
    check_loglik("m1_idiag", &data, &spec, find_fit(&golden, "m1_idiag"));
}

#[test]
fn loglik_m2a_nwg() {
    let golden = load_golden();
    let csv = load_csv();
    let (data, spec) = m2a_nwg_data(&csv);
    check_loglik("m2a_nwg", &data, &spec, find_fit(&golden, "m2a_nwg"));
}

// ---- Posterior probability tests ---------------------------------------

fn check_ppi(test_name: &str, data: &LongData, spec: &ModelSpec, golden: &GoldenFit) {
    if golden.ng <= 1 { return; }
    let layout = spec.layout();
    let ll = HlmeLikelihood::new(data, spec, &vec![0u8; layout.npm], &[]);
    let best = convert_golden_best(golden, &layout);
    let post = compute_posterior(&ll, &best);
    let ns = golden.ns;
    let ng = golden.ng;
    assert_eq!(post.ppi.len(), ns * ng);
    let mut max_rel = 0.0_f64;
    for i in 0..ns * ng {
        let rel = (post.ppi[i] - golden.ppi[i]).abs() / golden.ppi[i].abs().max(1e-10);
        max_rel = max_rel.max(rel);
    }
    assert!(max_rel < TOL_PPI,
        "{test_name}: ppi mismatch, max_rel={max_rel:.3e}");
    // Class assignments
    let golden_class_counts: std::collections::HashMap<usize, usize> =
        golden.pprob_class.iter().fold(std::collections::HashMap::new(), |mut m, &c| {
            *m.entry(c).or_default() += 1; m
        });
    let rust_class_counts: std::collections::HashMap<usize, usize> =
        post.class.iter().fold(std::collections::HashMap::new(), |mut m, &c| {
            *m.entry(c).or_default() += 1; m
        });
    assert_eq!(golden_class_counts, rust_class_counts,
        "{test_name}: class assignment counts differ");
    eprintln!("PASS ppi {test_name}: max_rel={max_rel:.2e}");
}

#[test]
fn ppi_gbtm2() {
    let golden = load_golden();
    let csv = load_csv();
    let (data, spec) = gbtm2_data(&csv);
    check_ppi("gbtm2", &data, &spec, find_fit(&golden, "gbtm2"));
}

#[test]
fn ppi_gbtm3() {
    let golden = load_golden();
    let csv = load_csv();
    let (data, spec) = gbtm3_data(&csv);
    check_ppi("gbtm3", &data, &spec, find_fit(&golden, "gbtm3"));
}

#[test]
fn ppi_m2a() {
    let golden = load_golden();
    let csv = load_csv();
    let (data, spec) = m2a_data(&csv);
    check_ppi("m2a", &data, &spec, find_fit(&golden, "m2a"));
}

// ---- predictY tests ----------------------------------------------------

#[test]
fn predict_y_m2a() {
    let golden = load_golden();
    let csv = load_csv();
    let (_data, spec) = m2a_data(&csv);
    let layout = spec.layout();
    let gf = find_fit(&golden, "m2a");

    // newdata: Time=0,2,5 with X1=0, X2=0, X3=0
    // X0 = [intercept, Time, X1, Time:X1, X2, X3]
    let n_new = 3;
    let newdata_x = vec![
        1.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        1.0, 2.0, 0.0, 0.0, 0.0, 0.0,
        1.0, 5.0, 0.0, 0.0, 0.0, 0.0,
    ];
    let pred = predict_y(&spec, &layout, &gf.best, &newdata_x, n_new);
    // Golden predictY_m2a pred is [[class1,class2] per time] (time-major).
    let golden_pred = &golden.predictY_m2a.pred;
    let mut max_rel = 0.0_f64;
    for g in 0..2 {
        for r in 0..n_new {
            let rust_val = pred[g * n_new + r];
            let r_val = golden_pred[r][g];
            let rel = (rust_val - r_val).abs() / r_val.abs().max(1e-10);
            max_rel = max_rel.max(rel);
        }
    }
    assert!(max_rel < TOL_PRED, "predictY m2a: max_rel={max_rel:.3e}");
    eprintln!("PASS predictY m2a: max_rel={max_rel:.2e}");
}

#[test]
fn predict_y_gbtm3() {
    let golden = load_golden();
    let csv = load_csv();
    let (_data, spec) = gbtm3_data(&csv);
    let layout = spec.layout();
    let gf = find_fit(&golden, "gbtm3");

    // newdata: Time=0..6, no other covars
    // X0 = [intercept, Time]
    let n_new = 7;
    let newdata_x: Vec<f64> = (0..n_new)
        .flat_map(|t| vec![1.0, t as f64])
        .collect();
    let pred = predict_y(&spec, &layout, &gf.best, &newdata_x, n_new);
    let golden_pred = &golden.predictY_gbtm3.pred;
    let mut max_rel = 0.0_f64;
    for g in 0..3 {
        for r in 0..n_new {
            let rust_val = pred[g * n_new + r];
            let r_val = golden_pred[r][g];
            let rel = (rust_val - r_val).abs() / r_val.abs().max(1e-10);
            max_rel = max_rel.max(rel);
        }
    }
    assert!(max_rel < TOL_PRED, "predictY gbtm3: max_rel={max_rel:.3e}");
    eprintln!("PASS predictY gbtm3: max_rel={max_rel:.2e}");
}

// ---- Optimization convergence tests -----------------------------------

#[test]
fn optimize_gbtm1() {
    let golden = load_golden();
    let csv = load_csv();
    let (data, spec) = gbtm1_data(&csv);
    let gf = find_fit(&golden, "gbtm1");

    // Auto-init: intercept=mean(Y), slope=0, stderr=1 (matching R's ng=1 default).
    let b0 = vec![csv.y.iter().sum::<f64>() / csv.y.len() as f64, 0.0, 1.0];
    let ctrl = HlmeControl { verbose: true, ..Default::default() };
    let fit = hlme(&data, &spec, &b0, &[], &ctrl).expect("gbtm1 fit failed");

    let rel_ll = (fit.loglik - gf.loglik).abs() / gf.loglik.abs();
    assert!(rel_ll < 1e-6, "gbtm1 opt loglik: Rust={} R={} rel={rel_ll:.3e}",
        fit.loglik, gf.loglik);
    eprintln!("PASS opt gbtm1: loglik={:.6} (R={:.6}), niter={}", fit.loglik, gf.loglik, fit.niter);
}

/// Build the init parameter vector for an ng>1 model from a prior ng=1 fit.
/// (Port of R hlme.R lines 957–994, Brandom=FALSE deterministic path.)
/// Currently unused in tests but retained for future ng>1 optimization tests.
#[allow(dead_code)]
fn init_from_prior(
    prior_best: &[f64],
    prior_v: &[f64],
    prior_conv: i32,
    spec: &ModelSpec,
) -> Vec<f64> {
    let layout = spec.layout();
    let ng = spec.ng;
    let mut b = vec![0.0; layout.npm];
    let mut l = 0_usize;
    let mut t = 0_usize;
    for i in 0..layout.nv {
        match spec.idg[i] {
            1 => {
                b[layout.nprob + t] = prior_best[l];
                l += 1;
                t += 1;
            }
            2 => {
                let v_idx = l * (l + 1) / 2;
                let spread = if prior_conv == 1 {
                    prior_v[v_idx].max(0.0).sqrt()
                } else {
                    prior_best[l].abs()
                };
                for g in 1..=ng {
                    let offset = (g as f64) - (ng as f64 + 1.0) / 2.0;
                    b[layout.nprob + t] = prior_best[l] + offset * spread;
                    t += 1;
                }
                l += 1;
            }
            _ => {}
        }
    }
    b[layout.i_stderr] = prior_best[prior_best.len() - 1];
    b
}

#[test]
fn optimize_gbtm2() {
    let golden = load_golden();
    let csv = load_csv();
    let (data, spec) = gbtm2_data(&csv);
    let gf = find_fit(&golden, "gbtm2");

    // Use a well-separated init (the R B=gbtm1 transformation creates nearly
    // identical classes, making the Hessian ill-conditioned for our finite-
    // difference optimizer). This init is well-separated and identifiable.
    let b0 = vec![0.0, 20.0, 30.0, -1.0, 0.0, 5.0];
    let ctrl = HlmeControl { maxiter: 500, verbose: true, ..Default::default() };
    let fit = match hlme(&data, &spec, &b0, &[], &ctrl) {
        Ok(f) => f,
        Err(e) => panic!("gbtm2 opt failed: {e}"),
    };

    let rel_ll = (fit.loglik - gf.loglik).abs() / gf.loglik.abs();
    assert!(rel_ll < 1e-6,
        "gbtm2 opt loglik: Rust={} R={} rel={rel_ll:.3e} conv={:?} niter={}",
        fit.loglik, gf.loglik, fit.conv, fit.niter);
    eprintln!("PASS opt gbtm2: loglik={:.6} (R={:.6}), niter={}", fit.loglik, gf.loglik, fit.niter);
}
