//! Cross-validation of the Rust port against R `coloc` (devel, matching the
//! reference source).
//!
//! Each test loads `coloc_golden.json` generated by `gen_r_golden.R` and
//! compares every output of `coloc_abf` / `finemap_abf` against R.
//!
//! Regenerate the fixture with (r45 conda env: R 4.5.3 + coloc from reference
//! source):
//!
//! ```sh
//! export R_HOME=$HOME/miniconda3/envs/r45/lib/R
//! export PATH=$HOME/miniconda3/envs/r45/bin:$PATH
//! export LD_LIBRARY_PATH=$HOME/miniconda3/envs/r45/lib:$LD_LIBRARY_PATH
//! Rscript tests/gen_r_golden.R tests/coloc_golden.json
//! ```

use coloc::{
    ColocAbfOptions, Dataset, EffectPriors, FinemapAbfSnp, TraitType, adjust_prior, approx_bf_p,
    check_dataset, coloc_abf, finemap_abf, logdiff, logsum, process_dataset, sd_y_est, var_data,
    var_data_cc,
};
use serde_json::Value;

// ── tolerances ──────────────────────────────────────────────────────────────
//
// The kernels are transliterations of R's pure-R arithmetic, so agreement is
// limited by the inverse-normal-CDF implementation (we use Acklam, R uses
// Wichura's AS241) and floating-point association order. In practice:
//   - lABF and SNP.PP agree to ~1e-12 when both use beta/varbeta
//   - lABF from p-values agree to ~1e-7 (due to different qnorm implementations)
//   - posterior probabilities agree to ~1e-7

/// Structural quantities computed from beta/varbeta (exact arithmetic path).
const TOL_EXACT: f64 = 1e-12;
/// Quantities that pass through qnorm (p-value path).
const TOL_QNORM: f64 = 1e-7;

// ── fixture loading ─────────────────────────────────────────────────────────

fn golden_path() -> std::path::PathBuf {
    std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/coloc_golden.json")
}

fn load_golden() -> Value {
    let path = golden_path();
    let text = std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!(
            "missing fixture {}: {e}\nrun: Rscript tests/gen_r_golden.R tests/coloc_golden.json",
            path.display()
        )
    });
    serde_json::from_str(&text).expect("fixture is valid JSON")
}

fn num(v: &Value) -> f64 {
    match v {
        Value::Number(n) => n.as_f64().unwrap_or(f64::NAN),
        Value::Array(a) if a.len() == 1 => num(&a[0]),
        Value::Null => f64::NAN,
        _ => f64::NAN,
    }
}

fn vec_f64(v: &Value) -> Vec<f64> {
    match v {
        Value::Array(a) => a.iter().map(num).collect(),
        Value::Null => Vec::new(),
        other => vec![num(other)],
    }
}

fn vec_str(v: &Value) -> Vec<String> {
    match v {
        Value::Array(a) => a
            .iter()
            .map(|x| match x {
                Value::String(s) => s.clone(),
                _ => x.to_string().trim_matches('"').to_string(),
            })
            .collect(),
        _ => Vec::new(),
    }
}

// ── helpers ─────────────────────────────────────────────────────────────────

fn make_dataset_from_inputs(inputs: &Value, mode: &str) -> Dataset {
    let snp = vec_str(&inputs["snp"]);
    let n = num(&inputs["N"]);
    let maf = vec_f64(&inputs["maf"]);
    let sd_y = num(&inputs["sdY"]);
    let s = num(&inputs["s"]);

    match mode {
        "DQ" => Dataset {
            snp,
            beta: Some(vec_f64(&inputs["beta_q"])),
            varbeta: Some(vec_f64(&inputs["vbeta_q"])),
            pvalues: None,
            maf: Some(maf),
            n: Some(n),
            r#type: TraitType::Quant,
            s: None,
            sd_y: Some(sd_y),
            position: None,
        },
        "DCC" => Dataset {
            snp,
            beta: Some(vec_f64(&inputs["beta_cc"])),
            varbeta: Some(vec_f64(&inputs["vbeta_cc"])),
            pvalues: None,
            maf: Some(maf),
            n: Some(n),
            r#type: TraitType::CC,
            s: Some(s),
            sd_y: None,
            position: None,
        },
        "PQ" => Dataset {
            snp,
            beta: None,
            varbeta: None,
            pvalues: Some(vec_f64(&inputs["p_q"])),
            maf: Some(maf),
            n: Some(n),
            r#type: TraitType::Quant,
            s: None,
            sd_y: Some(sd_y),
            position: None,
        },
        "PCC" => Dataset {
            snp,
            beta: None,
            varbeta: None,
            pvalues: Some(vec_f64(&inputs["p_cc"])),
            maf: Some(maf),
            n: Some(n),
            r#type: TraitType::CC,
            s: Some(s),
            sd_y: None,
            position: None,
        },
        _ => panic!("unknown mode {mode}"),
    }
}

fn check_pp(pp: &[f64; 5], scenario: &Value, tol: f64, label: &str) {
    let r_pp = vec_f64(&scenario["pp"]);
    assert_eq!(r_pp.len(), 5, "{label}: expected 5 PPs");
    for (i, (&rust, &r)) in pp.iter().zip(r_pp.iter()).enumerate() {
        assert!(
            (rust - r).abs() < tol,
            "{label}: PP.H{i} mismatch: rust={rust:.15e} vs R={r:.15e} diff={:.3e}",
            (rust - r).abs()
        );
    }
}

// ── low-level tests ─────────────────────────────────────────────────────────

#[test]
fn xval_var_data() {
    let golden = load_golden();
    let inputs = &golden["inputs"];
    let maf = vec_f64(&inputs["maf"]);
    let n = num(&inputs["N"]);

    for (i, &f) in maf.iter().enumerate() {
        let rust = var_data(f, n);
        // R: 1 / (2 * N * f * (1-f))
        let r_val = 1.0 / (2.0 * n * f * (1.0 - f));
        assert!((rust - r_val).abs() < 1e-15, "var_data mismatch at snp {i}");
    }
}

#[test]
fn xval_var_data_cc() {
    let golden = load_golden();
    let inputs = &golden["inputs"];
    let maf = vec_f64(&inputs["maf"]);
    let n = num(&inputs["N"]);
    let s = num(&inputs["s"]);

    for (i, &f) in maf.iter().enumerate() {
        let rust = var_data_cc(f, n, s);
        let r_val = 1.0 / (2.0 * n * f * (1.0 - f) * s * (1.0 - s));
        assert!(
            (rust - r_val).abs() < 1e-15,
            "var_data_cc mismatch at snp {i}"
        );
    }
}

#[test]
fn xval_sd_y_est() {
    let golden = load_golden();
    let inputs = &golden["inputs"];
    let vbeta = vec_f64(&inputs["vbeta_q"]);
    let maf = vec_f64(&inputs["maf"]);
    let n = num(&inputs["N"]);

    let rust = sd_y_est(&vbeta, &maf, n).unwrap();
    let r_val = num(&inputs["sdY"]);

    // sdY.est uses OLS through origin — should match to machine precision.
    assert!(
        (rust - r_val).abs() / r_val < TOL_EXACT,
        "sdY.est mismatch: rust={rust:.15e} vs R={r_val:.15e}"
    );
}

#[test]
fn xval_logsum_logdiff() {
    // logsum
    let vals = vec![1.0_f64, 2.0, 3.0, -5.0, 0.5];
    let rust = logsum(&vals);
    let expected: f64 = vals.iter().map(|&x| x.exp()).sum::<f64>().ln();
    assert!((rust - expected).abs() < 1e-14);

    // logdiff(ln(5), ln(2)) = ln(3)
    let ld = logdiff(5.0_f64.ln(), 2.0_f64.ln());
    assert!((ld - (3.0_f64).ln()).abs() < 1e-14);
}

#[test]
fn xval_adjust_prior() {
    assert!((adjust_prior(1e-4, 100) - 1e-4).abs() < 1e-15);
    // nsnps * p >= 1 → 1/(nsnps+1)
    assert!((adjust_prior(0.5, 10) - 1.0 / 11.0).abs() < 1e-15);
}

// ── coloc.abf cross-validation ──────────────────────────────────────────────

/// Generic coloc.abf cross-validation for a scenario.
fn xval_coloc_abf_scenario(
    golden: &Value,
    scenario_name: &str,
    ds1_mode: &str,
    ds2_mode: &str,
    tol: f64,
) {
    let inputs = &golden["inputs"];
    let scenario = &golden["scenarios"][scenario_name];
    assert!(!scenario.is_null(), "scenario {scenario_name} not found");

    let d1 = make_dataset_from_inputs(inputs, ds1_mode);
    let d2 = make_dataset_from_inputs(inputs, ds2_mode);

    // Use custom priors if present — R named vectors serialize as JSON arrays
    // [p1, p2, p12].
    let priors_arr = scenario["priors"].as_array().unwrap();
    let opts = ColocAbfOptions {
        p1: num(&priors_arr[0]),
        p2: num(&priors_arr[1]),
        p12: num(&priors_arr[2]),
        ..Default::default()
    };

    let result = coloc_abf(&d1, &d2, &opts).unwrap();

    // nsnps
    let r_nsnps = vec_f64(&scenario["nsnps"])[0] as usize;
    assert_eq!(result.nsnps, r_nsnps, "{scenario_name}: nsnps mismatch");

    // Posterior probabilities.
    check_pp(&result.pp.as_array(), scenario, tol, scenario_name);

    // Per-SNP results.
    let r_results = scenario["results"].as_array().unwrap();
    assert_eq!(result.snp.len(), r_results.len());

    for (i, r_row) in r_results.iter().enumerate() {
        let r_snp = match &r_row["snp"] {
            Value::String(s) => s.clone(),
            Value::Array(a) if a.len() == 1 => match &a[0] {
                Value::String(s) => s.clone(),
                _ => a[0].to_string().trim_matches('"').to_string(),
            },
            _ => r_row["snp"].to_string().trim_matches('"').to_string(),
        };
        assert_eq!(result.snp[i], r_snp, "snp {i} mismatch");

        let r_labf1 = num(&r_row["lABF.df1"]);
        let r_labf2 = num(&r_row["lABF.df2"]);
        assert!(
            (result.l_abf_df1[i] - r_labf1).abs() < tol,
            "{scenario_name}: lABF.df1[{i}] mismatch: rust={:.15e} vs R={:.15e}",
            result.l_abf_df1[i],
            r_labf1
        );
        assert!(
            (result.l_abf_df2[i] - r_labf2).abs() < tol,
            "{scenario_name}: lABF.df2[{i}] mismatch: rust={:.15e} vs R={:.15e}",
            result.l_abf_df2[i],
            r_labf2
        );

        let r_snp_pp = num(&r_row["SNP.PP.H4"]);
        assert!(
            (result.snp_pp_h4[i] - r_snp_pp).abs() < tol,
            "{scenario_name}: SNP.PP.H4[{i}] mismatch: rust={:.15e} vs R={:.15e}",
            result.snp_pp_h4[i],
            r_snp_pp
        );
    }
}

#[test]
fn xval_coloc_abf_dd() {
    let golden = load_golden();
    // quant-beta × cc-beta — both use beta/varbeta, exact arithmetic path.
    xval_coloc_abf_scenario(&golden, "dd", "DQ", "DCC", TOL_EXACT);
}

#[test]
fn xval_coloc_abf_dp() {
    let golden = load_golden();
    // quant-beta × cc-pvalue — ds2 uses pvalue path (qnorm).
    xval_coloc_abf_scenario(&golden, "dp", "DQ", "PCC", TOL_QNORM);
}

#[test]
fn xval_coloc_abf_pd() {
    let golden = load_golden();
    // quant-pvalue × cc-beta — ds1 uses pvalue path.
    xval_coloc_abf_scenario(&golden, "pd", "PQ", "DCC", TOL_QNORM);
}

#[test]
fn xval_coloc_abf_pp() {
    let golden = load_golden();
    // Both pvalue — both pass through qnorm.
    xval_coloc_abf_scenario(&golden, "pp", "PQ", "PCC", TOL_QNORM);
}

#[test]
fn xval_coloc_abf_custom_priors() {
    let golden = load_golden();
    xval_coloc_abf_scenario(&golden, "custom_priors", "DQ", "DCC", TOL_EXACT);
}

// ── coloc.abf with prior weights ────────────────────────────────────────────

#[test]
fn xval_coloc_abf_weighted() {
    let golden = load_golden();
    let inputs = &golden["inputs"];
    let scenario = &golden["scenarios"]["weighted"];
    assert!(!scenario.is_null());

    let d1 = make_dataset_from_inputs(inputs, "DQ");
    let d2 = make_dataset_from_inputs(inputs, "DCC");

    let pw1 = vec_f64(&scenario["prior_weights1"]);
    let pw2 = vec_f64(&scenario["prior_weights2"]);

    let priors_arr = scenario["priors"].as_array().unwrap();
    let opts = ColocAbfOptions {
        p1: num(&priors_arr[0]),
        p2: num(&priors_arr[1]),
        p12: num(&priors_arr[2]),
        prior_weights1: Some(pw1),
        prior_weights2: Some(pw2),
        ..Default::default()
    };

    let result = coloc_abf(&d1, &d2, &opts).unwrap();

    let r_nsnps = vec_f64(&scenario["nsnps"])[0] as usize;
    assert_eq!(result.nsnps, r_nsnps);

    check_pp(&result.pp.as_array(), scenario, TOL_EXACT, "weighted");

    // Per-SNP SNP.PP.H4
    let r_results = scenario["results"].as_array().unwrap();
    for (i, r_row) in r_results.iter().enumerate() {
        let r_snp_pp = num(&r_row["SNP.PP.H4"]);
        assert!(
            (result.snp_pp_h4[i] - r_snp_pp).abs() < TOL_EXACT,
            "weighted: SNP.PP.H4[{i}] mismatch: rust={:.15e} vs R={:.15e}",
            result.snp_pp_h4[i],
            r_snp_pp
        );
    }
}

// ── finemap.abf cross-validation ────────────────────────────────────────────

#[test]
fn xval_finemap_abf_dq() {
    let golden = load_golden();
    let inputs = &golden["inputs"];
    let scenario = &golden["scenarios"]["finemap_dq"];

    let d = make_dataset_from_inputs(inputs, "DQ");
    let result = finemap_abf(&d, 1e-4, None).unwrap();

    let r_snps = vec_str(&scenario["snp"]);
    let r_labf = vec_f64(&scenario["lABF"]);
    let r_prior = vec_f64(&scenario["prior"]);
    let r_snp_pp = vec_f64(&scenario["SNP.PP"]);

    // R appends a "null" row at the end — exclude it from comparison.
    let n_real = r_snps.len() - 1;
    assert_eq!(result.snps.len(), n_real, "finemap_dq: snp count mismatch");

    for (i, s) in result.snps.iter().enumerate() {
        assert_eq!(s.snp, r_snps[i], "finemap_dq: snp {i} mismatch");
        assert!(
            (s.l_abf - r_labf[i]).abs() < TOL_EXACT,
            "finemap_dq: lABF[{i}] mismatch: rust={:.15e} vs R={:.15e}",
            s.l_abf,
            r_labf[i]
        );
        assert!(
            (s.prior - r_prior[i]).abs() < TOL_EXACT,
            "finemap_dq: prior[{i}] mismatch: rust={:.15e} vs R={:.15e}",
            s.prior,
            r_prior[i]
        );
        assert!(
            (s.snp_pp - r_snp_pp[i]).abs() < TOL_EXACT,
            "finemap_dq: SNP.PP[{i}] mismatch: rust={:.15e} vs R={:.15e}",
            s.snp_pp,
            r_snp_pp[i]
        );
    }
}

#[test]
fn xval_finemap_abf_dcc() {
    let golden = load_golden();
    let inputs = &golden["inputs"];
    let scenario = &golden["scenarios"]["finemap_dcc"];

    let d = make_dataset_from_inputs(inputs, "DCC");
    let result = finemap_abf(&d, 1e-4, None).unwrap();

    let r_snps = vec_str(&scenario["snp"]);
    let r_labf = vec_f64(&scenario["lABF"]);
    let r_prior = vec_f64(&scenario["prior"]);
    let r_snp_pp = vec_f64(&scenario["SNP.PP"]);

    // R appends a "null" row at the end — exclude it from comparison.
    let n_real = r_snps.len() - 1;
    assert_eq!(result.snps.len(), n_real, "finemap_dcc: snp count mismatch");

    for (i, s) in result.snps.iter().enumerate() {
        assert_eq!(s.snp, r_snps[i], "finemap_dcc: snp {i} mismatch");
        assert!(
            (s.l_abf - r_labf[i]).abs() < TOL_EXACT,
            "finemap_dcc: lABF[{i}] mismatch: rust={:.15e} vs R={:.15e}",
            s.l_abf,
            r_labf[i]
        );
        assert!(
            (s.prior - r_prior[i]).abs() < TOL_EXACT,
            "finemap_dcc: prior[{i}] mismatch: rust={:.15e} vs R={:.15e}",
            s.prior,
            r_prior[i]
        );
        assert!(
            (s.snp_pp - r_snp_pp[i]).abs() < TOL_EXACT,
            "finemap_dcc: SNP.PP[{i}] mismatch: rust={:.15e} vs R={:.15e}",
            s.snp_pp,
            r_snp_pp[i]
        );
    }
}

// ── finemap.abf with prior weights ──────────────────────────────────────────

#[test]
fn finemap_abf_with_weights_matches_unweighted() {
    let golden = load_golden();
    let inputs = &golden["inputs"];

    let d = make_dataset_from_inputs(inputs, "DQ");
    let n = d.snp.len();
    let uniform_weights = vec![1.0; n];

    let result_u = finemap_abf(&d, 1e-4, None).unwrap();
    let result_w = finemap_abf(&d, 1e-4, Some(&uniform_weights)).unwrap();

    for i in 0..n {
        assert!(
            (result_u.snps[i].snp_pp - result_w.snps[i].snp_pp).abs() < 1e-14,
            "uniform weights should match no weights at snp {i}"
        );
    }
}
