//! Publish data packages to a Hugging Face dataset repository.

use std::path::Path;

use async_trait::async_trait;
use hf_hub::repository::CommitOperation;
use hf_hub::{HFClient, HFClientBuilder, HFError, HFRepository, RepoTypeDataset};

use crate::error::Result;
use crate::model::{CATALOG_SCHEMA_VERSION, CatalogEntry, CatalogIndex, DatasetManifest};
use crate::package::{PACKAGE_MANIFEST, PAYLOAD_DIR, validate_package};
use crate::remote::ObjectSource;

const INDEX_PATH: &str = "index.json";
/// Keep batches below Hub's 1000-file commit limit while leaving room for
/// metadata generated by the upload client.
const HF_COMMIT_BATCH_FILES: usize = 900;

/// Resolve a Hugging Face token: explicit value, then `HUGGING_FACE_TOKEN`;
/// `None` defers to the hf-hub defaults (`HF_TOKEN`, `HF_TOKEN_PATH`, or the
/// cached token file).
pub fn resolve_hf_token(explicit: Option<String>) -> Option<String> {
    explicit.or_else(|| {
        std::env::var("HUGGING_FACE_TOKEN")
            .ok()
            .filter(|token| !token.is_empty())
    })
}

/// Where and how to publish a package on the Hugging Face Hub.
#[derive(Debug, Clone)]
pub struct HfPublishTarget {
    /// Repository containing the global `index.json`.
    pub index_repo_id: String,
    /// Branch to commit to; `None` uses the repository main branch.
    pub revision: Option<String>,
    /// Bearer token. `None` falls back to the hf-hub defaults: `HF_TOKEN`,
    /// `HF_TOKEN_PATH`, or the cached token file.
    pub token: Option<String>,
    /// Create the dataset repository first when it does not exist yet.
    pub create_repository: bool,
}

/// Derive a per-package HF repo name (`{prefix}-{sanitized-id}`) from a
/// package prefix in `owner/name` form and a legacy display id.
///
/// Used only by the v2→v3 index migration to recover the repo for entries
/// that were published before the repo field was always populated. New
/// packages set `manifest.repo` directly and never call this.
pub fn package_repo_id(prefix: &str, package_id: &str) -> String {
    let sanitized = package_id
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() {
                c.to_ascii_lowercase()
            } else {
                '-'
            }
        })
        .collect::<String>();
    format!("{prefix}-{}", sanitized.trim_matches('-'))
}

/// Derive the canonical package prefix (`owner/name` without the trailing
/// `-<sanitized-id>` part) from an index repository ID.
///
/// `owner/catalog-index` yields `owner/catalog`. Other index names append
/// `-packages` so package repositories never collide with the index.
pub fn package_repo_prefix_for_index(index_repo_id: &str) -> Result<String> {
    let (owner, name) = split_repo_id(index_repo_id)?;
    let prefix_name = match name.strip_suffix("-index") {
        Some(prefix) => prefix.to_string(),
        None => format!("{name}-packages"),
    };
    Ok(format!("{owner}/{prefix_name}"))
}

/// Object source that routes `owner/repo/path` keys to the correct HF dataset.
///
/// The key format uses the full HF repo ID as the first two path components:
/// `owner/repo-name/path/to/file`.
pub struct MultiRepoHfSource {
    client: HFClient,
    revision: String,
}

impl MultiRepoHfSource {
    pub fn new(_index_repo: &str, revision: Option<String>, token: Option<String>) -> Result<Self> {
        let mut builder = HFClientBuilder::new();
        if let Some(token) = token {
            builder = builder.token(token);
        }
        let client = builder
            .build()
            .map_err(|error| format!("build Hugging Face client: {error}"))?;
        Ok(Self {
            client,
            revision: revision.unwrap_or_else(|| "main".to_string()),
        })
    }

    fn resolve(&self, key: &str) -> Result<(HFRepository<RepoTypeDataset>, String)> {
        let parts: Vec<&str> = key.splitn(3, '/').collect();
        if parts.len() < 3 || parts[0].is_empty() || parts[1].is_empty() {
            return Err(format!("HF multi-repo key must be `owner/repo/path`, got `{key}`").into());
        }
        let repo = self.client.dataset(parts[0], parts[1]);
        Ok((repo, parts[2].to_string()))
    }
}

#[async_trait]
impl ObjectSource for MultiRepoHfSource {
    async fn read(&self, key: &str) -> Result<Vec<u8>> {
        let (repository, path) = self.resolve(key)?;
        let bytes = fetch_retried(&repository, &path, None, &self.revision)
            .await
            .map_err(|error| format!("read Hugging Face object `{key}`: {error}"))?;
        Ok(bytes)
    }

    async fn read_range(&self, key: &str, offset: u64, len: u64) -> Result<Vec<u8>> {
        if len == 0 {
            return Ok(Vec::new());
        }
        let (repository, path) = self.resolve(key)?;
        let bytes = fetch_retried(
            &repository,
            &path,
            Some(offset..offset + len),
            &self.revision,
        )
        .await
        .map_err(|error| format!("read Hugging Face object `{key}` at {offset}: {error}"))?;
        Ok(bytes)
    }
}

/// Outcome of one fetch attempt: deterministic not-found (never retried)
/// or a retryable transport failure, including a request exceeding its
/// total timeout.
enum FetchFailure {
    NotFound,
    Transport(String),
}

impl std::fmt::Display for FetchFailure {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::NotFound => write!(formatter, "entry not found"),
            Self::Transport(reason) => write!(formatter, "{reason}"),
        }
    }
}

/// Fetch one object (optionally a byte range), retrying transient transport
/// failures.
///
/// hf-hub retries only the request handshake — response-body decode errors
/// surface unretried, and the underlying HTTP client has no total timeout,
/// so a stalled-but-open connection hangs forever. Every attempt is
/// therefore bounded by [`FETCH_REQUEST_TIMEOUT`]; a timeout counts as a
/// retryable failure. Large installs and migrations issue hundreds of
/// requests, so a rare per-request hiccup must not abort the whole
/// transfer. Deterministic failures (`EntryNotFound`) return immediately.
async fn fetch_retried(
    repository: &HFRepository<RepoTypeDataset>,
    path: &str,
    range: Option<std::ops::Range<u64>>,
    revision: &str,
) -> std::result::Result<Vec<u8>, FetchFailure> {
    /// Total time one HTTP attempt may take, however slow the stream. A
    /// 64 MiB chunk needs ~360 KiB/s to stay under this — anything slower
    /// is treated as a stall, not throughput.
    const FETCH_REQUEST_TIMEOUT: std::time::Duration = std::time::Duration::from_secs(180);
    const ATTEMPTS: usize = 4;
    /// Rate-limit waits are server-paced and do not burn the retry budget;
    /// cap them per chunk so a persistently limited run fails loudly
    /// instead of looping forever.
    const MAX_RATE_LIMIT_WAITS: usize = 3;
    /// Fallback pause when the Hub rate-limits without a `Retry-After`.
    const RATE_LIMIT_FALLBACK_WAIT: std::time::Duration = std::time::Duration::from_secs(120);
    let mut delay = std::time::Duration::from_millis(400);
    let mut rate_limit_waits = 0;
    let mut last = None;
    let mut attempt = 0;
    while attempt < ATTEMPTS {
        if attempt > 0 {
            tokio::time::sleep(delay).await;
            delay = delay.saturating_mul(2);
        }
        let request = async {
            if let Some(range) = range.clone() {
                repository
                    .download_file_to_bytes()
                    .filename(path)
                    .revision(revision.to_string())
                    .range(range)
                    .send()
                    .await
            } else {
                repository
                    .download_file_to_bytes()
                    .filename(path)
                    .revision(revision.to_string())
                    .send()
                    .await
            }
        };
        let sent = tokio::time::timeout(FETCH_REQUEST_TIMEOUT, request).await;
        let sent = match sent {
            Ok(result) => result,
            Err(_) => {
                last = Some(FetchFailure::Transport(format!(
                    "request timed out after {FETCH_REQUEST_TIMEOUT:?}"
                )));
                attempt += 1;
                continue;
            }
        };
        match sent {
            Ok(bytes) => return Ok(bytes.to_vec()),
            Err(HFError::EntryNotFound { .. }) => {
                return Err(FetchFailure::NotFound);
            }
            Err(HFError::RateLimited {
                retry_after,
                context: _,
            }) => {
                if rate_limit_waits >= MAX_RATE_LIMIT_WAITS {
                    last = Some(FetchFailure::Transport(
                        "rate limited; wait budget exhausted".to_string(),
                    ));
                    attempt += 1;
                    continue;
                }
                // The quota window is minutes long; exponential backoff is
                // useless here. Sleep the server-directed delay without
                // consuming a retry attempt.
                rate_limit_waits += 1;
                let wait = retry_after
                    .filter(|delay| !delay.is_zero())
                    .unwrap_or(RATE_LIMIT_FALLBACK_WAIT)
                    .min(std::time::Duration::from_secs(300));
                tokio::time::sleep(wait).await;
                continue;
            }
            Err(error) => {
                last = Some(FetchFailure::Transport(error.to_string()));
                attempt += 1;
            }
        }
    }
    Err(last.expect("at least one attempt ran"))
}

/// Publish a validated local package to a Hugging Face dataset repository.
///
/// The package is committed to its own dataset repository in a content-addressed
/// `<version>/<digest>` layout. Payload is committed in batches below Hub's
/// 1000-file limit, with the manifest last. The global index repository is
/// updated only after the package repository is complete, so readers observe
/// either the old or the new catalog generation, never a partial upload.
pub async fn publish_package_to_hf(
    package: impl AsRef<Path>,
    target: &HfPublishTarget,
) -> Result<CatalogEntry> {
    let package = package.as_ref();
    let manifest = validate_package(package).map_err(|error| error.to_string())?;
    let entry = build_entry(&manifest);

    let (pkg_owner, pkg_name) = split_repo_id(&entry.repo)?;
    let (index_owner, index_name) = split_repo_id(&target.index_repo_id)?;
    let mut builder = HFClientBuilder::new();
    if let Some(token) = &target.token {
        builder = builder.token(token.clone());
    }
    let client = builder
        .build()
        .map_err(|error| format!("build Hugging Face client: {error}"))?;

    if target.create_repository {
        client
            .create_repository()
            .repo_id(entry.repo.as_str())
            .repo_type(RepoTypeDataset)
            .exist_ok(true)
            .send()
            .await
            .map_err(|error| format!("create package repository `{}`: {error}", entry.repo))?;
        client
            .create_repository()
            .repo_id(target.index_repo_id.as_str())
            .repo_type(RepoTypeDataset)
            .exist_ok(true)
            .send()
            .await
            .map_err(|error| {
                format!(
                    "create Hugging Face index repository `{}`: {error}",
                    target.index_repo_id
                )
            })?;
    }

    // Phase 1: commit payload and finally the manifest to the package repo.
    // Batching is required by Hub's per-commit file limit; the index remains
    // the publication boundary, so partial package commits are never reachable
    // through a valid catalog entry.
    let package_repository = client.dataset(pkg_owner, pkg_name);
    let revision = target
        .revision
        .clone()
        .unwrap_or_else(|| "main".to_string());
    let operations = package_commit_operations(package, &entry, &manifest);
    let batch_count = operations.len().div_ceil(HF_COMMIT_BATCH_FILES);
    for (batch_index, batch) in operations.chunks(HF_COMMIT_BATCH_FILES).enumerate() {
        package_repository
            .create_commit()
            .operations(batch.to_vec())
            .commit_message(format!(
                "Publish {}@{} ({}/{})",
                entry.repo,
                entry.version,
                batch_index + 1,
                batch_count
            ))
            .revision(revision.clone())
            .send()
            .await
            .map_err(|error| {
                format!(
                    "publish package `{}` to `{}` batch {}/{}: {error}",
                    entry.repo,
                    entry.repo,
                    batch_index + 1,
                    batch_count
                )
            })?;
    }

    // Phase 2: update the package-local index, then the thin registry.
    let index_repository = client.dataset(index_owner, index_name);
    let package_index = read_remote_index(&package_repository, target.revision.as_deref()).await?;
    let package_index = upsert_entry(package_index, &entry)?;
    let package_index_bytes =
        serde_json::to_vec_pretty(&package_index).map_err(|error| error.to_string())?;
    package_repository
        .create_commit()
        .operations(vec![CommitOperation::add_bytes(
            INDEX_PATH,
            package_index_bytes,
        )])
        .commit_message(format!("Index {}@{}", entry.repo, entry.version))
        .revision(revision.clone())
        .send()
        .await
        .map_err(|error| format!("update package index in `{}`: {error}", entry.repo))?;

    let mut registry = read_remote_index(&index_repository, target.revision.as_deref()).await?;
    registry.schema_version = CATALOG_SCHEMA_VERSION;
    let legacy_repositories = registry
        .entries
        .iter()
        .filter(|entry| !entry.repo.is_empty())
        .map(|entry| entry.repo.clone())
        .collect::<Vec<_>>();
    for repository in legacy_repositories {
        registry.record_repository(&repository);
    }
    registry.entries.clear();
    registry.record_repository(&entry.repo);
    registry.generation = registry.generation.saturating_add(1);
    let registry_bytes = serde_json::to_vec_pretty(&registry).map_err(|error| error.to_string())?;
    index_repository
        .create_commit()
        .operations(vec![CommitOperation::add_bytes(INDEX_PATH, registry_bytes)])
        .commit_message(format!("Register {}", entry.repo))
        .revision(revision)
        .send()
        .await
        .map_err(|error| {
            format!(
                "publish index to Hugging Face repository `{}`: {error}",
                target.index_repo_id
            )
        })?;
    Ok(entry)
}

fn build_entry(manifest: &DatasetManifest) -> CatalogEntry {
    CatalogEntry {
        repo: manifest.repo.clone(),
        version: manifest.version.clone(),
        kind: manifest.kind.clone(),
        digest: manifest
            .digest
            .clone()
            .expect("validated manifests have a digest"),
        current: true,
        created_unix_seconds: std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|duration| duration.as_secs() as i64)
            .unwrap_or_default(),
    }
}

fn upsert_entry(mut index: CatalogIndex, entry: &CatalogEntry) -> Result<CatalogIndex> {
    index.upsert_current(entry.clone());
    index.validate()?;
    Ok(index)
}

fn split_repo_id(repo_id: &str) -> Result<(&str, &str)> {
    let (owner, name) = repo_id.split_once('/').ok_or_else(|| {
        format!("Hugging Face repository id must be `owner/name`, got `{repo_id}`")
    })?;
    if owner.is_empty() || name.is_empty() || name.contains('/') {
        return Err(
            format!("Hugging Face repository id must be `owner/name`, got `{repo_id}`").into(),
        );
    }
    Ok((owner, name))
}

async fn read_remote_index(
    repository: &HFRepository<RepoTypeDataset>,
    revision: Option<&str>,
) -> Result<CatalogIndex> {
    let revision = revision.unwrap_or("main");
    let request = repository
        .download_file_to_bytes()
        .filename(INDEX_PATH)
        .revision(revision.to_string());
    match request.send().await {
        Ok(bytes) => {
            let index: CatalogIndex = serde_json::from_slice(&bytes).map_err(|error| {
                format!("parse Hugging Face catalog index `{INDEX_PATH}`: {error}")
            })?;
            index.validate().map_err(|error| {
                format!("invalid Hugging Face catalog index `{INDEX_PATH}`: {error}")
            })?;
            Ok(index)
        }
        Err(HFError::EntryNotFound { .. }) => Ok(CatalogIndex::default()),
        Err(error) => {
            Err(format!("read Hugging Face catalog index `{INDEX_PATH}`: {error}").into())
        }
    }
}

fn package_commit_operations(
    package: &Path,
    entry: &CatalogEntry,
    manifest: &DatasetManifest,
) -> Vec<CommitOperation> {
    let mut operations = Vec::with_capacity(manifest.files.len() + 1);
    for file in &manifest.files {
        operations.push(CommitOperation::add_file(
            format!("{}/{}", entry.package_payload_prefix(), file.path),
            package.join(PAYLOAD_DIR).join(&file.path),
        ));
    }
    operations.push(CommitOperation::add_file(
        entry.package_manifest_key(),
        package.join(PACKAGE_MANIFEST),
    ));
    operations
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::package::{BuildOptions, build_package};
    use crate::remote::RemoteCatalog;
    use hf_hub::repository::AddSource;

    #[test]
    fn split_repo_id_requires_owner_and_name() {
        assert_eq!(
            split_repo_id("wjx/autonomics-catalog").unwrap(),
            ("wjx", "autonomics-catalog")
        );
        assert!(split_repo_id("catalog").is_err());
        assert!(split_repo_id("/catalog").is_err());
        assert!(split_repo_id("wjx/").is_err());
        assert!(split_repo_id("a/b/c").is_err());
    }

    #[test]
    fn package_repo_ids_are_valid_hf_names() {
        assert_eq!(
            package_repo_id("wjixiang/catalog", "hdl.ref.ukb_eur"),
            "wjixiang/catalog-hdl-ref-ukb-eur"
        );
        assert_eq!(
            package_repo_id("wjixiang/catalog", "_leading_and_trailing_"),
            "wjixiang/catalog-leading-and-trailing"
        );
    }

    #[test]
    fn package_prefix_is_derived_from_index_repo() {
        assert_eq!(
            package_repo_prefix_for_index("wjixiang/catalog-index").unwrap(),
            "wjixiang/catalog"
        );
        assert_eq!(
            package_repo_prefix_for_index("wjixiang/warehouse").unwrap(),
            "wjixiang/warehouse-packages"
        );
    }

    #[test]
    fn remote_catalog_hf_construction_is_lazy() {
        assert!(RemoteCatalog::hf("owner/catalog", None, None).is_ok());
    }

    #[test]
    fn commit_operations_mirror_catalog_layout() {
        let workspace = tempfile::tempdir().unwrap();
        let input = workspace.path().join("input");
        std::fs::create_dir_all(&input).unwrap();
        std::fs::write(input.join("data.txt"), b"hf-payload").unwrap();
        let package = build_package(
            &input,
            workspace.path().join("package"),
            BuildOptions {
                repo: Some("owner/catalog-panel".into()),
                version: Some("v1".into()),
                kind: Some("panel".into()),
                ..Default::default()
            },
        )
        .unwrap();
        let manifest = validate_package(&package.path).unwrap();
        let entry = build_entry(&manifest);
        let index = upsert_entry(CatalogIndex::default(), &entry).unwrap();
        let _index_bytes = serde_json::to_vec_pretty(&index).unwrap();

        let operations = package_commit_operations(&package.path, &entry, &manifest);
        assert_eq!(operations.len(), 2);

        match operations.last().unwrap() {
            CommitOperation::Add {
                path_in_repo,
                source: AddSource::File(source),
            } => {
                assert_eq!(path_in_repo, &entry.package_manifest_key());
                assert_eq!(source, &package.path.join(PACKAGE_MANIFEST));
            }
            other => panic!("expected manifest add, got {other:?}"),
        }
        match operations.first().unwrap() {
            CommitOperation::Add {
                path_in_repo,
                source: AddSource::File(source),
            } => {
                assert_eq!(
                    path_in_repo,
                    &format!("{}/data.txt", entry.package_payload_prefix())
                );
                assert_eq!(source, &package.path.join(PAYLOAD_DIR).join("data.txt"));
            }
            other => panic!("expected payload add, got {other:?}"),
        }
    }
}
