//! R golden test for `statkit::regression::reduced_rank_regression`.
//!
//! Golden files are generated by `tests/golden/gen_rrr_reference.R` (base R
//! `lm` + `svd`, self-checked) — there is no canonical R package for RRR, so
//! the reference implements the same estimator with base primitives.
//!
//! Run: `Rscript stat_crates/statkit/tests/golden/gen_rrr_reference.R` then
//! `cargo test -p statkit --test rrr_r_reference`

use statkit::regression::reduced_rank_regression;

fn read_csv(path: &str) -> Vec<(String, Vec<f64>)> {
    let text = std::fs::read_to_string(path)
        .unwrap_or_else(|_| panic!("{path} not found — run gen_rrr_reference.R first"));
    let mut cols: Vec<(String, Vec<f64>)> = Vec::new();
    let mut lines = text.lines();
    let header: Vec<String> = lines
        .next()
        .unwrap()
        .split(',')
        .map(|h| h.trim_matches('"').to_string())
        .collect();
    for h in &header {
        cols.push((h.clone(), Vec::new()));
    }
    for line in lines {
        for (col, f) in cols.iter_mut().zip(line.split(',')) {
            col.1.push(f.parse::<f64>().unwrap());
        }
    }
    cols
}

fn col<'a>(cols: &'a [(String, Vec<f64>)], name: &str) -> &'a [f64] {
    &cols
        .iter()
        .find(|(h, _)| h == name)
        .unwrap_or_else(|| panic!("column {name} missing"))
        .1
}

const TOL: f64 = 1e-9;

#[test]
fn reduced_rank_regression_matches_r() {
    let base = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/golden/");
    let cols = read_csv(&format!("{}rrr_data.csv", base));
    let ref_text = std::fs::read_to_string(format!("{}rrr_reference.json", base))
        .expect("rrr_reference.json missing — run gen_rrr_reference.R");
    let r: serde_json::Value = serde_json::from_str(&ref_text).unwrap();

    let x: Vec<&[f64]> = vec![col(&cols, "x1"), col(&cols, "x2"), col(&cols, "x3")];
    let y: Vec<&[f64]> = vec![col(&cols, "y1"), col(&cols, "y2"), col(&cols, "y3")];

    let close = |a: f64, b: f64, what: &str| {
        assert!((a - b).abs() <= TOL, "{what}: rust {a} vs R {b}");
    };

    for (key, k) in [("k1", 1usize), ("k2", 2), ("k3", 3)] {
        let g = &r["ranks"][key];
        let res = reduced_rank_regression(&x, &y, None, Some(k)).unwrap();
        assert_eq!(res.rank, k, "rank for {key}");

        // Intercepts (length r).
        for (j, gv) in g["intercept"].as_array().unwrap().iter().enumerate() {
            close(
                res.intercept[j],
                gv.as_f64().unwrap(),
                &format!("{key} intercept[{j}]"),
            );
        }
        // Slopes flattened row-major by predictor (R: t(slopes) column-major).
        let slopes = g["slopes"].as_array().unwrap();
        for (i, row) in res.coefficients.iter().enumerate() {
            for (j, &v) in row.iter().enumerate() {
                close(
                    v,
                    slopes[i * y.len() + j].as_f64().unwrap(),
                    &format!("{key} slopes[{i}][{j}]"),
                );
            }
        }
        // Singular values, variance explained, cumulative, per-response R².
        for (j, gv) in g["d"].as_array().unwrap().iter().enumerate() {
            close(
                res.singular_values[j],
                gv.as_f64().unwrap(),
                &format!("{key} d[{j}]"),
            );
        }
        for (j, gv) in g["ve"].as_array().unwrap().iter().enumerate() {
            close(
                res.variance_explained[j],
                gv.as_f64().unwrap(),
                &format!("{key} ve[{j}]"),
            );
        }
        for (j, gv) in g["cum"].as_array().unwrap().iter().enumerate() {
            close(
                res.cumulative[j],
                gv.as_f64().unwrap(),
                &format!("{key} cum[{j}]"),
            );
        }
        for (j, gv) in g["r2"].as_array().unwrap().iter().enumerate() {
            close(
                res.r_squared_per_response[j],
                gv.as_f64().unwrap(),
                &format!("{key} r2[{j}]"),
            );
        }
    }
}
