//! Cross-validation of the Rust LCV port against R golden outputs.
//!
//! The golden fixtures are generated by `tests/fixtures/gen/gen_golden.R`, which
//! sources the upstream R reference (`reference/LCV/R/`), simulates summary
//! statistics under the LCV model with a fixed seed, and runs R's `RunLCV`.
//!
//! Both scenarios use `ell = 1` (no LD) with fixed LDSC intercepts
//! (`ldsc.intercept = 0`, `crosstrait.intercept = 0`), exercising the full
//! pipeline: jackknife → mixed-4th-moments → gcp grid → posterior → p-values.
//!
//! LCV is fully deterministic, so comparisons are exact value-by-value.
//!
//! Regenerate fixtures (from repo root):
//!   Rscript bio_crates/lcv/tests/fixtures/gen/gen_golden.R

use std::path::Path;

use lcv::model::run_lcv;
use lcv::moments::K4Config;
use serde_json::Value;

const FIXTURES: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures");

/// Read a header-keyed TSV: `ell\tz1\tz2\tw`.
fn read_input(path: &Path) -> (Vec<f64>, Vec<f64>, Vec<f64>, Vec<f64>) {
    let s = std::fs::read_to_string(path).unwrap();
    let mut lines = s.lines();
    let _header = lines.next(); // skip header

    let mut ell = Vec::new();
    let mut z1 = Vec::new();
    let mut z2 = Vec::new();
    let mut w = Vec::new();
    for line in lines {
        let cols: Vec<&str> = line.split('\t').collect();
        if cols.len() < 4 {
            continue;
        }
        ell.push(cols[0].parse().unwrap());
        z1.push(cols[1].parse().unwrap());
        z2.push(cols[2].parse().unwrap());
        w.push(cols[3].parse().unwrap());
    }
    (ell, z1, z2, w)
}

/// Read golden JSON result.
fn read_result(path: &Path) -> Value {
    let s = std::fs::read_to_string(path).unwrap();
    serde_json::from_str(&s).unwrap()
}

fn close(a: f64, b: f64, rel: f64, abs: f64) -> bool {
    if a.is_nan() && b.is_nan() {
        return true;
    }
    if a.is_nan() || b.is_nan() {
        return false;
    }
    (a - b).abs() <= rel * b.abs().max(1e-12) + abs
}

/// Run Rust LCV on a scenario fixture and compare to R golden.
fn check_scenario(tag: &str, n1: f64, n2: f64) {
    let input_path = Path::new(FIXTURES).join(format!("scenario{tag}.tsv"));
    let result_path = Path::new(FIXTURES).join(format!("scenario{tag}_result.json"));

    let (ell, z1, z2, w) = read_input(&input_path);
    let golden = read_result(&result_path);

    let cfg = K4Config {
        crosstrait_intercept: false,
        ldsc_intercept: false,
        sig_threshold: f64::INFINITY,
        n1,
        n2,
        intercept12: 0.0,
    };

    let out = run_lcv(&ell, &z1, &z2, &w, 100, &cfg).expect("LCV should succeed");

    // Tolerances: the LCV estimator is fully deterministic; tiny differences
    // come only from float-order-of-operations in the weighted mean / wls.
    let rel = 1e-4;
    let abs = 1e-6;

    macro_rules! gget {
        ($field:expr) => {
            golden[$field].as_f64().unwrap()
        };
    }

    assert!(
        close(out.zscore, gget!("zscore"), rel, abs),
        "[{tag}] zscore: rust={:.6} r={:.6}",
        out.zscore,
        gget!("zscore")
    );
    assert!(
        close(out.gcp_pm, gget!("gcp_pm"), rel, abs),
        "[{tag}] gcp_pm: rust={:.6} r={:.6}",
        out.gcp_pm,
        gget!("gcp_pm")
    );
    assert!(
        close(out.gcp_pse, gget!("gcp_pse"), rel, abs),
        "[{tag}] gcp_pse: rust={:.6} r={:.6}",
        out.gcp_pse,
        gget!("gcp_pse")
    );
    assert!(
        close(out.rho_est, gget!("rho_est"), rel, abs),
        "[{tag}] rho_est: rust={:.6} r={:.6}",
        out.rho_est,
        gget!("rho_est")
    );
    assert!(
        close(out.rho_err, gget!("rho_err"), rel, abs),
        "[{tag}] rho_err: rust={:.6} r={:.6}",
        out.rho_err,
        gget!("rho_err")
    );
    assert!(
        close(
            out.pval_gcpzero_2tailed,
            gget!("pval_gcpzero_2tailed"),
            rel,
            abs
        ),
        "[{tag}] pval_gcpzero: rust={:.4e} r={:.4e}",
        out.pval_gcpzero_2tailed,
        gget!("pval_gcpzero_2tailed")
    );
    assert!(
        close(out.pval_fullycausal[0], gget!("pval_fullycausal_1"), rel, abs),
        "[{tag}] pval_fullycausal_1: rust={:.4e} r={:.4e}",
        out.pval_fullycausal[0],
        gget!("pval_fullycausal_1")
    );
    assert!(
        close(out.pval_fullycausal[1], gget!("pval_fullycausal_2"), rel, abs),
        "[{tag}] pval_fullycausal_2: rust={:.4e} r={:.4e}",
        out.pval_fullycausal[1],
        gget!("pval_fullycausal_2")
    );
    assert!(
        close(out.h2_zscore[0], gget!("h2_zscore_1"), rel, abs),
        "[{tag}] h2_zscore_1: rust={:.4} r={:.4}",
        out.h2_zscore[0],
        gget!("h2_zscore_1")
    );
    assert!(
        close(out.h2_zscore[1], gget!("h2_zscore_2"), rel, abs),
        "[{tag}] h2_zscore_2: rust={:.4} r={:.4}",
        out.h2_zscore[1],
        gget!("h2_zscore_2")
    );

    println!(
        "[{tag}] ✅ all fields match R golden (gcp_pm={:.4}, z={:.2}, rho={:.4})",
        out.gcp_pm, out.zscore, out.rho_est
    );
}

#[test]
fn scenario_a_strong_causality() {
    // q1=1.0, q2=0.2 → gcp > 0 (trait1 → trait2)
    check_scenario("A", 20000.0, 50000.0);
}

#[test]
fn scenario_b_reversed() {
    // q1=0.2, q2=1.0 → gcp < 0 (trait2 → trait1)
    check_scenario("B", 20000.0, 50000.0);
}
