//! Golden cross-validation: rdmulti Rust vs R.
//!
//! Generated by `Rscript tests/gen_golden.R` using R rdmulti 2.0.0
//! on synthetic multi-cutoff data (seed=42, n=1000, cutoffs at 33 and 66).

use std::io::BufReader;
use rdmulti::{rdmc, RdMcConfig};
use rdrobust::Kernel;

fn load_mc_data() -> (Vec<f64>, Vec<f64>, Vec<f64>) {
    let path = "tests/synthetic_mc.csv";
    let file = std::fs::File::open(path).unwrap_or_else(|e| panic!("Cannot open {path}: {e}"));
    let mut rdr = csv::ReaderBuilder::new().from_reader(BufReader::new(file));
    let mut y = Vec::new();
    let mut x = Vec::new();
    let mut c = Vec::new();
    for result in rdr.records() {
        let record = result.unwrap();
        y.push(record.get(0).unwrap().parse::<f64>().unwrap());
        x.push(record.get(1).unwrap().parse::<f64>().unwrap());
        c.push(record.get(2).unwrap().parse::<f64>().unwrap());
    }
    (y, x, c)
}

fn rel_err(a: f64, b: f64) -> f64 {
    if a.abs() < 1e-30 && b.abs() < 1e-30 { return 0.0; }
    (a - b).abs() / a.abs().max(b.abs())
}

#[test]
fn xval_rdmc_pooled() {
    let (y, x, c) = load_mc_data();
    let result = rdmc(&RdMcConfig {
        y, x, c,
        p: 1,
        kernel: Kernel::Triangular,
        bwselect: "mserd".into(),
        vce: "nn".into(),
        level: 95.0,
    }).unwrap();

    // R reference values
    let r_pooled_tau_cl = 0.1431900473896377;
    let r_pooled_se_rb = 0.3806628013308932;

    let tol = 1e-4;
    assert!(rel_err(result.pooled.tau_cl, r_pooled_tau_cl) < tol,
        "pooled tau_cl: Rust={:.10e} vs R={:.10e}", result.pooled.tau_cl, r_pooled_tau_cl);
    assert!(rel_err(result.pooled.se_rb, r_pooled_se_rb) < tol,
        "pooled se_rb: Rust={:.10e} vs R={:.10e}", result.pooled.se_rb, r_pooled_se_rb);
}

#[test]
fn xval_rdmc_cutoffs() {
    let (y, x, c) = load_mc_data();
    let result = rdmc(&RdMcConfig {
        y, x, c,
        p: 1,
        kernel: Kernel::Triangular,
        bwselect: "mserd".into(),
        vce: "nn".into(),
        level: 95.0,
    }).unwrap();

    assert_eq!(result.cutoffs.len(), 2, "expected 2 cutoffs");

    // R reference: cutoff 1 (at 33)
    let r_c1_tau_cl = 0.08197305957369849;
    let r_c1_tau_bc = 0.02217039654233588;
    // R reference: cutoff 2 (at 66)
    let r_c2_tau_cl = 0.6791095479974842;
    let r_c2_tau_bc = 0.5830994498130101;

    let tol = 1e-4;
    let c1 = &result.cutoffs[0];
    let c2 = &result.cutoffs[1];

    assert!(rel_err(c1.tau_cl, r_c1_tau_cl) < tol,
        "cutoff1 tau_cl: Rust={:.10e} vs R={:.10e}", c1.tau_cl, r_c1_tau_cl);
    assert!(rel_err(c1.tau_bc, r_c1_tau_bc) < tol,
        "cutoff1 tau_bc: Rust={:.10e} vs R={:.10e}", c1.tau_bc, r_c1_tau_bc);
    assert!(rel_err(c2.tau_cl, r_c2_tau_cl) < tol,
        "cutoff2 tau_cl: Rust={:.10e} vs R={:.10e}", c2.tau_cl, r_c2_tau_cl);
    assert!(rel_err(c2.tau_bc, r_c2_tau_bc) < tol,
        "cutoff2 tau_bc: Rust={:.10e} vs R={:.10e}", c2.tau_bc, r_c2_tau_bc);
}

#[test]
fn xval_rdmc_sample_sizes() {
    let (y, x, c) = load_mc_data();
    let result = rdmc(&RdMcConfig {
        y, x, c,
        p: 1,
        kernel: Kernel::Triangular,
        ..Default::default()
    }).unwrap();

    // R reference: n_h = 91 for cutoff 1, 112 for cutoff 2
    assert_eq!(result.cutoffs[0].n_h_l + result.cutoffs[0].n_h_r, 91,
        "cutoff1 n_h: got {}", result.cutoffs[0].n_h_l + result.cutoffs[0].n_h_r);
    assert_eq!(result.cutoffs[1].n_h_l + result.cutoffs[1].n_h_r, 112,
        "cutoff2 n_h: got {}", result.cutoffs[1].n_h_l + result.cutoffs[1].n_h_r);
}
