//! Multiclass metrics vs base-R golden.
//!
//! Golden files are generated by `tests/reference/gen_metrics_reference.R`
//! (run it from the repo root).
//!
//! Run: `cargo test -p ml --test metrics_r_reference`

use serde_json::Value;

const TOL_AUC: f64 = 1e-6;
const TOL_STRICT: f64 = 1e-10;
const TOL_BIN: f64 = 1e-9;

struct Data {
    y: Vec<usize>,
    probs: Vec<Vec<f64>>,
}

fn load_data() -> Data {
    let csv = std::fs::read_to_string(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/reference/metrics_data.csv"
    ))
    .expect("metrics_data.csv not found — run gen_metrics_reference.R first");
    let mut y = Vec::new();
    let mut probs = Vec::new();
    for (i, line) in csv.lines().enumerate() {
        if i == 0 || line.trim().is_empty() {
            continue;
        }
        let cols: Vec<&str> = line.split(',').collect();
        y.push(cols[0].trim().parse().unwrap());
        probs.push(vec![
            cols[1].trim().parse().unwrap(),
            cols[2].trim().parse().unwrap(),
            cols[3].trim().parse().unwrap(),
        ]);
    }
    Data { y, probs }
}

fn load_ref() -> Value {
    let json = std::fs::read_to_string(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/reference/metrics_reference.json"
    ))
    .expect("metrics_reference.json not found — run gen_metrics_reference.R first");
    serde_json::from_str(&json).unwrap()
}

fn f64s(v: &Value, key: &str) -> Vec<f64> {
    v[key]
        .as_array()
        .unwrap()
        .iter()
        .map(|x| x.as_f64().unwrap())
        .collect()
}

fn close(a: f64, b: f64, tol: f64, what: &str) {
    assert!(
        (a - b).abs() <= tol,
        "{what}: rust {a} vs R {b} (|diff| {} > {tol})",
        (a - b).abs()
    );
}

fn argmax(row: &[f64]) -> usize {
    let mut best = 0;
    let mut best_v = f64::NEG_INFINITY;
    for (j, &v) in row.iter().enumerate() {
        if v > best_v {
            best_v = v;
            best = j;
        }
    }
    best
}

#[test]
fn auc_matches_r() {
    let d = load_data();
    let r = load_ref();
    let aucs = ml::metrics::ovr_auc(&d.y, &d.probs, 3).unwrap();
    let ref_auc = f64s(&r, "auc");
    for c in 0..3 {
        close(aucs[c], ref_auc[c], TOL_AUC, &format!("auc[{c}]"));
    }
    close(
        ml::metrics::macro_ovr_auc(&d.y, &d.probs, 3).unwrap(),
        r["macro_auc"].as_f64().unwrap(),
        TOL_AUC,
        "macro_auc",
    );
}

#[test]
fn accuracy_balanced_brier_logloss_match_r() {
    let d = load_data();
    let r = load_ref();
    let y_f: Vec<f64> = d.y.iter().map(|&v| v as f64).collect();
    let y_pred_f: Vec<f64> = d.probs.iter().map(|p| argmax(p) as f64).collect();

    close(
        ml::metrics::accuracy(&y_f, &y_pred_f).unwrap(),
        r["accuracy"].as_f64().unwrap(),
        TOL_STRICT,
        "accuracy",
    );
    let cm = ml::metrics::confusion_matrix(&y_f, &y_pred_f, 3).unwrap();
    close(
        ml::metrics::balanced_accuracy(&cm, 3).unwrap(),
        r["balanced_accuracy"].as_f64().unwrap(),
        TOL_STRICT,
        "balanced_accuracy",
    );
    close(
        ml::metrics::multiclass_brier(&d.y, &d.probs, 3).unwrap(),
        r["brier"].as_f64().unwrap(),
        TOL_STRICT,
        "brier",
    );
    close(
        ml::metrics::multiclass_log_loss(&d.y, &d.probs, 3).unwrap(),
        r["log_loss"].as_f64().unwrap(),
        TOL_STRICT,
        "log_loss",
    );
    let (m_p, m_r, m_f) = ml::metrics::macro_precision_recall_f1(&y_f, &y_pred_f, 3).unwrap();
    let rp = f64s(&r, "precision");
    let rr = f64s(&r, "recall");
    let rf = f64s(&r, "f1");
    close(
        m_p,
        rp.iter().sum::<f64>() / 3.0,
        TOL_STRICT,
        "macro_precision",
    );
    close(
        m_r,
        rr.iter().sum::<f64>() / 3.0,
        TOL_STRICT,
        "macro_recall",
    );
    close(m_f, rf.iter().sum::<f64>() / 3.0, TOL_STRICT, "macro_f1");
}

#[test]
fn calibration_bins_class0_match_r() {
    let d = load_data();
    let r = load_ref();
    let y_bin: Vec<bool> = d.y.iter().map(|&v| v == 0).collect();
    let p0: Vec<f64> = d.probs.iter().map(|row| row[0]).collect();
    let curve = ml::metrics::class_calibration(&y_bin, &p0, 10).unwrap();
    let bins = f64s(&r, "cal0_bins");
    let ns = f64s(&r, "cal0_n");
    let means = f64s(&r, "cal0_mean_pred");
    let rates = f64s(&r, "cal0_obs_rate");
    assert_eq!(curve.bins.len(), bins.len(), "non-empty bin count");
    for (i, b) in curve.bins.iter().enumerate() {
        assert_eq!(b.bin_index, bins[i] as usize, "bin[{i}] index");
        assert_eq!(b.n, ns[i] as usize, "bin[{i}] n");
        close(
            b.mean_pred,
            means[i],
            TOL_BIN,
            &format!("bin[{i}] mean_pred"),
        );
        close(b.obs_rate, rates[i], TOL_BIN, &format!("bin[{i}] obs_rate"));
    }
}
