//! Multinomial elastic-net vs glmnet golden.
//!
//! Golden files are generated by `tests/golden/gen_mnet_reference.R`
//! (run it from the repo root).  The λ grid and the CV fold ids are
//! shared bit-for-bit through the CSV/JSON, so no RNG alignment.
//!
//! The multinomial objective has flat valleys: two glmnet runs on
//! equivalent parameterisations drift ~2e-2 in coefficients at equal
//! objective value, so coefficients are NOT compared at 1e-3.  The
//! identified quantities are: the λ grid and λ_max (exact formulas),
//! support sets, the objective value, probabilities (~3e-4 observed),
//! and the CV deviance curve (≤ 1e-2 by design).
//!
//! Run: `cargo test -p ml --test mnet_r_reference`

use faer::Mat;
use ml::multinomial::{ClassWeight, LambdaSelect, MnetConfig, mnet_fit, mnet_predict};
use serde_json::Value;

const TOL_GRID: f64 = 1e-10; // λ_max formula (probe: exact to 1e-15)
const TOL_PATH: f64 = 1e-9; // log-spaced grid reconstruction
const TOL_PROB: f64 = 2e-3; // probabilities at fixed λ (probe: ~3e-4)
const TOL_OBJ: f64 = 1e-5; // objective value at fixed λ
const TOL_CV: f64 = 1e-2; // CV deviance curve (design target)

struct Data {
    x_train: Vec<Vec<f64>>,
    y_train: Vec<usize>,
    fold_train: Vec<usize>,
    x_test: Vec<Vec<f64>>,
}

fn load_data() -> Data {
    let csv = std::fs::read_to_string(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/golden/mnet_data.csv"
    ))
    .expect("mnet_data.csv not found — run gen_mnet_reference.R first");
    let mut tr_x = Vec::new();
    let mut tr_y = Vec::new();
    let mut tr_f = Vec::new();
    let mut te_x = Vec::new();
    for (i, line) in csv.lines().enumerate() {
        if i == 0 || line.trim().is_empty() {
            continue;
        }
        let cols: Vec<&str> = line.split(',').collect();
        let y: usize = cols[1].trim().parse().unwrap();
        let row: Vec<f64> = cols[3..]
            .iter()
            .map(|v| v.trim().parse().unwrap())
            .collect();
        // write.csv quotes string columns; test rows carry fold = NA
        if cols[0].trim().trim_matches('"') == "train" {
            tr_y.push(y);
            tr_f.push(cols[2].trim().parse::<usize>().unwrap());
            tr_x.push(row);
        } else {
            te_x.push(row);
        }
    }
    Data {
        x_train: tr_x,
        y_train: tr_y,
        fold_train: tr_f,
        x_test: te_x,
    }
}

fn load_ref() -> Value {
    let json = std::fs::read_to_string(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/golden/mnet_reference.json"
    ))
    .expect("mnet_reference.json not found — run gen_mnet_reference.R first");
    serde_json::from_str(&json).unwrap()
}

fn mat(rows: &[Vec<f64>]) -> Mat<f64> {
    Mat::from_fn(rows.len(), rows[0].len(), |i, j| rows[i][j])
}

fn f64s(v: &Value, key: &str) -> Vec<f64> {
    v[key]
        .as_array()
        .unwrap()
        .iter()
        .map(|x| x.as_f64().unwrap())
        .collect()
}

/// Precision-tiered solver configs: the grid test only reads formula
/// output, the CV curve has 1e-2 headroom, the fixed-λ fit needs real
/// precision.
fn cfg(grid: Option<Vec<f64>>, n_lambda: usize, max_iter: usize, tol: f64) -> MnetConfig {
    MnetConfig {
        alpha: 1.0,
        n_lambda,
        min_ratio: Some(0.01),
        lambda_grid: grid,
        max_iter,
        tol,
        class_weight: ClassWeight::None,
    }
}

/// z-scale objective of a (back-transformed) model, matching the value the
/// R script computes at glmnet's solution.
fn zscale_objective(
    model: &ml::multinomial::MultinomialEnetModel,
    x: &Mat<f64>,
    y: &[usize],
    lam: f64,
    alpha: f64,
) -> f64 {
    let n = x.nrows();
    let p = x.ncols();
    let k = model.class_labels.len();
    // forward-transform to the training z scale
    let w_z: Vec<Vec<f64>> = (0..k)
        .map(|c| {
            (0..p)
                .map(|j| model.weights[c][j] * model.x_sd[j])
                .collect()
        })
        .collect();
    let b_z: Vec<f64> = (0..k)
        .map(|c| {
            model.intercept[c]
                + (0..p)
                    .map(|j| model.weights[c][j] * model.x_mean[j])
                    .sum::<f64>()
        })
        .collect();
    let mut nll = 0.0;
    for i in 0..n {
        let mut row = vec![0.0; k];
        for c in 0..k {
            let mut s = b_z[c];
            for j in 0..p {
                s += w_z[c][j] * (x[(i, j)] - model.x_mean[j]) / model.x_sd[j];
            }
            row[c] = s;
        }
        let mx = row.iter().copied().fold(f64::NEG_INFINITY, f64::max);
        let lse: f64 = row.iter().map(|&v| (v - mx).exp()).sum::<f64>().ln();
        nll += lse + mx - row[y[i]];
    }
    nll / n as f64
        + lam * alpha * w_z.iter().flatten().map(|v| v.abs()).sum::<f64>()
        + 0.5 * lam * (1.0 - alpha) * w_z.iter().flatten().map(|v| v * v).sum::<f64>()
}

#[test]
fn lambda_max_and_default_grid_match_glmnet() {
    let d = load_data();
    let r = load_ref();
    let x = mat(&d.x_train);
    let labels: Vec<String> = (0..3).map(|c| format!("class_{c}")).collect();
    let feats: Vec<String> = (0..x.ncols()).map(|j| format!("f{j}")).collect();
    // default-path fit (no explicit grid) exercises λ_max + log-spacing;
    // the grid is formula output, so a loose solve is plenty
    let (_, curve, _) = mnet_fit(
        &x,
        &d.y_train,
        &labels,
        &feats,
        &cfg(None, 25, 500, 1e-5),
        None,
        LambdaSelect::Min,
    )
    .unwrap();
    let want_max = r["lambda_max"].as_f64().unwrap();
    assert!(
        (curve.lambda[0] - want_max).abs() <= TOL_GRID,
        "lambda_max: {} vs glmnet {}",
        curve.lambda[0],
        want_max
    );
    let want_grid = f64s(&r, "lambda_grid");
    assert_eq!(curve.lambda.len(), want_grid.len());
    for (i, (a, b)) in curve.lambda.iter().zip(&want_grid).enumerate() {
        assert!(
            (a - b).abs() <= TOL_PATH * b.abs().max(1e-12),
            "grid[{i}]: {a} vs {b}"
        );
    }
}

#[test]
fn fixed_lambda_support_objective_probabilities_match_glmnet() {
    let d = load_data();
    let r = load_ref();
    let x = mat(&d.x_train);
    let labels: Vec<String> = (0..3).map(|c| format!("class_{c}")).collect();
    let feats: Vec<String> = (0..x.ncols()).map(|j| format!("f{j}")).collect();
    let grid = f64s(&r, "lambda_grid");
    let i_fix = r["i_fix"].as_u64().unwrap() as usize;
    let lam_fix = grid[i_fix];

    // two-point grid pins the no-CV selection to grid[0] = lam_fix
    let cfg = cfg(Some(vec![lam_fix, lam_fix * 0.999]), 2, 50000, 1e-9);
    let (model, _curve, coefs) = mnet_fit(
        &x,
        &d.y_train,
        &labels,
        &feats,
        &cfg,
        None,
        LambdaSelect::Min,
    )
    .unwrap();
    assert!((model.lambda_selected - lam_fix).abs() < 1e-14);

    // support set: features nonzero in any class, exactly glmnet's
    let got: std::collections::BTreeSet<usize> = coefs.iter().map(|e| e.feature_index).collect();
    let want: std::collections::BTreeSet<usize> = r["support_fix"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_u64().unwrap() as usize)
        .collect();
    assert_eq!(got, want, "support set at fixed lambda");

    // objective on the z scale, same quantity the R script computes at
    // glmnet's solution
    let obj = zscale_objective(&model, &x, &d.y_train, lam_fix, 1.0);
    let obj_ref = r["obj_fix"].as_f64().unwrap();
    // one-sided: a tighter solver lands LOWER on the same convex
    // objective (ours beat glmnet by 3e-5 during calibration); a wildly
    // lower value would mean we solved a different problem
    assert!(
        obj <= obj_ref + TOL_OBJ,
        "objective above glmnet's: rust {obj} vs {obj_ref}"
    );
    assert!(
        obj >= obj_ref - 1e-3,
        "objective implausibly below glmnet's: rust {obj} vs {obj_ref}"
    );

    // probabilities and classes on the held-out test rows
    let out = mnet_predict(&model, &mat(&d.x_test)).unwrap();
    let ref_pp = f64s(&r, "probs_fix");
    assert_eq!(ref_pp.len(), d.x_test.len() * 3);
    let mut max_pd = 0.0f64;
    for (i, row) in out.probabilities.iter().enumerate() {
        assert!((row.iter().sum::<f64>() - 1.0).abs() < 1e-10, "row {i}");
        for (c, &v) in row.iter().enumerate() {
            max_pd = max_pd.max((v - ref_pp[i * 3 + c]).abs());
        }
    }
    assert!(max_pd <= TOL_PROB, "max prob diff {max_pd} > {TOL_PROB}");
    let ref_yhat: Vec<usize> = r["yhat_fix"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_u64().unwrap() as usize)
        .collect();
    assert_eq!(
        out.predictions, ref_yhat,
        "predicted classes at fixed lambda"
    );
}

#[test]
fn cv_curve_matches_glmnet_on_shared_folds() {
    let d = load_data();
    let r = load_ref();
    let x = mat(&d.x_train);
    let labels: Vec<String> = (0..3).map(|c| format!("class_{c}")).collect();
    let feats: Vec<String> = (0..x.ncols()).map(|j| format!("f{j}")).collect();
    let grid = f64s(&r, "lambda_grid");
    let n = d.y_train.len();

    // rebuild the shared foldid: test = rows of fold f, train = the rest
    let nf = r["nfolds"].as_u64().unwrap() as usize;
    let folds: Vec<(Vec<usize>, Vec<usize>)> = (0..nf)
        .map(|f| {
            (
                (0..n).filter(|&i| d.fold_train[i] != f).collect(),
                (0..n).filter(|&i| d.fold_train[i] == f).collect(),
            )
        })
        .collect();
    assert_eq!(folds.iter().map(|(_, t)| t.len()).sum::<usize>(), n);

    let (model, curve, _) = mnet_fit(
        &x,
        &d.y_train,
        &labels,
        &feats,
        &cfg(Some(grid.clone()), grid.len(), 10000, 1e-7),
        Some(&folds),
        LambdaSelect::Min,
    )
    .unwrap();

    // CV deviance curve within the design tolerance
    let cvm = f64s(&r, "cvm");
    assert_eq!(curve.cv_deviance.len(), cvm.len());
    let max_diff = curve
        .cv_deviance
        .iter()
        .zip(&cvm)
        .map(|(a, b)| (a - b).abs())
        .fold(0.0, f64::max);
    assert!(
        max_diff <= TOL_CV,
        "max |cv deviance diff| {max_diff} > {TOL_CV}"
    );

    // λ.min / λ.1se: fold fits converge along flat valleys, so the exact
    // argmin index can shift by one grid step; two steps = failure
    let step = (grid[0].ln() - grid[grid.len() - 1].ln()) / (grid.len() - 1) as f64;
    let near = |a: f64, b: f64| (a.ln() - b.ln()).abs() <= 2.0 * step;
    assert!(
        near(curve.lambda_min, r["lambda_min"].as_f64().unwrap()),
        "lambda.min: rust {} vs glmnet {}",
        curve.lambda_min,
        r["lambda_min"].as_f64().unwrap()
    );
    assert!(
        near(curve.lambda_1se, r["lambda_1se"].as_f64().unwrap()),
        "lambda.1se: rust {} vs glmnet {}",
        curve.lambda_1se,
        r["lambda_1se"].as_f64().unwrap()
    );

    // df along the path: exact at the fixed λ, ±1 elsewhere (borderline
    // coefficients can flip between solvers at small λ)
    let df_ref: Vec<usize> = r["df_path"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_u64().unwrap() as usize)
        .collect();
    assert_eq!(curve.nonzero_features.len(), df_ref.len());
    assert!(curve.nonzero_features.windows(2).all(|w| w[0] <= w[1]));
    for (i, (a, b)) in curve.nonzero_features.iter().zip(&df_ref).enumerate() {
        assert!(
            (*a as i64 - *b as i64).abs() <= 1,
            "df[{i}]: rust {a} vs glmnet {b}"
        );
    }

    // the selected model is fit at lambda.min and predicts sanely
    let out = mnet_predict(&model, &x).unwrap();
    assert!(!out.predictions.is_empty());
    assert!(
        (curve.lambda_min - model.lambda_selected).abs() < 1e-14,
        "Min selection should fit at lambda.min"
    );
}
