//! PAM (nearest shrunken centroid) vs pamr golden.
//!
//! Golden files are generated by `tests/golden/gen_pam_reference.R`
//! (run it from the repo root).  The R script self-checks its formula
//! statistics against pamr's stored internals before writing.
//!
//! Run: `cargo test -p ml --test pam_r_reference`

use ml::centroid::{DeltaSelect, pam_fit, pam_predict};
use serde_json::Value;

const TOL: f64 = 1e-10;
const TOL_POST: f64 = 1e-8;

struct Data {
    x_train: Vec<Vec<f64>>,
    y_train: Vec<usize>,
    x_test: Vec<Vec<f64>>,
}

fn load_data() -> Data {
    let csv = std::fs::read_to_string(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/golden/pam_data.csv"
    ))
    .expect("pam_data.csv not found — run gen_pam_reference.R first");
    let mut tr_x = Vec::new();
    let mut tr_y = Vec::new();
    let mut te_x = Vec::new();
    for (i, line) in csv.lines().enumerate() {
        if i == 0 || line.trim().is_empty() {
            continue;
        }
        let cols: Vec<&str> = line.split(',').collect();
        let y: usize = cols[1].trim().parse().unwrap();
        let row: Vec<f64> = cols[2..]
            .iter()
            .map(|v| v.trim().parse().unwrap())
            .collect();
        // write.csv quotes string columns — strip the quotes before matching
        if cols[0].trim().trim_matches('"') == "train" {
            tr_y.push(y);
            tr_x.push(row);
        } else {
            te_x.push(row);
        }
    }
    Data {
        x_train: tr_x,
        y_train: tr_y,
        x_test: te_x,
    }
}

fn load_ref() -> Value {
    let json = std::fs::read_to_string(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/golden/pam_reference.json"
    ))
    .expect("pam_reference.json not found — run gen_pam_reference.R first");
    serde_json::from_str(&json).unwrap()
}

fn mat(rows: &[Vec<f64>]) -> faer::Mat<f64> {
    faer::Mat::from_fn(rows.len(), rows[0].len(), |i, j| rows[i][j])
}

fn f64s(v: &Value, key: &str) -> Vec<f64> {
    v[key]
        .as_array()
        .unwrap()
        .iter()
        .map(|x| x.as_f64().unwrap())
        .collect()
}

fn close(a: f64, b: f64, tol: f64, what: &str) {
    assert!(
        (a - b).abs() <= tol,
        "{what}: rust {a} vs pamr {b} (|diff| {} > {tol})",
        (a - b).abs()
    );
}

#[test]
fn training_stats_and_grid_match_pamr() {
    let d = load_data();
    let r = load_ref();
    let x = mat(&d.x_train);
    let labels: Vec<String> = (0..3).map(|c| format!("class_{c}")).collect();
    let feats: Vec<String> = (0..x.ncols()).map(|j| format!("f{j}")).collect();
    // default-grid path without folds → exercises seq(0, max|d|, 30)
    let (model, curve, _) = pam_fit(
        &x,
        &d.y_train,
        &labels,
        &feats,
        None,
        None,
        DeltaSelect::MinError,
    )
    .unwrap();

    for (name, got, want) in [
        ("grand_mean", &model.grand_mean, f64s(&r, "grand_mean")),
        ("pooled_sd", &model.pooled_sd, f64s(&r, "pooled_sd")),
        ("se_scale", &model.se_scale, f64s(&r, "se_scale")),
        ("priors", &model.priors, f64s(&r, "priors")),
    ] {
        assert_eq!(got.len(), want.len(), "{name} length");
        for (i, (a, b)) in got.iter().zip(&want).enumerate() {
            close(*a, *b, TOL, &format!("{name}[{i}]"));
        }
    }
    let grid = f64s(&r, "threshold_grid");
    assert_eq!(curve.delta.len(), grid.len(), "grid length");
    for (i, (a, b)) in curve.delta.iter().zip(&grid).enumerate() {
        close(*a, *b, TOL, &format!("grid[{i}]"));
    }
    // no folds: Δ=0 model, empty error columns
    assert_eq!(model.delta_selected, 0.0);
    assert!(curve.cv_error.is_empty() && curve.cv_se.is_empty());
}

#[test]
fn posterior_and_signature_match_pamr_at_fixed_delta() {
    let d = load_data();
    let r = load_ref();
    let x = mat(&d.x_train);
    let labels: Vec<String> = (0..3).map(|c| format!("class_{c}")).collect();
    let feats: Vec<String> = (0..x.ncols()).map(|j| format!("f{j}")).collect();
    let thr = r["thr"].as_f64().unwrap();
    // single-point grid pins the selected Δ to pamr's threshold[15]
    let (model, _, sig) = pam_fit(
        &x,
        &d.y_train,
        &labels,
        &feats,
        Some(vec![thr]),
        None,
        DeltaSelect::MinError,
    )
    .unwrap();
    close(model.delta_selected, thr, TOL, "delta_selected");

    let out = pam_predict(&model, &mat(&d.x_test)).unwrap();
    let ref_pp = f64s(&r, "posterior"); // row-major n_test × k
    assert_eq!(ref_pp.len(), d.x_test.len() * 3);
    for (i, row) in out.probabilities.iter().enumerate() {
        assert!(
            (row.iter().sum::<f64>() - 1.0).abs() < 1e-10,
            "row {i} sums to 1"
        );
        for (c, &v) in row.iter().enumerate() {
            close(
                v,
                ref_pp[i * 3 + c],
                TOL_POST,
                &format!("posterior[{i}][{c}]"),
            );
        }
    }
    let ref_yhat: Vec<usize> = r["yhat"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_u64().unwrap() as usize)
        .collect();
    assert_eq!(out.predictions, ref_yhat, "predicted classes");

    let ref_nz: Vec<usize> = r["signature_features"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_u64().unwrap() as usize)
        .collect();
    let got: std::collections::BTreeSet<usize> = sig.iter().map(|e| e.feature_index).collect();
    let want: std::collections::BTreeSet<usize> = ref_nz.into_iter().collect();
    assert_eq!(got, want, "signature feature set");
}
