//! R golden test for `ml::rotation` (varimax / promax ports).
//!
//! Golden files are generated by `tests/golden/gen_rotation_reference.R`
//! (base R `stats::varimax` / `stats::promax`, jsonlite) — run it first:
//! `Rscript stat_crates/ml/tests/golden/gen_rotation_reference.R`.
//!
//! Tolerance is 1e-8: R's varimax loop stops at `eps = 1e-5` on the relative
//! criterion change, but the `u %*% vt` rotation is invariant to paired sign
//! flips of the SVD factors, so the converged solutions agree to near machine
//! precision in practice.

use ml::rotation::{promax, varimax};

fn load_reference() -> serde_json::Value {
    let text = std::fs::read_to_string(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/golden/rotation_reference.json"
    ))
    .expect("rotation_reference.json missing — run gen_rotation_reference.R");
    serde_json::from_str(&text).unwrap()
}

fn mat_from_json(vals: &serde_json::Value, rows: usize, cols: usize) -> faer::Mat<f64> {
    let flat = vals.as_array().unwrap();
    assert_eq!(flat.len(), rows * cols);
    // Stored row-major (R: as.numeric(t(m))).
    faer::Mat::from_fn(rows, cols, |i, j| flat[i * cols + j].as_f64().unwrap())
}

fn compare(actual: &faer::Mat<f64>, expected: &faer::Mat<f64>, what: &str) {
    let (r, c) = actual.shape();
    assert_eq!(expected.shape(), (r, c), "{what} shape");
    for i in 0..r {
        for j in 0..c {
            let a = actual[(i, j)];
            let b = expected[(i, j)];
            assert!((a - b).abs() <= 1e-8, "{what}[{i}][{j}]: rust {a} vs R {b}");
        }
    }
}

#[test]
fn varimax_promax_match_r() {
    let r = load_reference();
    for key in ["main", "small"] {
        let rows = r["rows"][key].as_u64().unwrap() as usize;
        let cols = r["cols"][key].as_u64().unwrap() as usize;
        let x = mat_from_json(&r[key]["loadings"], rows, cols);

        // varimax, normalize = TRUE (R default)
        let vm = varimax(&x, true, 1e-5).unwrap();
        compare(
            &vm.loadings,
            &mat_from_json(&r[key]["varimax"]["loadings"], rows, cols),
            &format!("{key} varimax loadings"),
        );
        compare(
            &vm.rotmat,
            &mat_from_json(&r[key]["varimax"]["rotmat"], cols, cols),
            &format!("{key} varimax rotmat"),
        );

        // varimax, normalize = FALSE
        let vm0 = varimax(&x, false, 1e-5).unwrap();
        compare(
            &vm0.loadings,
            &mat_from_json(&r[key]["varimax_unnorm"]["loadings"], rows, cols),
            &format!("{key} varimax-unnorm loadings"),
        );
        compare(
            &vm0.rotmat,
            &mat_from_json(&r[key]["varimax_unnorm"]["rotmat"], cols, cols),
            &format!("{key} varimax-unnorm rotmat"),
        );

        // promax, m = 4 (R default; internally varimax with normalize = TRUE)
        let pm = promax(&x, 4.0).unwrap();
        compare(
            &pm.loadings,
            &mat_from_json(&r[key]["promax"]["loadings"], rows, cols),
            &format!("{key} promax loadings"),
        );
        compare(
            &pm.rotmat,
            &mat_from_json(&r[key]["promax"]["rotmat"], cols, cols),
            &format!("{key} promax rotmat"),
        );
    }
}
