//! R golden test for the `svy_rcs` node — design-based restricted cubic
//! splines vs R survey 4.5.
//!
//! Golden files are generated by `tests/golden/gen_svy_rcs_reference.R`
//! (rocker/r-ver:4.5.1 probe): explicit knots are shared by both sides and
//! the Harrell basis is implemented independently in R, then fitted with
//! `svyglm` and tested with `regTermTest(method="Wald")`.
//!
//! Run: `cargo test -p nodes-survey --test svy_rcs_r_reference`

use std::sync::Arc;

use arrow_array::{Float64Array, Int64Array, RecordBatch};
use arrow_schema::{DataType, Field, Schema};
use dag_core::node::NodeInput;
use dag_core::registry::{NodeCtx, NodeFactory};

use nodes_survey::survey_rcs::SvyRcsFactory;

fn read_csv() -> (
    Vec<i64>,
    Vec<i64>,
    Vec<f64>,
    Vec<f64>,
    Vec<f64>,
    Vec<f64>,
    Vec<f64>,
) {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/golden/rcs_data.csv");
    let text =
        std::fs::read_to_string(path).expect("rcs_data.csv missing — regenerate via the probe");
    let mut st = Vec::new();
    let mut psu = Vec::new();
    let mut xx = Vec::new();
    let mut cc = Vec::new();
    let mut yy_lin = Vec::new();
    let mut yy_bin = Vec::new();
    let mut wt = Vec::new();
    for (i, line) in text.lines().enumerate() {
        if i == 0 {
            continue; // header
        }
        let f: Vec<&str> = line.split(',').collect();
        st.push(f[0].parse().unwrap());
        psu.push(f[1].parse().unwrap());
        xx.push(f[2].parse().unwrap());
        cc.push(f[3].parse().unwrap());
        yy_lin.push(f[4].parse().unwrap());
        yy_bin.push(f[5].parse::<f64>().unwrap());
        wt.push(f[6].parse().unwrap());
    }
    (st, psu, xx, cc, yy_lin, yy_bin, wt)
}

fn make_batch() -> RecordBatch {
    let (st, psu, xx, cc, yy_lin, _yy_bin, wt) = read_csv();
    let n = st.len();
    let _ = n;
    let to_arr = |v: Vec<f64>| Arc::new(Float64Array::from(v)) as Arc<dyn arrow_array::Array>;
    let to_int = |v: Vec<i64>| Arc::new(Int64Array::from(v)) as Arc<dyn arrow_array::Array>;
    RecordBatch::try_new(
        Arc::new(Schema::new(vec![
            Field::new("st3", DataType::Int64, false),
            Field::new("psu3", DataType::Int64, false),
            Field::new("xx", DataType::Float64, false),
            Field::new("cc", DataType::Float64, false),
            Field::new("yy_lin", DataType::Float64, false),
            Field::new("wt3", DataType::Float64, false),
        ])),
        vec![
            to_int(st),
            to_int(psu),
            to_arr(xx),
            to_arr(cc),
            to_arr(yy_lin),
            to_arr(wt),
        ],
    )
    .unwrap()
}

fn node_ctx() -> NodeCtx {
    NodeCtx::new(
        datafusion::prelude::SessionContext::new().runtime_env(),
        None,
    )
}

async fn run(spec: serde_json::Value, batch: RecordBatch) -> Vec<RecordBatch> {
    let mut node = SvyRcsFactory.build(spec, node_ctx()).unwrap();
    let input = NodeInput::new_dataframe(
        0,
        datafusion::prelude::SessionContext::new()
            .read_batch(batch)
            .unwrap(),
    );
    let outs = node
        .execute(
            &node_ctx(),
            &[input],
            &dag_core::dag::node_event::NodeReporter::noop(),
        )
        .await
        .unwrap();
    outs.dataframe(0).unwrap().clone().collect().await.unwrap()
}

fn f(rows: &[RecordBatch], name: &str) -> f64 {
    let batch = &rows[0];
    let col = batch.column(batch.schema().index_of(name).unwrap());
    if let Some(a) = col.as_any().downcast_ref::<Float64Array>() {
        a.value(0)
    } else {
        col.as_any()
            .downcast_ref::<arrow_array::Int32Array>()
            .unwrap()
            .value(0) as f64
    }
}

const TOL: f64 = 1e-8;

#[tokio::test]
async fn svy_rcs_matches_r() {
    let ref_text = std::fs::read_to_string(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/golden/svy_rcs_reference.json"
    ))
    .expect("svy_rcs_reference.json missing — run gen_svy_rcs_reference.R");
    let r: serde_json::Value = serde_json::from_str(&ref_text).unwrap();

    let spec = serde_json::json!({
        "design": {"ids": ["psu3"], "strata": ["st3"], "weights": "wt3"},
        "x_column": "xx",
        "outcome_column": "yy_lin",
        "covariates": ["cc"],
        "knots": [4.0, 5.5, 7.0, 8.5],
    });
    let rows = run(spec, make_batch()).await;

    let close = |a: f64, b: f64, what: &str| {
        assert!(
            (a - b).abs() <= TOL,
            "{what}: rust {a} vs R {b} (|Δ| = {})",
            (a - b).abs()
        );
    };

    // Coefficients: intercept, xx, basis1, basis2, cc.
    let g = &r["gaussian"];
    for (i, name) in [
        "coef_intercept",
        "coef_x",
        "coef_basis_0",
        "coef_basis_1",
        "coef_cc",
    ]
    .iter()
    .enumerate()
    {
        close(
            f(&rows, name),
            g["coefficients"][i].as_f64().unwrap(),
            &format!("coef[{i}]"),
        );
    }
    // Nonlinearity Wald test (F statistic + p, ddf = degf + 1 − p).
    close(
        f(&rows, "nonlinear_stat"),
        g["nonlinear"]["F"].as_f64().unwrap(),
        "nonlinear F",
    );
    close(
        f(&rows, "nonlinear_p"),
        g["nonlinear"]["p"].as_f64().unwrap(),
        "nonlinear p",
    );
    assert_eq!(f(&rows, "nonlinear_ndf") as i64, 2);
    // ddf = degf(design) + 1 − p = (25 − 5) + 1 − 5 = 16.
    assert_eq!(g["nonlinear"]["ddf"].as_i64().unwrap(), 16);
    assert_eq!(f(&rows, "nonlinear_ddf") as i64, 16);
    assert_eq!(f(&rows, "n_obs") as i64, 500);
    close(
        f(&rows, "overall_stat"),
        g["overall"]["F"].as_f64().unwrap(),
        "overall F",
    );
    close(
        f(&rows, "overall_p"),
        g["overall"]["p"].as_f64().unwrap(),
        "overall p",
    );
    // Explicit knots round-trip.
    for (i, kv) in r["knots"].as_array().unwrap().iter().enumerate() {
        close(f(&rows, &format!("knot_{i}")), kv.as_f64().unwrap(), "knot");
    }
}
