//! R golden test for the survey LRT (`regTermTest(method="LRT")` /
//! `anova.svyglm(method="LRT")` equivalent).
//!
//! Golden files are generated by the one-shot rocker/r-ver:4.5.1 probe with
//! the R survey package 4.5 (see docs/design/survey-factor-rrr-mediation-nodes.md
//! for the probe commands):
//! - `tests/golden/lrt_data.csv` — 400-row stratified-clustered design
//!   (8 strata × 5 PSU × 10 obs) with one zero-weight row;
//! - `tests/golden/svy_lrt_reference.json` — LRT/Wald statistics from
//!   `regTermTest` + `anova.svyglm`, plus the ddf semantics check.
//!
//! Run: `cargo test -p survey --test svy_lrt_reference`

use std::collections::HashMap;

use survey::FamilySpec;
use survey::design::SurveyDesignBuilder;
use survey::model::{RegTermTestMethod, reg_term_test_with, svy_lrt, svyglm};

struct Case {
    y_key: &'static str,
    lrt_key: &'static str,
    family: FamilySpec,
}

fn close(a: f64, b: f64, tol: f64, what: &str) {
    assert!(
        (a - b).abs() <= tol,
        "{what}: rust {a} vs R {b} (|Δ| = {})",
        (a - b).abs()
    );
}

/// Minimal quoted-CSV reader for the R `write.csv` output used by the probe.
fn read_data(path: &str) -> HashMap<String, Vec<f64>> {
    let text = std::fs::read_to_string(path)
        .unwrap_or_else(|_| panic!("{path} not found — regenerate via the survey probe"));
    let mut cols: HashMap<String, Vec<f64>> = HashMap::new();
    let mut headers: Vec<String> = Vec::new();
    for (i, line) in text.lines().enumerate() {
        let fields: Vec<&str> = if line.starts_with('"') {
            // Header row: "a","b","c"
            line.split("\",\"").map(|f| f.trim_matches('"')).collect()
        } else {
            line.split(',').collect()
        };
        if i == 0 {
            headers = fields.iter().map(|s| s.to_string()).collect();
            for h in &headers {
                cols.insert(h.clone(), Vec::new());
            }
            continue;
        }
        assert_eq!(fields.len(), headers.len(), "ragged csv row {i}");
        for (h, f) in headers.iter().zip(&fields) {
            cols.get_mut(h).unwrap().push(f.parse::<f64>().unwrap());
        }
    }
    cols
}

fn build_design(d: &HashMap<String, Vec<f64>>) -> survey::design::SurveyDesign {
    let st: Vec<String> = d["st"].iter().map(|v| format!("s{v}")).collect();
    // PSU codes in the fixture are already globally unique; qualifying with
    // the stratum is a harmless canonicalisation (R survey nests ids).
    let psu: Vec<String> = d["psu"]
        .iter()
        .zip(&d["st"])
        .map(|(&p, &s)| format!("s{s}p{p}"))
        .collect();
    SurveyDesignBuilder::new()
        .strata(st)
        .cluster(psu)
        .weights(d["wt"].clone())
        .build()
        .expect("design")
}

#[test]
fn svy_lrt_matches_r_regter_test() {
    let base = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/golden/");
    let d = read_data(&format!("{}lrt_data.csv", base));
    let ref_json = std::fs::read_to_string(format!("{}svy_lrt_reference.json", base))
        .expect("svy_lrt_reference.json missing");
    let r: serde_json::Value = serde_json::from_str(&ref_json).unwrap();
    assert_eq!(r["survey_version"].as_str().unwrap(), "4.5");

    let design = build_design(&d);
    let x_full: Vec<Vec<f64>> = ["x1", "x2", "x3"].iter().map(|k| d[*k].clone()).collect();
    let x_red: Vec<Vec<f64>> = vec![d["x3"].clone()];
    // Tested coefficients: x1, x2 → indices 1 and 2 (0-based, after
    // intercept); R's regTermTest(mg, ~x1 + x2).
    let test_indices: [usize; 2] = [1, 2];

    for case in [
        Case {
            y_key: "y_gauss",
            lrt_key: "gaussian",
            family: FamilySpec::new("gaussian", None).unwrap(),
        },
        Case {
            y_key: "y_bin",
            lrt_key: "binomial",
            family: FamilySpec::new("quasibinomial", None).unwrap(),
        },
    ] {
        let y = &d[case.y_key];
        let fit_full =
            svyglm(y, &x_full, &design, true, None, &case.family, None).expect("full fit failed");
        let fit_red =
            svyglm(y, &x_red, &design, true, None, &case.family, None).expect("reduced fit failed");

        let g = &r["lrt"][case.lrt_key];
        // Deviances (validates the weighted-deviance field + zero-weight row).
        close(
            fit_full.deviance,
            g["deviance_full"].as_f64().unwrap(),
            1e-6,
            &format!("{} deviance_full", case.lrt_key),
        );
        close(
            fit_red.deviance,
            g["deviance_reduced"].as_f64().unwrap(),
            1e-6,
            &format!("{} deviance_reduced", case.lrt_key),
        );

        let t = svy_lrt(&fit_full, &fit_red, &test_indices).expect("svy_lrt");
        close(
            t.statistic,
            g["chisq"].as_f64().unwrap(),
            1e-6,
            &format!("{} chisq", case.lrt_key),
        );
        assert_eq!(t.ndf, g["ndf"].as_u64().unwrap() as usize);
        assert_eq!(t.ddf, g["ddf"].as_u64().unwrap() as usize);
        // p: saddlepoint reproduces R to ~1e-6 absolute (see pfsum tests for
        // the uniroot-tolerance analysis); these goldens are tiny, so compare
        // with a relative band.
        let p_r = g["p"].as_f64().unwrap();
        assert!(
            (t.p_value - p_r).abs() <= (1e-6_f64).max(1e-3 * p_r.abs()),
            "{} p: rust {} vs R {}",
            case.lrt_key,
            t.p_value,
            p_r
        );

        // Cross-check the Wald branch on the same fit (design-covariance
        // regression guard; the R Wald golden p is also in the JSON).
        let w = reg_term_test_with(&fit_full, &test_indices, RegTermTestMethod::Wald).unwrap();
        let w_r = &r["wald"][case.lrt_key];
        let p_w = w_r["p"].as_f64().unwrap();
        assert!(
            (w.p_value - p_w).abs() <= (1e-6_f64).max(1e-3 * p_w.abs()),
            "{} wald p: rust {} vs R {}",
            case.lrt_key,
            w.p_value,
            p_w
        );
    }
}

#[test]
fn svy_lrt_rejects_mismatched_row_sets() {
    let base = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/golden/");
    let d = read_data(&format!("{}lrt_data.csv", base));
    let design = build_design(&d);
    let spec = FamilySpec::new("gaussian", None).unwrap();
    let x_full: Vec<Vec<f64>> = ["x1", "x2", "x3"].iter().map(|k| d[*k].clone()).collect();

    // Full fit on complete rows (400 incl. the zero-weight row).
    let fit_full = svyglm(&d["y_gauss"], &x_full, &design, true, None, &spec, None).unwrap();
    assert_eq!(fit_full.n, 400);

    // Reduced fit with a NaN response row: svyglm's internal filter drops it,
    // so n differs from the full fit — svy_lrt must reject the pair.
    let mut y_short = d["y_gauss"].clone();
    y_short[0] = f64::NAN;
    let x_red: Vec<Vec<f64>> = vec![d["x3"].clone()];
    let fit_red = svyglm(&y_short, &x_red, &design, true, None, &spec, None).unwrap();
    assert_eq!(fit_red.n, 399);
    assert!(svy_lrt(&fit_full, &fit_red, &[2, 3]).is_err());

    // Non-nested coefficient counts are rejected too: same-row reduced fit
    // with 3 coefficients + 2 tested ≠ 4 (full).
    let x_red2: Vec<Vec<f64>> = vec![d["x2"].clone(), d["x3"].clone()];
    let fit_red2 = svyglm(&d["y_gauss"], &x_red2, &design, true, None, &spec, None).unwrap();
    assert_eq!(fit_red2.n, fit_full.n);
    assert!(svy_lrt(&fit_full, &fit_red2, &[2, 3]).is_err());
}
