//! R golden test for `survey::svy_coxph` — design-based Cox variance parity.
//!
//! Golden files are generated by `tests/golden/gen_svy_coxph_reference.R`
//! (local R survey 4.5 + survival): `survey::svycoxph` with rescaled
//! probability weights, whose variance is
//! `svyrecvar(resid(fit, "dfbeta", weighted = TRUE))` — weighted score
//! residuals with risk-set mean centering.  Event times are tie-free so
//! the Breslow partial likelihood equals coxph's Efron default.
//!
//! Run: `cargo test -p survey --test svy_coxph_reference`

use std::collections::HashMap;

use survey::design::{SurveyDesign, SurveyDesignBuilder};
use survey::survival::svy_coxph;

/// Minimal quoted-CSV reader for the R `write.csv` output.
fn read_data(path: &str) -> HashMap<String, Vec<f64>> {
    let text = std::fs::read_to_string(path)
        .unwrap_or_else(|_| panic!("{path} not found — run gen_svy_coxph_reference.R"));
    let mut cols: HashMap<String, Vec<f64>> = HashMap::new();
    let mut headers: Vec<String> = Vec::new();
    for (i, line) in text.lines().enumerate() {
        let fields: Vec<&str> = if line.starts_with('"') {
            line.split("\",\"").map(|f| f.trim_matches('"')).collect()
        } else {
            line.split(',').collect()
        };
        if i == 0 {
            headers = fields.iter().map(|s| s.to_string()).collect();
            for h in &headers {
                cols.insert(h.clone(), Vec::new());
            }
            continue;
        }
        assert_eq!(fields.len(), headers.len(), "ragged csv row {i}");
        for (h, f) in headers.iter().zip(&fields) {
            cols.get_mut(h).unwrap().push(f.parse::<f64>().unwrap());
        }
    }
    cols
}

fn build_design(d: &HashMap<String, Vec<f64>>) -> SurveyDesign {
    let st: Vec<String> = d["st"].iter().map(|v| format!("s{v}")).collect();
    // PSU codes are nested within strata (R survey `nest = TRUE`).
    let psu: Vec<String> = d["psu"]
        .iter()
        .zip(&d["st"])
        .map(|(&p, &s)| format!("s{s}p{p}"))
        .collect();
    SurveyDesignBuilder::new()
        .strata(st)
        .cluster(psu)
        .weights(d["wt"].clone())
        .build()
        .expect("design")
}

const TOL: f64 = 1e-8;

#[test]
fn svy_coxph_matches_r() {
    let d = read_data(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/golden/coxph_data.csv"
    ));
    let design = build_design(&d);

    let x = vec![d["x1"].clone(), d["x2"].clone()];
    let fit = svy_coxph(&d["time"], &d["event"], &x, &design).expect("svy_coxph");

    let ref_text = std::fs::read_to_string(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/golden/svy_coxph_reference.json"
    ))
    .expect("svy_coxph_reference.json missing — run gen_svy_coxph_reference.R");
    let r: serde_json::Value = serde_json::from_str(&ref_text).unwrap();

    let close = |a: f64, b: f64, what: &str| {
        assert!(
            (a - b).abs() <= TOL,
            "{what}: rust {a} vs R {b} (|Δ| = {})",
            (a - b).abs()
        );
    };

    assert_eq!(fit.n as i64, r["n"].as_i64().unwrap());
    assert_eq!(fit.n_events as i64, r["n_events"].as_i64().unwrap());
    for i in 0..2 {
        close(
            fit.coefficients[i],
            r["coefficients"][i].as_f64().unwrap(),
            &format!("coef[{i}]"),
        );
        close(
            fit.design_cov[i][i].sqrt(),
            r["se"][i].as_f64().unwrap(),
            &format!("se[{i}]"),
        );
        for j in 0..2 {
            close(
                fit.design_cov[i][j],
                r["vcov"][i][j].as_f64().unwrap(),
                &format!("vcov[{i}][{j}]"),
            );
        }
    }
}
