//! Cross-validation of the Rust HDL-L port against the R golden outputs
//! (generated by `tests/fixtures-gen/gen_golden.R`).
//!
//! The golden fixture is a single simulated region (233 SNPs): `gen_golden.R`
//! builds the LD reference `(lam, V, LDsc)` from the demo PLINK that ships with
//! the HDL repo, simulates per-SNP `bhat` from the HDL eigen-space model with
//! known parameters, and runs a faithful transcription of `HDL/R/HDL.L.R`'s
//! numerical core using R's own `optim(L-BFGS-B)`.
//!
//! This test loads R's exact arrays, runs the Rust estimator, and compares the
//! MLE / LRT P / profile-CI outputs. The HDL-L estimator is fully deterministic,
//! so comparisons are exact value-by-value alignments (no Monte-Carlo tolerance).
//!
//! Fixture size is tiny (233 SNPs), so this runs as a normal (non-ignored) test.

use std::collections::HashMap;
use std::path::{Path, PathBuf};

use faer::Mat;
use hdl::locus::{self, DEFAULT_ALPHA, DEFAULT_EIGEN_CUT, DEFAULT_LIM, DEFAULT_NREF};

const GOLDEN: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures/golden");

fn gold(name: &str) -> PathBuf {
    Path::new(GOLDEN).join(name)
}

/// Read a single-column TSV of f64 (no header).
fn read_col(path: &Path) -> Vec<f64> {
    std::fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("read {}: {e}", path.display()))
        .lines()
        .filter(|l| !l.trim().is_empty())
        .map(|l| l.trim().parse::<f64>().unwrap())
        .collect()
}

/// Read a header-keyed one-row TSV into a map.
fn read_meta(path: &Path) -> HashMap<String, f64> {
    let s = std::fs::read_to_string(path).unwrap();
    let mut lines = s.lines();
    let header: Vec<&str> = lines.next().unwrap().split('\t').collect();
    let vals: Vec<&str> = lines.next().unwrap().split('\t').collect();
    header
        .iter()
        .zip(vals.iter())
        .map(|(k, v)| (k.to_string(), v.parse::<f64>().unwrap()))
        .collect()
}

/// Read a whitespace/tab-delimited matrix TSV (no header) into a faer Mat.
fn read_matrix(path: &Path) -> Mat<f64> {
    let rows: Vec<Vec<f64>> = std::fs::read_to_string(path)
        .unwrap()
        .lines()
        .filter(|l| !l.trim().is_empty())
        .map(|l| l.split_whitespace().map(|x| x.parse::<f64>().unwrap()).collect())
        .collect();
    let n = rows.len();
    let m = rows[0].len();
    Mat::from_fn(n, m, |i, j| rows[i][j])
}

fn close(a: f64, b: f64, rel: f64, abs: f64) -> bool {
    if a.is_nan() && b.is_nan() {
        return true;
    }
    if a.is_nan() || b.is_nan() {
        return false;
    }
    (a - b).abs() <= rel * b.abs().max(1e-12) + abs
}

#[test]
fn estimator_from_r_arrays() {
    let lam = read_col(&gold("lam.tsv"));
    let v = read_matrix(&gold("V.tsv"));
    let ldsc = read_col(&gold("ldsc.tsv"));
    let bhat1 = read_col(&gold("bhat1.tsv"));
    let bhat2 = read_col(&gold("bhat2.tsv"));
    let meta = read_meta(&gold("result.tsv"));

    let n1 = meta["N1"];
    let n2 = meta["N2"];
    let n0 = meta["N0"];
    let eigen_cut = meta["eigen.cut"];
    let lim = meta["lim"];
    let alpha = meta["alpha"];

    let res = locus::run_locus(
        &bhat1,
        &bhat2,
        &lam,
        v.as_ref(),
        &ldsc,
        n1,
        n2,
        n0,
        DEFAULT_NREF,
        eigen_cut,
        lim,
        alpha,
    )
    .expect("run_locus");

    // ---- deterministic point estimates (tight tolerance) ----
    println!(
        "h11: rust={:.6} R={:.6} | h22: rust={:.6} R={:.6}",
        res.h11, meta["h11"], res.h22, meta["h22"]
    );
    assert!(close(res.h11, meta["h11"], 1e-4, 1e-6), "h11 mismatch");
    assert!(close(res.h22, meta["h22"], 1e-4, 1e-6), "h22 mismatch");

    println!(
        "h12: rust={:.6} R={:.6} | int_h12: rust={:.4} R={:.4}",
        res.h12, meta["h12"], res.int_h12, meta["int.h12"]
    );
    assert!(close(res.h12, meta["h12"], 1e-4, 1e-7), "h12 mismatch");

    // rg point estimate — 10000-point grid → ~2e-4 quantisation; allow 6e-4.
    println!(
        "rg: rust={:.6} R={:.6} | CI rust=[{:.4},{:.4}] R=[{:.4},{:.4}]",
        res.rg, meta["rg"], res.rg_lower, res.rg_upper, meta["rg.lower"], meta["rg.upper"]
    );
    assert!(close(res.rg, meta["rg"], 6e-4, 1e-4), "rg mismatch");
    assert!(close(res.rg_lower, meta["rg.lower"], 5e-3, 1e-3), "rg.lower mismatch");
    assert!(close(res.rg_upper, meta["rg.upper"], 5e-3, 1e-3), "rg.upper mismatch");

    // ---- LRT P values (relative tolerance for the tiny tails) ----
    println!(
        "p_h1: rust={:.4e} R={:.4e} | p_h2: rust={:.4e} R={:.4e} | p_h12: rust={:.4e} R={:.4e}",
        res.p_h1, meta["p.h1"], res.p_h2, meta["p.h2"], res.p_h12, meta["p.h12"]
    );
    assert!(
        close(res.p_h1, meta["p.h1"], 1e-3, 1e-300),
        "p_h1 mismatch"
    );
    assert!(
        close(res.p_h2, meta["p.h2"], 1e-3, 1e-300),
        "p_h2 mismatch"
    );
    assert!(
        close(res.p_h12, meta["p.h12"], 2e-2, 1e-12),
        "p_h12 mismatch"
    );

    // ---- eigen-cut retained component count ----
    assert_eq!(
        res.n_retained,
        meta["n.retained"] as usize,
        "eigen-cut retained count mismatch"
    );
    assert!(res.converged, "Rust reported non-convergence");
    println!("estimator_from_r_arrays OK (K={})", res.n_retained);
}

/// Default-argument entry point agrees with explicit defaults.
#[test]
fn defaults_match_explicit() {
    let lam = read_col(&gold("lam.tsv"));
    let v = read_matrix(&gold("V.tsv"));
    let ldsc = read_col(&gold("ldsc.tsv"));
    let bhat1 = read_col(&gold("bhat1.tsv"));
    let bhat2 = read_col(&gold("bhat2.tsv"));
    let meta = read_meta(&gold("result.tsv"));

    let explicit = locus::run_locus(
        &bhat1, &bhat2, &lam, v.as_ref(), &ldsc, meta["N1"], meta["N2"], meta["N0"],
        DEFAULT_NREF, DEFAULT_EIGEN_CUT, DEFAULT_LIM, DEFAULT_ALPHA,
    )
    .unwrap();
    assert!(close(explicit.h11, meta["h11"], 1e-4, 1e-6));
    assert!(close(explicit.rg, meta["rg"], 6e-4, 1e-4));
}

// ===========================================================================
// PLINK-path tests (#2 reference_from_plink, #3 full_pipeline).
//
// These rebuild the LD reference from the demo PLINK that ships under
// `reference/HDL/` and validate (a) that the Rust eigen-decomposition matches
// R's exported `(lam, V)` via a sign/permutation-invariant reconstruction
// `R = V·diag(lam)·Vᵀ`, and (b) that the full PLINK→eigen→estimate pipeline
// agrees with the golden results.
//
// They require the reference repo at `reference/HDL/` (committed); if absent,
// they are skipped so CI without the data still passes.
// ===========================================================================

/// Path to the demo PLINK prefix inside the cloned HDL reference repo.
fn demo_prefix() -> PathBuf {
    // CARGO_MANIFEST_DIR = bio_crates/hdl → repo root is two levels up.
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../reference/HDL/build_ld_ref/demo/test")
}

fn demo_available() -> bool {
    let p = demo_prefix();
    p.with_extension("bed").is_file()
}

/// Reconstruct `R = V·diag(lam)·Vᵀ` (sign/permutation invariant for comparison).
fn reconstruct_r(lam: &[f64], v: Mat<f64>) -> Mat<f64> {
    let n = lam.len();
    let vd = Mat::from_fn(n, n, |i, j| v[(i, j)] * lam[j]); // V·diag(lam)
    let vt = vd.transpose();
    &vd * vt
}

fn frobenius_diff(a: &Mat<f64>, b: &Mat<f64>) -> f64 {
    let mut s = 0.0;
    for i in 0..a.nrows() {
        for j in 0..a.ncols() {
            let d = a[(i, j)] - b[(i, j)];
            s += d * d;
        }
    }
    s.sqrt()
}

#[test]
fn reference_from_plink() {
    if !demo_available() {
        eprintln!("skipping reference_from_plink: demo PLINK not present");
        return;
    }
    let snps_raw = std::fs::read_to_string(gold("snps.tsv")).unwrap();
    let snps: Vec<String> = snps_raw
        .lines()
        .filter(|l| !l.trim().is_empty())
        .map(|l| l.trim().to_string())
        .collect();

    let ldref = hdl::reference::ld_ref_from_plink(&demo_prefix(), &snps)
        .expect("ld_ref_from_plink");

    // eigenvalues should match R to high precision.
    let lam_r = read_col(&gold("lam.tsv"));
    let lam_rust = &ldref.lam;
    let mut max_lam_err = 0.0f64;
    for (a, b) in lam_rust.iter().zip(lam_r.iter()) {
        max_lam_err = max_lam_err.max((a - b).abs());
    }
    println!("reference_from_plink: max |lam_rust - lam_R| = {max_lam_err:.3e}");
    // faer vs R eigen on the same symmetric matrix → very close.
    assert!(max_lam_err < 1e-6, "eigenvalue mismatch too large: {max_lam_err}");

    // reconstructed R must match (sign/permutation invariant).
    let v_r = read_matrix(&gold("V.tsv"));
    let r_r = reconstruct_r(&lam_r, v_r);
    let r_rust = reconstruct_r(lam_rust, ldref.v.clone());
    let fd = frobenius_diff(&r_r, &r_rust);
    println!("reference_from_plink: ‖R_rust − R_R‖_F = {fd:.3e}");
    assert!(fd < 1e-8, "reconstructed R mismatch: {fd}");
    println!("reference_from_plink OK");
}

#[test]
fn full_pipeline() {
    if !demo_available() {
        eprintln!("skipping full_pipeline: demo PLINK not present");
        return;
    }
    let snps_raw = std::fs::read_to_string(gold("snps.tsv")).unwrap();
    let snps: Vec<String> = snps_raw
        .lines()
        .filter(|l| !l.trim().is_empty())
        .map(|l| l.trim().to_string())
        .collect();

    let ldref = hdl::reference::ld_ref_from_plink(&demo_prefix(), &snps)
        .expect("ld_ref_from_plink");
    let bhat1 = read_col(&gold("bhat1.tsv"));
    let bhat2 = read_col(&gold("bhat2.tsv"));
    let meta = read_meta(&gold("result.tsv"));

    // The golden bhat was simulated on R's eigen-basis; Rust's V may carry
    // different per-component signs, but the HDL likelihood is invariant to
    // eigenvector sign flips, so the estimates must still agree.
    let res = locus::run_locus(
        &bhat1,
        &bhat2,
        &ldref.lam,
        ldref.v.as_ref(),
        &ldref.ldsc,
        meta["N1"],
        meta["N2"],
        meta["N0"],
        DEFAULT_NREF,
        DEFAULT_EIGEN_CUT,
        DEFAULT_LIM,
        DEFAULT_ALPHA,
    )
    .expect("run_locus (full pipeline)");

    println!(
        "full_pipeline: h11 rust={:.6} R={:.6} | rg rust={:.4} R={:.4} | p_h12 rust={:.4e} R={:.4e}",
        res.h11, meta["h11"], res.rg, meta["rg"], res.p_h12, meta["p.h12"]
    );
    // Slightly looser than the estimator-only test (eigen library differences
    // in V feed through bstar, though the likelihood is sign-invariant).
    assert!(close(res.h11, meta["h11"], 1e-3, 1e-5), "h11 full-pipeline");
    assert!(close(res.h22, meta["h22"], 1e-3, 1e-5), "h22 full-pipeline");
    assert!(close(res.rg, meta["rg"], 1e-3, 1e-3), "rg full-pipeline");
    assert!(
        close(res.p_h12, meta["p.h12"], 5e-2, 1e-12),
        "p_h12 full-pipeline"
    );
    println!("full_pipeline OK");
}
