//! Cross-validation of the Rust MTAG port against Python golden outputs.
//!
//! The golden fixtures are generated by `tests/fixtures/gen_golden.py`, which
//! extracts the core MTAG mathematical functions (gmm_omega, mtag_analysis,
//! _posDef_adjustment, numerical_omega, cov2corr) from the Python reference
//! (`reference/mtag/mtag.py` v1.0.8) and runs them on synthetic scenarios with
//! deterministic seeds.
//!
//! Regenerate fixtures:
//!   cd bio_crates/mtag/tests/fixtures && python3 gen_golden.py
//!
//! Restore from archive (if golden_outputs.json is missing):
//!   rclone copy aliyun:autonomics-data/mtag/golden_outputs.json bio_crates/mtag/tests/fixtures/

use faer::Mat;
use serde_json::Value;

use mtag::linalg::{cov2corr, pos_def_adjustment};
use mtag::mtag::mtag_analysis;
use mtag::nelder::nelder_mead_generic;
use mtag::omega::{OmegaConfig, estimate_omega, flatten_out_omega, gmm_omega, rebuild_omega};

const FIXTURES: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures");

/// Tolerance for comparing floating-point values.
/// MTAG involves matrix inversions and Cholesky factorisations, so we use
/// a relative tolerance of 1e-6 (matching the `--tol` default in MTAG).
const RTOL: f64 = 1e-6;
/// Absolute tolerance for values near zero.
const ATOL: f64 = 1e-10;

fn close(a: f64, b: f64) -> bool {
    if a.is_nan() && b.is_nan() {
        return true;
    }
    if a.is_nan() || b.is_nan() {
        return false;
    }
    if a.is_infinite() && b.is_infinite() {
        return a.signum() == b.signum();
    }
    (a - b).abs() <= RTOL * b.abs().max(1e-12) + ATOL
}

/// Read the golden JSON file.
fn read_golden() -> Value {
    let path = format!("{FIXTURES}/golden_outputs.json");
    let s = std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!("Failed to read {path}: {e}. Run: cd tests/fixtures && python3 gen_golden.py")
    });
    serde_json::from_str(&s).expect("Failed to parse golden JSON")
}

/// Parse a JSON 2D array into a faer Mat.
fn json_to_mat(v: &Value) -> Mat<f64> {
    let rows = v.as_array().unwrap();
    let m = rows.len();
    let n = rows[0].as_array().unwrap().len();
    let mut mat = Mat::zeros(m, n);
    for (i, row) in rows.iter().enumerate() {
        for (j, val) in row.as_array().unwrap().iter().enumerate() {
            mat[(i, j)] = val.as_f64().unwrap();
        }
    }
    mat
}

/// Parse a JSON 3D array (M×P×P) into a Vec of P×P matrices.
#[allow(dead_code)]
fn json_to_3d(v: &Value) -> Vec<Mat<f64>> {
    v.as_array().unwrap().iter().map(json_to_mat).collect()
}

/// Compare two matrices element-by-element, printing the first mismatch.
fn assert_mat_close(a: &Mat<f64>, b: &Mat<f64>, name: &str) {
    assert_eq!(
        a.nrows(),
        b.nrows(),
        "{name}: row count mismatch: {} vs {}",
        a.nrows(),
        b.nrows()
    );
    assert_eq!(
        a.ncols(),
        b.ncols(),
        "{name}: col count mismatch: {} vs {}",
        a.ncols(),
        b.ncols()
    );
    for i in 0..a.nrows() {
        for j in 0..a.ncols() {
            if !close(a[(i, j)], b[(i, j)]) {
                panic!(
                    "{name}: mismatch at [{i},{j}]: Rust={:.12}, Python={:.12}, diff={:.2e}",
                    a[(i, j)],
                    b[(i, j)],
                    (a[(i, j)] - b[(i, j)]).abs()
                );
            }
        }
    }
}

#[test]
fn test_scenario1_gmm_omega() {
    let golden = read_golden();
    let s = &golden["scenario1"];

    let zs = json_to_mat(&s["Zs"]);
    let ns = json_to_mat(&s["Ns"]);
    let sigma_ld = json_to_mat(&s["sigma_LD"]);

    let omega_rust = gmm_omega(&zs, &ns, &sigma_ld);
    let omega_python = json_to_mat(&s["omega_gmm"]);

    assert_mat_close(&omega_rust, &omega_python, "GMM Omega (scenario 1)");
}

#[test]
fn test_scenario1_posdef_adjustment() {
    let golden = read_golden();
    let s = &golden["scenario1"];

    // GMM omega
    let zs = json_to_mat(&s["Zs"]);
    let ns = json_to_mat(&s["Ns"]);
    let sigma_ld = json_to_mat(&s["sigma_LD"]);
    let omega_gmm = gmm_omega(&zs, &ns, &sigma_ld);

    let omega_adj_rust = pos_def_adjustment(omega_gmm, 0.99, 1000).unwrap();
    let omega_adj_python = json_to_mat(&s["omega_gmm_adj"]);

    assert_mat_close(
        &omega_adj_rust,
        &omega_adj_python,
        "PosDef-adjusted Omega (scenario 1)",
    );
}

#[test]
fn test_scenario1_mtag_analysis() {
    let golden = read_golden();
    let s = &golden["scenario1"];

    let zs = json_to_mat(&s["Zs"]);
    let ns = json_to_mat(&s["Ns"]);
    let sigma_ld = json_to_mat(&s["sigma_LD"]);
    let omega_hat = json_to_mat(&s["omega_gmm_adj"]);

    let result = mtag_analysis(&zs, &ns, &omega_hat, &sigma_ld);

    assert_mat_close(
        &result.mtag_betas,
        &json_to_mat(&s["mtag_betas"]),
        "MTAG betas (scenario 1)",
    );
    assert_mat_close(
        &result.mtag_se,
        &json_to_mat(&s["mtag_se"]),
        "MTAG SEs (scenario 1)",
    );
    assert_mat_close(
        &result.mtag_factor,
        &json_to_mat(&s["mtag_factor"]),
        "MTAG factors (scenario 1)",
    );
}

#[test]
fn test_scenario2_gmm_omega_3traits() {
    let golden = read_golden();
    let s = &golden["scenario2"];

    let zs = json_to_mat(&s["Zs"]);
    let ns = json_to_mat(&s["Ns"]);
    let sigma_ld = json_to_mat(&s["sigma_LD"]);

    let omega_rust = gmm_omega(&zs, &ns, &sigma_ld);
    let omega_python = json_to_mat(&s["omega_gmm"]);

    assert_mat_close(
        &omega_rust,
        &omega_python,
        "GMM Omega (scenario 2, 3 traits)",
    );
}

#[test]
fn test_scenario2_mtag_analysis_3traits() {
    let golden = read_golden();
    let s = &golden["scenario2"];

    let zs = json_to_mat(&s["Zs"]);
    let ns = json_to_mat(&s["Ns"]);
    let sigma_ld = json_to_mat(&s["sigma_LD"]);
    let omega_hat = json_to_mat(&s["omega_gmm_adj"]);

    let result = mtag_analysis(&zs, &ns, &omega_hat, &sigma_ld);

    assert_mat_close(
        &result.mtag_betas,
        &json_to_mat(&s["mtag_betas"]),
        "MTAG betas (scenario 2, 3 traits)",
    );
    assert_mat_close(
        &result.mtag_se,
        &json_to_mat(&s["mtag_se"]),
        "MTAG SEs (scenario 2, 3 traits)",
    );
}

#[test]
fn test_scenario3_numerical_omega() {
    let golden = read_golden();
    let s = &golden["scenario3_numerical"];

    let zs = json_to_mat(&s["Zs"]);
    let ns = json_to_mat(&s["Ns"]);
    let sigma_ld = json_to_mat(&s["sigma_LD"]);
    let _omega_start = json_to_mat(&s["omega_start"]);
    let omega_python = json_to_mat(&s["omega_numerical"]);

    // Use the Rust numerical omega estimator.
    let cfg = OmegaConfig {
        numerical: true,
        perfect_gencov: false,
        equal_h2: false,
        tol: 1e-6,
        no_overlap: false,
    };
    let omega_rust = estimate_omega(&zs, &ns, &sigma_ld, &cfg).unwrap();

    // Numerical optimisation may not match exactly between scipy and our
    // Nelder-Mead — use a looser tolerance.
    for i in 0..omega_rust.nrows() {
        for j in 0..omega_rust.ncols() {
            let rust = omega_rust[(i, j)];
            let python = omega_python[(i, j)];
            let rel_err = (rust - python).abs() / python.abs().max(1e-12);
            assert!(
                rel_err < 0.05,
                "Numerical Omega mismatch at [{i},{j}]: Rust={rust:.8}, Python={python:.8}, rel_err={rel_err:.4}"
            );
        }
    }
}

#[test]
fn test_scenario3_mtag_with_numerical_omega() {
    let golden = read_golden();
    let s = &golden["scenario3_numerical"];

    let zs = json_to_mat(&s["Zs"]);
    let ns = json_to_mat(&s["Ns"]);
    let sigma_ld = json_to_mat(&s["sigma_LD"]);
    let omega_hat = json_to_mat(&s["omega_numerical"]);

    let result = mtag_analysis(&zs, &ns, &omega_hat, &sigma_ld);

    assert_mat_close(
        &result.mtag_betas,
        &json_to_mat(&s["mtag_betas"]),
        "MTAG betas (scenario 3, numerical omega)",
    );
    assert_mat_close(
        &result.mtag_se,
        &json_to_mat(&s["mtag_se"]),
        "MTAG SEs (scenario 3, numerical omega)",
    );
}

#[test]
fn test_scenario4_posdef_adjustment() {
    let golden = read_golden();
    let s = &golden["scenario4_posdef"];

    let input = json_to_mat(&s["input"]);
    let adjusted_python = json_to_mat(&s["adjusted"]);

    let adjusted_rust = pos_def_adjustment(input, 0.99, 1000).unwrap();

    assert_mat_close(
        &adjusted_rust,
        &adjusted_python,
        "PosDef adjustment (scenario 4)",
    );
}

#[test]
fn test_scenario4_cov2corr() {
    let golden = read_golden();
    let s = &golden["scenario4_posdef"];

    let adjusted = json_to_mat(&s["adjusted"]);
    let corr_python = json_to_mat(&s["corr"]);

    let corr_rust = cov2corr(&adjusted);

    assert_mat_close(&corr_rust, &corr_python, "cov2corr (scenario 4)");
}

#[test]
fn test_flatten_rebuild_roundtrip_python() {
    // Verify that our flatten/rebuild Cholesky parameterisation matches
    // Python's by checking that rebuild(flatten(omega)) ≈ omega for
    // a test matrix from the golden outputs.
    let golden = read_golden();
    let s = &golden["scenario2"];
    let omega = json_to_mat(&s["omega_gmm_adj"]);

    // Only test roundtrip if omega is positive definite (required for Cholesky).
    let flat = flatten_out_omega(&omega);
    let rebuilt = rebuild_omega(&flat);

    assert_mat_close(&rebuilt, &omega, "flatten/rebuild roundtrip");
}

#[test]
fn test_nelder_mead_matches_scipy() {
    // Test that our Nelder-Mead can minimise a simple function to the same
    // point as scipy.optimize.minimize.
    // f(x) = sum((x_i - c_i)^2) where c = [1, 2, 3]
    let f = |x: &[f64]| {
        x.iter()
            .enumerate()
            .map(|(i, &v)| (v - (i as f64 + 1.0)).powi(2))
            .sum::<f64>()
    };
    let x0 = vec![0.0, 0.0, 0.0];
    let result = nelder_mead_generic(f, &x0, 0.5, 1e-6, 1e-8, 5000);

    for i in 0..3 {
        assert!(
            (result[i] - (i as f64 + 1.0)).abs() < 1e-3,
            "Nelder-Mead x[{i}] = {}, expected {}",
            result[i],
            i + 1
        );
    }
}
