//! Comprehensive cross-validation against R EValue package golden output.
//!
//! Golden values generated by `tests/gen_r_golden.R` using the real R
//! EValue package (v4.1.4). Run:
//! ```sh
//! Rscript tests/gen_r_golden.R tests/evalue_golden.json
//! ```
//! then:
//! ```sh
//! cargo test -p evalue --test cross_validation
//! ```

use evalue::{
    bias_spec, evalue as ev, multi_bound, multi_evalue, selection,
};
use serde_json::Value;

const TOL: f64 = 1e-4;

fn load_golden() -> Value {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/evalue_golden.json");
    let text = std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!(
            "Failed to read {}: {}. Run `Rscript tests/gen_r_golden.R tests/evalue_golden.json` first.",
            path.display(), e
        )
    });
    serde_json::from_str(&text).expect("Failed to parse golden JSON")
}

/// Extract a numeric field from JSON, handling R's "NA" string.
fn jnum(v: &Value, key: &str) -> Option<f64> {
    let val = &v[key];
    if val.is_null() {
        return None;
    }
    if let Some(s) = val.as_str() {
        if s == "NA" {
            return None;
        }
        return s.parse().ok();
    }
    val.as_f64()
}

// ═══════════════════════════════════════════════════════════════════════
// Simple E-value cross-validation
// ═══════════════════════════════════════════════════════════════════════

#[test]
fn xval_rr_leukemia() {
    let g = load_golden();
    let r = &g["rr_leukemia"];
    let res = ev::evalues_rr(0.80, Some(0.71), Some(0.91), 1.0).unwrap();

    assert!((res.point_evalue().unwrap() - jnum(r, "point_e").unwrap()).abs() < TOL);
    // est < true → upper CI E-value reported
    assert!(
        (res.evalues[2].unwrap() - jnum(r, "upper_e").unwrap()).abs() < TOL,
        "upper E-value mismatch"
    );
}

#[test]
fn xval_rr_point_only() {
    let g = load_golden();
    let r = &g["rr_point_only"];
    let res = ev::evalues_rr(3.5, None, None, 1.0).unwrap();
    assert!((res.point_evalue().unwrap() - jnum(r, "point_e").unwrap()).abs() < TOL);
}

#[test]
fn xval_rr_non_null() {
    let g = load_golden();
    let r = &g["rr_non_null"];
    let res = ev::evalues_rr(2.0, None, None, 1.5).unwrap();
    assert!((res.point_evalue().unwrap() - jnum(r, "point_e").unwrap()).abs() < TOL);
}

#[test]
fn xval_or_common() {
    let g = load_golden();
    let r = &g["or_common"];
    let res = ev::evalues_or(0.86, Some(0.75), Some(0.99), false, 1.0).unwrap();
    assert!((res.point_evalue().unwrap() - jnum(r, "point_e").unwrap()).abs() < TOL);
    assert!((res.rr_values[0].unwrap() - jnum(r, "point_rr").unwrap()).abs() < TOL);
}

#[test]
fn xval_or_rare() {
    let g = load_golden();
    let r = &g["or_rare"];
    let res = ev::evalues_or(3.0, None, None, true, 1.0).unwrap();
    assert!((res.point_evalue().unwrap() - jnum(r, "point_e").unwrap()).abs() < TOL);
}

#[test]
fn xval_hr_common() {
    let g = load_golden();
    let r = &g["hr_common"];
    let res = ev::evalues_hr(0.56, Some(0.46), Some(0.69), false, 1.0).unwrap();
    assert!((res.point_evalue().unwrap() - jnum(r, "point_e").unwrap()).abs() < TOL);
    assert!((res.rr_values[0].unwrap() - jnum(r, "point_rr").unwrap()).abs() < TOL);
}

#[test]
fn xval_hr_rare() {
    let g = load_golden();
    let r = &g["hr_rare"];
    let res = ev::evalues_hr(0.56, Some(0.46), Some(0.69), true, 1.0).unwrap();
    assert!((res.point_evalue().unwrap() - jnum(r, "point_e").unwrap()).abs() < TOL);
}

#[test]
fn xval_md_basic() {
    let g = load_golden();
    let r = &g["md_basic"];
    let res = ev::evalues_md(0.5, Some(0.25), 0.0).unwrap();
    assert!((res.point_evalue().unwrap() - jnum(r, "point_e").unwrap()).abs() < TOL);
    assert!((res.rr_values[0].unwrap() - jnum(r, "point_rr").unwrap()).abs() < TOL);
}

#[test]
fn xval_ols_basic() {
    let g = load_golden();
    let r = &g["ols_basic"];
    let res = ev::evalues_ols(0.3, Some(0.1), 1.0, 1.0, 0.0).unwrap();
    assert!((res.point_evalue().unwrap() - jnum(r, "point_e").unwrap()).abs() < TOL);
    assert!((res.rr_values[0].unwrap() - jnum(r, "point_rr").unwrap()).abs() < TOL);
}

#[test]
fn xval_smoking_twoxtwo() {
    let g = load_golden();
    let r = &g["smoking"];
    let (rr, lower, upper) = ev::two_by_two_rr(397.0, 78557.0, 51.0, 108778.0, 0.05);
    let res = ev::evalues_rr(rr, Some(lower), Some(upper), 1.0).unwrap();
    assert!((res.point_evalue().unwrap() - jnum(r, "point_e").unwrap()).abs() < TOL);
}

#[test]
fn xval_rd_smoking() {
    let g = load_golden();
    let r = &g["rd_smoking"];
    let (est_e, lo_e) = ev::evalues_rd(397.0, 78557.0, 51.0, 108778.0, 0.0, 0.05, 0.0001).unwrap();
    assert!((est_e - jnum(r, "est_evalue").unwrap()).abs() < TOL, "est_e: {est_e}");
    assert!((lo_e - jnum(r, "lower_evalue").unwrap()).abs() < TOL, "lower_e: {lo_e}");
}

// ═══════════════════════════════════════════════════════════════════════
// Multi-bias E-value cross-validation
// ═══════════════════════════════════════════════════════════════════════

#[test]
fn xval_multi_confounding() {
    let g = load_golden();
    let expected = jnum(&g["multi_confounding"], "point_e").unwrap();
    let mb = bias_spec::multi_bias(&[bias_spec::confounding()]).unwrap();
    let res = multi_evalue::multi_evalues_rr(&mb, 3.5, None, None, 1.0).unwrap();
    assert!((res.point_evalue().unwrap() - expected).abs() < TOL);
}

#[test]
fn xval_multi_sel_general() {
    let g = load_golden();
    let expected = jnum(&g["multi_sel_general"], "point_e").unwrap();
    let mb = bias_spec::multi_bias(&[bias_spec::selection(&["general"]).unwrap()]).unwrap();
    let res = multi_evalue::multi_evalues_rr(&mb, 0.5, None, None, 1.0).unwrap();
    assert!((res.point_evalue().unwrap() - expected).abs() < TOL, "got {} expected {expected}", res.point_evalue().unwrap());
}

#[test]
fn xval_multi_sel_selected() {
    let g = load_golden();
    let expected = jnum(&g["multi_sel_selected"], "point_e").unwrap();
    let mb = bias_spec::multi_bias(&[bias_spec::selection(&["selected"]).unwrap()]).unwrap();
    let res = multi_evalue::multi_evalues_rr(&mb, 4.7, None, None, 1.0).unwrap();
    assert!((res.point_evalue().unwrap() - expected).abs() < TOL, "got {} expected {expected}", res.point_evalue().unwrap());
}

#[test]
fn xval_multi_sel_incr() {
    let g = load_golden();
    let expected = jnum(&g["multi_sel_incr"], "point_e").unwrap();
    let mb = bias_spec::multi_bias(&[
        bias_spec::selection(&["general", "increased risk"]).unwrap()
    ]).unwrap();
    let res = multi_evalue::multi_evalues_rr(&mb, 0.8, None, None, 1.0).unwrap();
    assert!((res.point_evalue().unwrap() - expected).abs() < TOL, "got {} expected {expected}", res.point_evalue().unwrap());
}

#[test]
fn xval_multi_sel_su() {
    let g = load_golden();
    let expected = jnum(&g["multi_sel_su"], "point_e").unwrap();
    let mb = bias_spec::multi_bias(&[
        bias_spec::selection(&["general", "S = U"]).unwrap()
    ]).unwrap();
    let res = multi_evalue::multi_evalues_rr(&mb, 5.3, None, None, 1.0).unwrap();
    assert!((res.point_evalue().unwrap() - expected).abs() < TOL, "got {} expected {expected}", res.point_evalue().unwrap());
}

#[test]
fn xval_multi_conf_sel() {
    let g = load_golden();
    let expected = jnum(&g["multi_conf_sel"], "point_e").unwrap();
    let mb = bias_spec::multi_bias(&[
        bias_spec::confounding(),
        bias_spec::selection(&["general"]).unwrap(),
    ]).unwrap();
    let res = multi_evalue::multi_evalues_rr(&mb, 2.5, None, None, 1.0).unwrap();
    assert!((res.point_evalue().unwrap() - expected).abs() < TOL, "got {} expected {expected}", res.point_evalue().unwrap());
}

#[test]
fn xval_multi_conf_sel_misclass() {
    let g = load_golden();
    let expected = jnum(&g["multi_conf_sel_misclass"], "point_e").unwrap();
    let mb = bias_spec::multi_bias(&[
        bias_spec::confounding(),
        bias_spec::selection(&["general"]).unwrap(),
        bias_spec::misclassification("outcome", false, false).unwrap(),
    ]).unwrap();
    let res = multi_evalue::multi_evalues_rr(&mb, 2.5, None, None, 1.0).unwrap();
    assert!((res.point_evalue().unwrap() - expected).abs() < TOL, "got {} expected {expected}", res.point_evalue().unwrap());
}

// ═══════════════════════════════════════════════════════════════════════
// Multi-bias bound cross-validation
// ═══════════════════════════════════════════════════════════════════════

#[test]
fn xval_bound_confounding() {
    let g = load_golden();
    let expected = jnum(&g["bound_confounding"], "").unwrap_or_else(|| g["bound_confounding"].as_f64().unwrap());
    let mb = bias_spec::multi_bias(&[bias_spec::confounding()]).unwrap();
    let mut params = std::collections::HashMap::new();
    params.insert("RRAUc".into(), 2.0);
    params.insert("RRUcY".into(), 2.0);
    let b = multi_bound::multi_bound(&mb, &params).unwrap();
    assert!((b - expected).abs() < TOL, "got {b}, expected {expected}");
}

#[test]
fn xval_bound_conf_sel_incr() {
    let g = load_golden();
    let expected = g["bound_conf_sel_incr"].as_f64().unwrap();
    let mb = bias_spec::multi_bias(&[
        bias_spec::confounding(),
        bias_spec::selection(&["general", "increased risk"]).unwrap(),
    ]).unwrap();
    let mut params = std::collections::HashMap::new();
    params.insert("RRAUc".into(), 2.0);
    params.insert("RRUcY".into(), 2.0);
    params.insert("RRUsYA1".into(), 3.0);
    params.insert("RRSUsA1".into(), 3.0);
    let b = multi_bound::multi_bound(&mb, &params).unwrap();
    assert!((b - expected).abs() < TOL, "got {b}, expected {expected}");
}

// ═══════════════════════════════════════════════════════════════════════
// Selection bias E-value (svalues) cross-validation
// ═══════════════════════════════════════════════════════════════════════

#[test]
fn xval_svalues_zika() {
    let g = load_golden();
    let expected = jnum(&g["svalues_zika"], "point_e").unwrap();
    let res = selection::svalues_rr(73.1, Some(13.0), None, 1.0, false, false, false, false).unwrap();
    assert!((res.point_evalue().unwrap() - expected).abs() < TOL, "got {} expected {expected}", res.point_evalue().unwrap());
}

#[test]
fn xval_svalues_obesity() {
    let g = load_golden();
    let expected = jnum(&g["svalues_obesity"], "point_e").unwrap();
    let res = selection::svalues_rr(1.50, Some(1.22), None, 1.0, true, false, false, false).unwrap();
    assert!((res.point_evalue().unwrap() - expected).abs() < TOL, "got {} expected {expected}", res.point_evalue().unwrap());
}

#[test]
fn xval_svalues_endometrial() {
    let g = load_golden();
    let expected = jnum(&g["svalues_endometrial"], "point_e").unwrap();
    let res = selection::svalues_rr(2.30, None, None, 11.98, false, true, true, false).unwrap();
    assert!((res.point_evalue().unwrap() - expected).abs() < TOL, "got {} expected {expected}", res.point_evalue().unwrap());
}
