//! Cross-validation of the Rust MRlap port against base-R golden outputs.
//!
//! The golden fixtures are generated by `tests/fixtures-gen/gen_golden.R` — a
//! faithful, self-contained base-R transcription of MRlap's tidy / harmonise /
//! distance-pruning / get_correction maths (the LDSC and IVW stages are
//! validated separately in the `ldsc` and `mr` crates). The R script fixes the
//! LDSC outputs (λ, h²) as shared inputs, so the correction comparison is
//! independent of the LDSC regression.
//!
//! Deterministic quantities (standardised effects, harmonised table, pruned IV
//! set, π, σ², corrected point estimate) are compared exactly. The bootstrap SE
//! and covariance are Monte-Carlo estimates from *different* RNG streams
//! (R's Mersenne Twister vs ChaCha8), so they agree within a relative tolerance
//! reflecting sampling noise (validated at ~10 % relative, asserted at 20 %).

use std::collections::HashSet;
use std::path::Path;

use mrlap::{
    correction::{CorrectionInput, correct},
    harmonise::harmonise,
    input::{RawGwasRow, tidy},
    pruning::{PruneMode, select_instruments},
};

const GOLDEN: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures/golden");

fn gold(name: &str) -> String {
    std::fs::read_to_string(Path::new(GOLDEN).join(name))
        .unwrap_or_else(|e| panic!("read {name}: {e}"))
}

/// Parse a header-keyed TSV into a Vec of row-records (each a Vec<String>).
fn read_tsv(name: &str) -> (Vec<String>, Vec<Vec<String>>) {
    let s = gold(name);
    let mut lines = s.lines();
    let header: Vec<String> = lines
        .next()
        .unwrap()
        .split('\t')
        .map(str::to_owned)
        .collect();
    let rows: Vec<Vec<String>> = lines
        .filter(|l| !l.trim().is_empty())
        .map(|l| l.split('\t').map(str::to_owned).collect())
        .collect();
    (header, rows)
}

fn col<'a>(header: &[String], row: &'a [String], name: &str) -> &'a str {
    let i = header
        .iter()
        .position(|h| h == name)
        .unwrap_or_else(|| panic!("col {name}"));
    &row[i]
}

fn f(row: &[String], header: &[String], name: &str) -> f64 {
    col(header, row, name).parse().unwrap()
}

fn approx(a: f64, b: f64, rel: f64, abs: f64) -> bool {
    if a.is_nan() && b.is_nan() {
        return true;
    }
    (a - b).abs() <= rel * b.abs().max(1e-12) + abs
}

/// Load a raw GWAS TSV (rsid, chr, pos, alt, ref, Z, N) into RawGwasRows.
fn load_gwas(name: &str) -> Vec<RawGwasRow> {
    let (h, rows) = read_tsv(name);
    rows.iter()
        .map(|r| RawGwasRow {
            rsid: col(&h, r, "rsid").to_string(),
            chr: Some(col(&h, r, "chr").parse().unwrap()),
            pos: Some(col(&h, r, "pos").parse().unwrap()),
            alt: col(&h, r, "alt").to_string(),
            ref_allele: col(&h, r, "ref").to_string(),
            z: Some(col(&h, r, "Z").parse().unwrap()),
            n: col(&h, r, "N").parse().unwrap(),
            ..Default::default()
        })
        .collect()
}

#[test]
fn tidy_matches_r() {
    let exp = load_gwas("gwas_exp.tsv");
    let tidy_rows = tidy(&exp, true).unwrap();
    let (h, golden) = read_tsv("tidy.tsv");
    assert_eq!(tidy_rows.len(), golden.len(), "row count");
    // index by rsid
    use std::collections::HashMap;
    let map: HashMap<&str, &Vec<String>> = golden
        .iter()
        .map(|r| (col(&h, r, "rsid"), r))
        .collect();
    for t in &tidy_rows {
        let g = map.get(t.rsid.as_str()).unwrap();
        assert!(
            approx(t.std_beta, f(g, &h, "std_beta"), 1e-9, 1e-12),
            "std_beta {}",
            t.rsid
        );
        assert!(
            approx(t.std_se, f(g, &h, "std_SE"), 1e-9, 1e-12),
            "std_SE {}",
            t.rsid
        );
        assert!(approx(t.p, f(g, &h, "p"), 1e-6, 1e-12), "p {}", t.rsid);
        assert!(approx(t.z, f(g, &h, "Z"), 1e-9, 1e-12), "Z {}", t.rsid);
    }
}

#[test]
fn harmonise_matches_r() {
    let exp = tidy(&load_gwas("gwas_exp.tsv"), true).unwrap();
    let out = tidy(&load_gwas("gwas_out.tsv"), true).unwrap();
    let harm = harmonise(&exp, &out);
    let (h, golden) = read_tsv("harmonised.tsv");
    use std::collections::HashMap;
    let map: HashMap<&str, &Vec<String>> = golden
        .iter()
        .map(|r| (col(&h, r, "rsid"), r))
        .collect();
    assert_eq!(harm.len(), golden.len(), "harmonised row count");
    for row in &harm {
        let g = map.get(row.rsid.as_str()).unwrap();
        assert!(approx(
            row.std_beta_exp,
            f(g, &h, "std_beta.exp"),
            1e-9,
            1e-12
        ));
        assert!(
            approx(row.std_beta_out, f(g, &h, "std_beta.out"), 1e-9, 1e-12),
            "std_beta.out mismatch {}: rust={} r={}",
            row.rsid,
            row.std_beta_out,
            f(g, &h, "std_beta.out")
        );
        assert!(approx(row.p_exp, f(g, &h, "p.exp"), 1e-6, 1e-12));
    }
}

#[test]
fn pruning_and_ivw_match_r() {
    let exp = tidy(&load_gwas("gwas_exp.tsv"), true).unwrap();
    let out = tidy(&load_gwas("gwas_out.tsv"), true).unwrap();
    let harm = harmonise(&exp, &out);

    let (ivs, _pruned) = select_instruments(
        &harm,
        &PruneMode::Distance {
            mr_threshold: 5e-8,
            mr_reverse: None,
            pruning_dist_kb: 500.0,
        },
    )
    .unwrap();

    // Pruned rsid set must match R exactly.
    let (ph, pruned_golden) = read_tsv("pruned.tsv");
    let golden_rsids: HashSet<&str> = pruned_golden.iter().map(|r| col(&ph, r, "rsid")).collect();
    let rust_rsids: HashSet<&str> = ivs.iter().map(|i| i.rsid.as_str()).collect();
    assert_eq!(rust_rsids, golden_rsids, "pruned IV set differs from R");

    // IVW point estimate + SE.
    let mr = mrlap::mr_runner::run_mr(&ivs);
    let (ih, irow) = read_tsv("ivw.tsv");
    let g = &irow[0];
    assert!(
        approx(mr.alpha_obs, f(g, &ih, "alpha_obs"), 1e-6, 1e-8),
        "alpha_obs: rust={} r={}",
        mr.alpha_obs,
        f(g, &ih, "alpha_obs")
    );
    assert!(
        approx(mr.alpha_obs_se, f(g, &ih, "alpha_obs_se"), 1e-6, 1e-8),
        "alpha_obs_se: rust={} r={}",
        mr.alpha_obs_se,
        f(g, &ih, "alpha_obs_se")
    );
}

#[test]
fn correction_matches_r() {
    let exp = tidy(&load_gwas("gwas_exp.tsv"), true).unwrap();
    let out = tidy(&load_gwas("gwas_out.tsv"), true).unwrap();
    let harm = harmonise(&exp, &out);
    let (ivs, _) = select_instruments(
        &harm,
        &PruneMode::Distance {
            mr_threshold: 5e-8,
            mr_reverse: None,
            pruning_dist_kb: 500.0,
        },
    )
    .unwrap();
    let mr = mrlap::mr_runner::run_mr(&ivs);

    let (ch, crow) = read_tsv("correction.tsv");
    let g = &crow[0];
    let iv_beta: Vec<f64> = ivs.iter().map(|i| i.std_beta_exp).collect();
    let iv_se: Vec<f64> = ivs.iter().map(|i| i.std_se_exp).collect();

    let input = CorrectionInput {
        iv_std_beta_exp: &iv_beta,
        iv_std_se_exp: &iv_se,
        lambda: f(g, &ch, "lambda"),
        lambda_se: f(g, &ch, "lambda_se"),
        h2_ldsc: f(g, &ch, "h2_LDSC"),
        h2_ldsc_se: f(g, &ch, "h2_LDSC_se"),
        alpha_obs: mr.alpha_obs,
        alpha_obs_se: mr.alpha_obs_se,
        n_exp: mr.n_exp,
        n_out: mr.n_out,
        mr_threshold: 5e-8,
    };
    // Rust seed 42 mirrors R's set.seed(42); streams differ so only the
    // deterministic quantities match exactly.
    let res = correct(&input, 42).unwrap();

    // Deterministic — tight tolerance.
    assert!(
        approx(res.pi_x, f(g, &ch, "pi_x"), 1e-4, 1e-10),
        "pi_x: rust={} r={}",
        res.pi_x,
        f(g, &ch, "pi_x")
    );
    assert!(
        approx(res.sigma2_x, f(g, &ch, "sigma2_x"), 1e-4, 1e-12),
        "sigma2_x: rust={} r={}",
        res.sigma2_x,
        f(g, &ch, "sigma2_x")
    );
    assert!(
        approx(
            res.alpha_corrected,
            f(g, &ch, "alpha_corrected"),
            1e-4,
            1e-10
        ),
        "alpha_corrected: rust={} r={}",
        res.alpha_corrected,
        f(g, &ch, "alpha_corrected")
    );

    // Monte-Carlo — relative tolerance (different RNG streams).
    let r_se = f(g, &ch, "alpha_corrected_se");
    assert!(
        approx(res.alpha_corrected_se, r_se, 0.20, 1e-4),
        "alpha_corrected_se: rust={} r={} (diff {:.2}%)",
        res.alpha_corrected_se,
        r_se,
        (res.alpha_corrected_se - r_se).abs() / r_se * 100.0
    );
    let r_cov = f(g, &ch, "cov_obs_corrected");
    assert!(
        r_cov.abs() < 1e-8 || approx(res.cov_obs_corrected, r_cov, 0.35, 1e-5),
        "cov_obs_corrected: rust={} r={}",
        res.cov_obs_corrected,
        r_cov
    );

    // Both should detect a significant obs-vs-corrected difference (same sign).
    let r_test = f(g, &ch, "test_diff");
    assert_eq!(
        res.test_diff.is_sign_negative(),
        r_test.is_sign_negative(),
        "test_diff sign: rust={} r={}",
        res.test_diff,
        r_test
    );
}
