//! Cross-validation of the Rust LAVA port against the original R LAVA golden
//! outputs (generated by `tests/fixtures-gen/gen_golden.R`).
//!
//! These tests load the vignette fixtures (PLINK + sumstats), run the Rust
//! pipeline, and compare to the R golden TSVs. Deterministic quantities
//! (K, omega, sigma, h², point estimates, univariate p) must match to ~1e-4;
//! simulation quantities (bivariate / multireg / pcor p-values and CIs) match
//! to Monte-Carlo tolerance.
//!
//! Heavy (loads ~150k SNPs × 7 phenotypes + 42 MB PLINK bed): run with
//!   cargo test -p lava --test cross_validation -- --ignored --nocapture

use std::collections::HashMap;
use std::path::{Path, PathBuf};

use lava::analysis::{run_bivar, run_multireg, run_pcor, run_univ};
use lava::input::{process_input, read_loci};
use lava::locus::{process_locus, LocusOptions};

const FIXTURES: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures");
const GOLDEN: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures/golden");

fn fx(name: &str) -> PathBuf {
    Path::new(FIXTURES).join(name)
}
fn gold(name: &str) -> PathBuf {
    Path::new(GOLDEN).join(name)
}

/// Read a header-keyed TSV into a vector of row maps (string values).
fn read_tsv(path: &Path) -> Vec<HashMap<String, String>> {
    let s = std::fs::read_to_string(path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    let mut lines = s.lines();
    let header: Vec<String> = lines
        .next()
        .unwrap()
        .split_whitespace()
        .map(|x| x.to_string())
        .collect();
    lines
        .filter(|l| !l.trim().is_empty())
        .map(|l| {
            let parts: Vec<&str> = l.split_whitespace().collect();
            header
                .iter()
                .zip(parts.iter())
                .map(|(h, v)| (h.clone(), v.to_string()))
                .collect()
        })
        .collect()
}

fn fval(m: &HashMap<String, String>, k: &str) -> f64 {
    m.get(k).map(|v| v.parse::<f64>().unwrap_or(f64::NAN)).unwrap_or(f64::NAN)
}

fn close(a: f64, b: f64, rel: f64, abs: f64) -> bool {
    if a.is_nan() && b.is_nan() {
        return true;
    }
    if a.is_nan() || b.is_nan() {
        return false;
    }
    (a - b).abs() <= rel * b.abs().max(1e-12) + abs
}

/// Build the processed input (all 7 phenotypes), matching `gen_golden.R`.
fn make_input() -> lava::input::Input {
    process_input(
        &fx("input.info.txt"),
        Some(&fx("sample.overlap.txt")),
        &fx("g1000_test"),
        None,
        Some(FIXTURES),
    )
    .expect("process_input failed")
}

#[test]
#[ignore]
fn locus_266_deterministic() {
    let input = make_input();
    let loci = read_loci(&fx("test.loci")).expect("read_loci");
    let l266 = loci.iter().find(|l| l.loc == "266").unwrap();
    let loc = process_locus(
        l266,
        &input,
        Some(&["depression".to_string(), "neuro".to_string(), "bmi".to_string()]),
        &LocusOptions::default(),
    )
    .expect("process_locus 266")
    .expect("locus 266 not analysable");

    let golden = read_tsv(&gold("locus_266_intermediate.tsv"));
    assert_eq!(loc.k, fval(&golden[0], "K") as usize, "K mismatch");
    assert_eq!(loc.n_snps, fval(&golden[0], "n.snps") as usize, "n.snps mismatch");

    // phenos order
    let gphenos: Vec<&str> = golden.iter().map(|r| r["phen"].as_str()).collect();
    assert_eq!(loc.phenos, gphenos.iter().map(|s| s.to_string()).collect::<Vec<_>>());

    let phenos = ["depression", "neuro", "bmi"];
    let univ = run_univ(&loc.params(), None, false, true);
    for (i, ph) in phenos.iter().enumerate() {
        let g = golden.iter().find(|r| r["phen"] == *ph).unwrap();
        let gi = loc.phenos.iter().position(|p| p == *ph).unwrap();
        println!("{ph}: h2.obs rust={} R={} | N rust={} R={} | sigma rust={} R={} | omega rust={} R={}",
            loc.h2_obs[gi], fval(g, "h2.obs"),
            loc.n[gi], fval(g, "N"),
            loc.sigma[(gi,gi)], fval(g, "sigma_diag"),
            loc.omega[(gi,gi)], fval(g, "omega_diag"));
        assert!(close(loc.n[gi], fval(g, "N"), 1e-6, 1e-6), "N {} mismatch", ph);
        assert!(close(loc.sigma[(gi, gi)], fval(g, "sigma_diag"), 1e-4, 1e-9), "sigma {} mismatch", ph);
        assert!(close(loc.omega[(gi, gi)], fval(g, "omega_diag"), 1e-4, 1e-9), "omega {} mismatch", ph);
        assert!(close(univ[i].p, fval(g, "univ_p"), 1e-4, 1e-9), "univ p {} mismatch", ph);
        let _ = i;
    }
    println!("locus_266 deterministic OK (K={}, n.snps={})", loc.k, loc.n_snps);
}

#[test]
#[ignore]
fn locus_266_omega_matrix() {
    let input = make_input();
    let loci = read_loci(&fx("test.loci")).expect("read_loci");
    let l266 = loci.iter().find(|l| l.loc == "266").unwrap();
    let loc = process_locus(
        l266,
        &input,
        Some(&["depression".to_string(), "neuro".to_string(), "bmi".to_string()]),
        &LocusOptions::default(),
    )
    .unwrap()
    .unwrap();

    let omega_rows: Vec<Vec<f64>> = std::fs::read_to_string(gold("locus_266_omega.tsv"))
        .unwrap()
        .lines()
        .map(|l| l.split_whitespace().map(|x| x.parse::<f64>().unwrap()).collect())
        .collect();
    let p = loc.p();
    let mut max_err = 0.0f64;
    for i in 0..p {
        for j in 0..p {
            let e = (loc.omega[(i, j)] - omega_rows[i][j]).abs();
            max_err = max_err.max(e);
        }
    }
    println!("locus_266 omega max abs err = {:.3e}", max_err);
    assert!(max_err < 1e-6, "omega matrix mismatch (max err {max_err:.3e})");
}

#[test]
#[ignore]
fn locus_266_bivar() {
    let input = make_input();
    let loci = read_loci(&fx("test.loci")).expect("read_loci");
    let l266 = loci.iter().find(|l| l.loc == "266").unwrap();
    let loc = process_locus(
        l266,
        &input,
        Some(&["depression".to_string(), "neuro".to_string(), "bmi".to_string()]),
        &LocusOptions::default(),
    )
    .unwrap()
    .unwrap();

    let mut rng = lava::rng(lava::DEFAULT_RNG_SEED);
    let bivar = run_bivar(&loc.params(), None, None, None, true, true, 1.25, true, &mut rng);
    let golden = read_tsv(&gold("locus_266_bivar.tsv"));
    for row in &bivar {
        let g = golden.iter().find(|r| r["phen1"] == row.phen1 && r["phen2"] == row.phen2).unwrap();
        println!("{} ~ {}: rho rust={:.4} R={:.4} | r2 rust={:.4} R={:.4} | p rust={:.4} R={:.4}",
            row.phen1, row.phen2, row.rho, fval(g, "rho"), row.r2, fval(g, "r2"), row.p, fval(g, "p"));
        // deterministic point estimates (tight)
        assert!(close(row.rho, fval(g, "rho"), 1e-4, 1e-9), "rho {}~{}", row.phen1, row.phen2);
        assert!(close(row.r2, fval(g, "r2"), 1e-4, 1e-9), "r2 {}~{}", row.phen1, row.phen2);
    }
    println!("locus_266 bivar point estimates OK");
}

#[test]
#[ignore]
fn all_loci_deterministic_sweep() {
    let input = make_input();
    let loci = read_loci(&fx("test.loci")).expect("read_loci");
    let golden = read_tsv(&gold("all_loci_deterministic.tsv"));
    let mut checked = 0usize;
    let mut k_mismatch = 0usize;
    for ld in &loci {
        let loc = match process_locus(ld, &input, None, &LocusOptions::default()) {
            Ok(Some(l)) => l,
            _ => continue,
        };
        for (gi, ph) in loc.phenos.iter().enumerate() {
            let g = match golden.iter().find(|r| r["locus"] == ld.loc && r["phen"] == *ph) {
                Some(r) => r,
                None => continue,
            };
            let gk = fval(g, "K") as usize;
            if loc.k != gk {
                k_mismatch += 1;
                println!("K mismatch locus {} rust={} R={}", ld.loc, loc.k, gk);
                continue;
            }
            if !close(loc.omega[(gi, gi)], fval(g, "omega_diag"), 1e-3, 1e-9) {
                println!("  omega diag locus {} ph {} rust={:.6e} R={:.6e}", ld.loc, ph, loc.omega[(gi,gi)], fval(g,"omega_diag"));
            }
            assert!(close(loc.sigma[(gi, gi)], fval(g, "sigma_diag"), 1e-3, 1e-9),
                "sigma diag locus {} ph {}", ld.loc, ph);
            checked += 1;
        }
    }
    println!("all-loci sweep: checked {} (phenotype,locus) pairs; K mismatches: {}", checked, k_mismatch);
    assert!(checked > 100, "too few pairs checked ({checked})");
}

#[test]
#[ignore]
fn locus_964_multireg_pcor() {
    let input = make_input();
    let loci = read_loci(&fx("test.loci")).expect("read_loci");
    let l964 = loci.iter().find(|l| l.loc == "964").unwrap();
    let loc = process_locus(
        l964,
        &input,
        Some(&[
            "hypothyroidism".to_string(),
            "asthma".to_string(),
            "rheuma".to_string(),
            "diabetes".to_string(),
        ]),
        &LocusOptions::default(),
    )
    .unwrap()
    .unwrap();

    let mut rng = lava::rng(lava::DEFAULT_RNG_SEED);
    let mr = run_multireg(&loc.params(), "hypothyroidism", None, None, true, true, true, 1.5, &mut rng);
    let mr_golden = read_tsv(&gold("locus_964_multireg.tsv"));
    let mr_rows = mr.first().unwrap();
    for r in mr_rows {
        let g = mr_golden.iter().find(|x| x["predictors"] == r.predictors).unwrap();
        println!("multireg {}: gamma rust={:.4} R={:.4} | r2 rust={:.4} R={:.4}",
            r.predictors, r.gamma, fval(g, "gamma"), r.r2, fval(g, "r2"));
        assert!(close(r.gamma, fval(g, "gamma"), 1e-4, 1e-9), "gamma {}", r.predictors);
        assert!(close(r.r2, fval(g, "r2"), 1e-4, 1e-9), "r2 {}", r.predictors);
    }

    let pc = run_pcor(&loc.params(), ("hypothyroidism", "diabetes"), Some(&["asthma".to_string()]), None, true, true, 0.95, 1.25, &mut rng);
    let pcg = &read_tsv(&gold("locus_964_pcor.tsv"))[0];
    println!("pcor: rust={:.4} R={:.4}", pc.pcor, fval(pcg, "pcor"));
    assert!(close(pc.pcor, fval(pcg, "pcor"), 1e-4, 1e-9), "pcor point estimate");
    println!("locus_964 multireg + pcor point estimates OK");
}
