//! Strict cross-validation of the Rust MR-PRESSO port against the reference R
//! package (MRPRESSO v1.0), for a shared `set.seed`.
//!
//! Golden values are generated by `tests/gen_r_golden.R`:
//! ```sh
//! Rscript tests/gen_r_golden.R tests/mrpresso_golden.json
//! cargo test -p mrpresso --test cross_validation
//! ```
//!
//! Because the port reproduces R's exact Mersenne-Twister + inversion-`rnorm`,
//! the empirical p-values (integer counts over the null distribution) must
//! match R **exactly**, not just within tolerance.

use mrpresso::{MrpressoInput, mr_presso};
use serde_json::Value;

const TOL: f64 = 1e-9;

fn load_golden() -> Value {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/mrpresso_golden.json");
    let text = std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!(
            "Failed to read {}: {}. Run `Rscript tests/gen_r_golden.R tests/mrpresso_golden.json` first.",
            path.display(),
            e
        )
    });
    serde_json::from_str(&text).expect("Failed to parse golden JSON")
}

/// Read the SummaryStats fixture (reconstructed from the R `SummaryStats.rda`
/// via the R golden script's `n`; the values are embedded below).
fn summary_stats() -> (Vec<Vec<f64>>, Vec<Vec<f64>>, Vec<f64>, Vec<f64>) {
    // Columns: E1_effect E1_se E2_effect E2_se Y_effect Y_se (50 rows)
    let (e1, e1_se, e2, e2_se, y, y_se) = summary_stats_raw();
    let beta_exposure = vec![e1, e2];
    let sd_exposure = vec![e1_se, e2_se];
    (beta_exposure, sd_exposure, y, y_se)
}

fn summary_stats_raw() -> (Vec<f64>, Vec<f64>, Vec<f64>, Vec<f64>, Vec<f64>, Vec<f64>) {
    let data = include_str!("summary_stats.csv");
    let mut e1 = Vec::new();
    let mut e1_se = Vec::new();
    let mut e2 = Vec::new();
    let mut e2_se = Vec::new();
    let mut y = Vec::new();
    let mut y_se = Vec::new();
    for line in data.lines() {
        let line = line.trim();
        if line.is_empty() {
            continue;
        }
        // Columns: E1_effect E1_se E1_pval E2_effect E2_se E2_pval Y_effect Y_se Y_pval
        let f: Vec<f64> = line.split(',').map(|s| s.parse().unwrap()).collect();
        e1.push(f[0]);
        e1_se.push(f[1]);
        e2.push(f[3]);
        e2_se.push(f[4]);
        y.push(f[6]);
        y_se.push(f[7]);
    }
    (e1, e1_se, e2, e2_se, y, y_se)
}

/// Build an input from the SummaryStats fixture, selecting exposures.
fn input_for(exposure_indices: &[usize], seed: u32) -> MrpressoInput {
    let (beta_exposure, sd_exposure, y, y_se) = summary_stats();
    MrpressoInput {
        beta_outcome: y.clone(),
        beta_exposure: exposure_indices
            .iter()
            .map(|&i| beta_exposure[i].clone())
            .collect(),
        sd_outcome: y_se.clone(),
        sd_exposure: exposure_indices
            .iter()
            .map(|&i| sd_exposure[i].clone())
            .collect(),
        outlier_test: true,
        distortion_test: true,
        signif_threshold: 0.05,
        nb_distribution: 1000,
        seed,
        row_labels: None,
    }
}

fn num(v: &Value) -> Option<f64> {
    if let Some(x) = v.as_f64() {
        Some(x)
    } else if let Some(s) = v.as_str() {
        if s == "NA" || s == "<NA>" {
            None
        } else {
            s.parse().ok()
        }
    } else {
        None
    }
}

/// Read a numeric field that may be a scalar or an array (jsonlite unboxes
/// single-element vectors).
fn num_vec(v: &Value) -> Vec<f64> {
    match v.as_array() {
        Some(a) => a.iter().map(|x| num_or_nan(x)).collect(),
        None => vec![num_or_nan(v)],
    }
}

/// Numeric value, mapping R's `NA` (and missing) to `NaN`.
fn num_or_nan(v: &Value) -> f64 {
    num(v).unwrap_or(f64::NAN)
}

fn close(a: f64, b: f64, tol: f64) -> bool {
    (a.is_nan() && b.is_nan()) || (a - b).abs() <= tol
}

/// Compare the deterministic core + exact p-values for one scenario.
fn check_scenario(key: &str, input: MrpressoInput) {
    let g = &load_golden()[key];
    let out = mr_presso(&input).expect("mr_presso should succeed");

    // ── Global test ──
    let g_rss = num(&g["global"]["RSSobs"]).unwrap();
    assert!(
        close(out.global.rss_obs, g_rss, 1e-6),
        "[{key}] global RSSobs: Rust={} R={g_rss}",
        out.global.rss_obs
    );
    let g_p = num(&g["global"]["Pvalue"]).unwrap();
    assert!(
        (out.global.pvalue - g_p).abs() < 1e-12,
        "[{key}] global Pvalue: Rust={} R={g_p}",
        out.global.pvalue
    );

    // ── Main MR results (raw + outlier-corrected) ──
    let gm = &g["main_mr"];
    let g_est: Vec<f64> = num_vec(&gm["estimate"]);
    let g_sd: Vec<f64> = num_vec(&gm["sd"]);
    let g_t: Vec<f64> = num_vec(&gm["t_stat"]);
    let g_pv: Vec<f64> = num_vec(&gm["pvalue"]);
    assert_eq!(
        out.main_mr.len(),
        g_est.len(),
        "[{key}] main_mr row count: Rust={} R={}",
        out.main_mr.len(),
        g_est.len()
    );
    for (i, row) in out.main_mr.iter().enumerate() {
        assert!(
            close(row.causal_estimate, g_est[i], TOL),
            "[{key}] main_mr[{i}] estimate: Rust={} R={}",
            row.causal_estimate,
            g_est[i]
        );
        assert!(
            close(row.sd, g_sd[i], TOL),
            "[{key}] main_mr[{i}] sd: Rust={} R={}",
            row.sd,
            g_sd[i]
        );
        assert!(
            close(row.t_stat, g_t[i], 1e-6),
            "[{key}] main_mr[{i}] t-stat: Rust={} R={}",
            row.t_stat,
            g_t[i]
        );
        assert!(
            close(row.p_value, g_pv[i], 1e-9),
            "[{key}] main_mr[{i}] p-value: Rust={} R={}",
            row.p_value,
            g_pv[i]
        );
    }

    // ── Outlier test ──
    match (&g["outlier"], &out.outlier) {
        (Value::Null, None) => {}
        (Value::Null, Some(_)) => panic!("[{key}] Rust produced outliers but R did not"),
        (_, None) => panic!("[{key}] R produced outliers but Rust did not"),
        (_, Some(rows)) => {
            let g_rss: Vec<f64> = num_vec(&g["outlier"]["rss"]);
            let g_pv: Vec<f64> = num_vec(&g["outlier"]["pvalue"]);
            assert_eq!(rows.len(), g_rss.len(), "[{key}] outlier row count");
            for (i, row) in rows.iter().enumerate() {
                assert!(
                    close(row.rss_obs, g_rss[i], 1e-6),
                    "[{key}] outlier[{i}] rss: Rust={} R={}",
                    row.rss_obs,
                    g_rss[i]
                );
                assert!(
                    close(row.pvalue, g_pv[i], 1e-12),
                    "[{key}] outlier[{i}] pvalue: Rust={} R={}",
                    row.pvalue,
                    g_pv[i]
                );
            }
            // Significant outliers must match exactly (row indices).
            let g_sig: Vec<usize> = g["outlier"]["sig"]
                .as_array()
                .unwrap()
                .iter()
                .map(|v| v.as_u64().unwrap() as usize)
                .collect();
            let rust_sig: Vec<usize> = rows
                .iter()
                .filter(|r| r.pvalue <= 0.05)
                .map(|r| r.index)
                .collect();
            assert_eq!(rust_sig, g_sig, "[{key}] significant outlier indices");
        }
    }

    // ── Distortion test ──
    match (&g["distortion"], &out.distortion) {
        (Value::Null, None) => {}
        (Value::Null, Some(_)) => panic!("[{key}] Rust produced distortion but R did not"),
        (_, None) => panic!("[{key}] R produced distortion but Rust did not"),
        (_, Some(dt)) => {
            let g_coef: Vec<f64> = num_vec(&g["distortion"]["coefficient"]);
            assert_eq!(
                dt.coefficient.len(),
                g_coef.len(),
                "[{key}] distortion coef count"
            );
            for (i, c) in dt.coefficient.iter().enumerate() {
                assert!(
                    close(*c, g_coef[i], 1e-6),
                    "[{key}] distortion coef[{i}]: Rust={c} R={}",
                    g_coef[i]
                );
            }
            let g_p = num(&g["distortion"]["pvalue"]).unwrap();
            assert!(
                (dt.pvalue.unwrap() - g_p).abs() < 1e-12,
                "[{key}] distortion pvalue: Rust={} R={g_p}",
                dt.pvalue.unwrap()
            );
            let g_ind: Vec<usize> = g["distortion"]["indices"]
                .as_array()
                .unwrap()
                .iter()
                .map(|v| v.as_u64().unwrap() as usize)
                .collect();
            assert_eq!(
                dt.outlier_indices, g_ind,
                "[{key}] distortion outlier indices"
            );
        }
    }
}

#[test]
fn xval_single_exposure() {
    check_scenario("single", input_for(&[0], 123));
}

#[test]
fn xval_multi_exposure() {
    check_scenario("multi", input_for(&[0, 1], 123));
}

#[test]
fn xval_single_other_seed() {
    check_scenario("single_other_seed", input_for(&[0], 7));
}

#[test]
fn xval_single_no_outlier() {
    // outlier test runs but distortion test disabled → outlier-corrected MR is NA.
    let mut input = input_for(&[0], 123);
    input.distortion_test = false;
    check_scenario("single_no_outlier", input);
}

#[test]
fn xval_global_only() {
    // neither outlier nor distortion test → only the global test is reported.
    let mut input = input_for(&[0], 42);
    input.outlier_test = false;
    input.distortion_test = false;
    check_scenario("global_only", input);
}
