//! Cross-validation of the Rust BKMR port against the reference R `bkmr`
//! package (v0.2.2.9000).
//!
//! Each test loads `bkmr_golden.json` generated by `gen_r_golden.R` and
//! compares every MCMC chain value (beta, lambda, sigsq.eps, r, delta,
//! acceptance indicators, move types) against R, using identical `set.seed`.
//!
//! The Rust port reproduces R's RNG stream (MT19937 + inversion rnorm +
//! Ahrens–Dieter rexp/rgamma + truncnorm rejection) bit-exactly. The
//! linear-algebra (Cholesky, inverse) uses `faer`, which agrees with R's
//! LAPACK to ~1e-15. Transcendental functions (lgamma, pnorm) use `statrs`
//! and may differ from Rmath by ~1e-12, so over 100 iterations an acceptance
//! decision may rarely flip. Tolerances are set accordingly.
//!
//! Regenerate the fixture with (r45 conda env):
//! ```sh
//! export R_HOME=$HOME/miniconda3/envs/r45/lib/R
//! export PATH=$HOME/miniconda3/envs/r45/bin:$PATH
//! export LD_LIBRARY_PATH=$HOME/miniconda3/envs/r45/lib:$LD_LIBRARY_PATH
//! Rscript tests/gen_r_golden.R tests/bkmr_golden.json
//! ```

use bkmr::{ControlParams, KmbayesOptions, RMethod, RPrior, Rng, StartingValues, kmbayes, sim_data};
use serde_json::Value;

// Tolerance for MCMC chain values: the port reproduces R's RNG stream
// bit-exactly, and faer's Cholesky agrees with R's LAPACK to ~1e-15.
// Transcendental functions (lgamma, pnorm) differ by ~1e-12, so a few ULPs
// of drift may accumulate in the chain. 1e-9 catches real bugs while
// accepting harmless float association-order differences.
const TOL_CHAIN: f64 = 1e-9;

fn golden_path() -> std::path::PathBuf {
    std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/bkmr_golden.json")
}

fn load_golden() -> Value {
    let path = golden_path();
    let text = std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!(
            "missing fixture {}: {e}\nrun: Rscript tests/gen_r_golden.R tests/bkmr_golden.json",
            path.display()
        )
    });
    serde_json::from_str(&text).expect("fixture is valid JSON")
}

fn vec_f64(v: &Value) -> Vec<f64> {
    v.as_array().unwrap().iter().map(|x| x.as_f64().unwrap()).collect()
}

fn opt_vec_f64(v: &Value) -> Vec<f64> {
    match v.as_array() {
        Some(a) => a.iter().map(|x| x.as_f64().unwrap()).collect(),
        None => Vec::new(),
    }
}

struct ChainCmp {
    max_beta: f64,
    max_lambda: f64,
    max_sigsq: f64,
    max_r: f64,
    max_delta: f64,
    n_accept_mismatch: usize,
}

fn compare_chain(golden: &Value, fit: &bkmr::BkmrFit, n: usize, m: usize, k: usize) -> ChainCmp {
    let g_beta = vec_f64(&golden["beta"]);
    let g_lambda = vec_f64(&golden["lambda"]);
    let g_sigsq = vec_f64(&golden["sigsq_eps"]);
    let g_r = vec_f64(&golden["r"]);
    let g_delta = vec_f64(&golden["delta"]);
    let g_acc_lambda = vec_f64(&golden["acc_lambda"]);
    let g_acc_rdelta = opt_vec_f64(&golden["acc_rdelta"]);
    let g_move_type = opt_vec_f64(&golden["move_type"]);

    let _ = (n, k);

    let nsamp = fit.iter;
    let mut max_beta = 0.0f64;
    let mut max_lambda = 0.0f64;
    let mut max_sigsq = 0.0f64;
    let mut max_r = 0.0f64;
    let mut max_delta = 0.0f64;

    for s in 0..nsamp {
        for j in 0..k {
            let gv = g_beta[s * k + j];
            max_beta = max_beta.max((fit.beta[(s, j)] - gv).abs());
        }
        max_lambda = max_lambda.max((fit.lambda[(s, 0)] - g_lambda[s]).abs());
        max_sigsq = max_sigsq.max((fit.sigsq_eps[s] - g_sigsq[s]).abs());
        for j in 0..m {
            max_r = max_r.max((fit.r[(s, j)] - g_r[s * m + j]).abs());
            max_delta = max_delta.max((fit.delta[(s, j)] - g_delta[s * m + j]).abs());
        }
    }

    // Count acceptance / move-type mismatches (from iteration 2 onward)
    let mut n_accept_mismatch = 0usize;
    for s in 1..nsamp {
        if (fit.acc_lambda[(s, 0)] - g_acc_lambda[s]).abs() > 0.5 {
            n_accept_mismatch += 1;
        }
        if fit.varsel {
            if (fit.acc_rdelta[s] - g_acc_rdelta[s]).abs() > 0.5 {
                n_accept_mismatch += 1;
            }
            if (fit.move_type[s] - g_move_type[s]).abs() > 0.5 {
                n_accept_mismatch += 1;
            }
        }
    }

    ChainCmp {
        max_beta,
        max_lambda,
        max_sigsq,
        max_r,
        max_delta,
        n_accept_mismatch,
    }
}

fn run_scenario(golden: &Value) -> (bkmr::BkmrFit, usize, usize, usize) {
    let n = golden["n"].as_u64().unwrap() as usize;
    let m = golden["M"].as_u64().unwrap() as usize;
    let seed = golden["seed"].as_u64().unwrap() as u32;
    let varsel = golden["varsel"].as_bool().unwrap();
    let r_prior_str = golden["r_prior"].as_str().unwrap();
    let zgen = golden["Zgen"].as_str().unwrap();
    let hfun = golden["hfun"].as_u64().unwrap() as usize;
    let iter = golden["iter"].as_u64().unwrap() as usize;
    let r_prior: RPrior = r_prior_str.parse().unwrap();

    // Generate data with the same seed
    let mut rng = Rng::new(seed);
    let dat = sim_data(&mut rng, n, m, 0.5, 2.0, hfun, zgen, &[1, 2]);

    // Verify data matches
    let g_y = vec_f64(&golden["y"]);
    let g_z = vec_f64(&golden["Z"]);
    let g_x = vec_f64(&golden["X"]);
    let max_y_diff = dat.y.iter().zip(g_y.iter()).map(|(a, b)| (a - b).abs()).fold(0.0f64, f64::max);
    assert!(max_y_diff < 1e-12, "y mismatch: {max_y_diff:e}");
    let mut max_z_diff = 0.0f64;
    for i in 0..n {
        for j in 0..m {
            max_z_diff = max_z_diff.max((dat.z[(i, j)] - g_z[j * n + i]).abs());
        }
    }
    assert!(max_z_diff < 1e-12, "Z mismatch: {max_z_diff:e}");
    let max_x_diff = (0..n).map(|i| (dat.x[(i, 0)] - g_x[i]).abs()).fold(0.0f64, f64::max);
    assert!(max_x_diff < 1e-12, "X mismatch: {max_x_diff:e}");

    // Run kmbayes with same seed
    let mut rng2 = Rng::new(seed);
    let opts = KmbayesOptions {
        iter,
        varsel,
        rmethod: RMethod::Varying,
        r_prior,
        starting_values: StartingValues {
            beta: Some(vec![0.0]),
            sigsq_eps: Some(0.5),
            r: Some(vec![1.0; m]),
            lambda: Some(vec![10.0]),
            delta: Some(vec![1.0; m]),
            h_hat: Some(vec![1.0; n]),
        },
        control_params: ControlParams {
            r_prior,
            ..ControlParams::default()
        },
        ztest: None,
    };
    let fit = kmbayes(&mut rng2, &dat.y, dat.z.as_ref(), dat.x.as_ref(), &opts).unwrap();
    (fit, n, m, 1)
}

// ── tests ───────────────────────────────────────────────────────────────

#[test]
fn xval_gaussian_novarsel() {
    let g = load_golden();
    let s = &g["scenarios"]["gaussian_novarsel"];
    let (fit, n, m, k) = run_scenario(s);
    let cmp = compare_chain(s, &fit, n, m, k);
    eprintln!("gaussian_novarsel: beta={:.3e} lambda={:.3e} sigsq={:.3e} r={:.3e} delta={:.3e} accept_mismatch={}",
              cmp.max_beta, cmp.max_lambda, cmp.max_sigsq, cmp.max_r, cmp.max_delta, cmp.n_accept_mismatch);
    assert!(cmp.max_beta < TOL_CHAIN, "beta diff {}", cmp.max_beta);
    assert!(cmp.max_lambda < TOL_CHAIN, "lambda diff {}", cmp.max_lambda);
    assert!(cmp.max_sigsq < TOL_CHAIN, "sigsq diff {}", cmp.max_sigsq);
    assert!(cmp.max_r < TOL_CHAIN, "r diff {}", cmp.max_r);
    assert!(cmp.n_accept_mismatch == 0, "accept mismatch {}", cmp.n_accept_mismatch);
}

#[test]
fn xval_gaussian_varsel() {
    let g = load_golden();
    let s = &g["scenarios"]["gaussian_varsel"];
    let (fit, n, m, k) = run_scenario(s);
    let cmp = compare_chain(s, &fit, n, m, k);
    eprintln!("gaussian_varsel: beta={:.3e} lambda={:.3e} sigsq={:.3e} r={:.3e} delta={:.3e} accept_mismatch={}",
              cmp.max_beta, cmp.max_lambda, cmp.max_sigsq, cmp.max_r, cmp.max_delta, cmp.n_accept_mismatch);
    assert!(cmp.max_beta < TOL_CHAIN, "beta diff {}", cmp.max_beta);
    assert!(cmp.max_lambda < TOL_CHAIN, "lambda diff {}", cmp.max_lambda);
    assert!(cmp.max_sigsq < TOL_CHAIN, "sigsq diff {}", cmp.max_sigsq);
    assert!(cmp.max_r < TOL_CHAIN, "r diff {}", cmp.max_r);
    assert!(cmp.max_delta < TOL_CHAIN, "delta diff {}", cmp.max_delta);
    assert!(cmp.n_accept_mismatch == 0, "accept mismatch {}", cmp.n_accept_mismatch);
}

#[test]
fn xval_gaussian_varsel_gamma() {
    let g = load_golden();
    let s = &g["scenarios"]["gaussian_varsel_gamma"];
    let (fit, n, m, k) = run_scenario(s);
    let cmp = compare_chain(s, &fit, n, m, k);
    eprintln!("gaussian_varsel_gamma: beta={:.3e} lambda={:.3e} sigsq={:.3e} r={:.3e} delta={:.3e} accept_mismatch={}",
              cmp.max_beta, cmp.max_lambda, cmp.max_sigsq, cmp.max_r, cmp.max_delta, cmp.n_accept_mismatch);
    assert!(cmp.max_beta < TOL_CHAIN, "beta diff {}", cmp.max_beta);
    assert!(cmp.max_lambda < TOL_CHAIN, "lambda diff {}", cmp.max_lambda);
    assert!(cmp.max_sigsq < TOL_CHAIN, "sigsq diff {}", cmp.max_sigsq);
    assert!(cmp.max_r < TOL_CHAIN, "r diff {}", cmp.max_r);
    assert!(cmp.max_delta < TOL_CHAIN, "delta diff {}", cmp.max_delta);
}

#[test]
fn xval_gaussian_novarsel_unif() {
    let g = load_golden();
    let s = &g["scenarios"]["gaussian_novarsel_unif"];
    let (fit, n, m, k) = run_scenario(s);
    let cmp = compare_chain(s, &fit, n, m, k);
    eprintln!("gaussian_novarsel_unif: beta={:.3e} lambda={:.3e} sigsq={:.3e} r={:.3e} delta={:.3e} accept_mismatch={}",
              cmp.max_beta, cmp.max_lambda, cmp.max_sigsq, cmp.max_r, cmp.max_delta, cmp.n_accept_mismatch);
    assert!(cmp.max_beta < TOL_CHAIN, "beta diff {}", cmp.max_beta);
    assert!(cmp.max_lambda < TOL_CHAIN, "lambda diff {}", cmp.max_lambda);
    assert!(cmp.max_sigsq < TOL_CHAIN, "sigsq diff {}", cmp.max_sigsq);
    assert!(cmp.max_r < TOL_CHAIN, "r diff {}", cmp.max_r);
}
