//! Cross-validation of the Rust GenomicSEM port against R lavaan golden
//! outputs (generated by `tests/fixtures-gen/gen_golden.R`).
//!
//! These tests load JSON fixtures containing:
//! - Known S (genetic covariance) and V (sampling covariance) matrices
//! - R lavaan parameter estimates from `sem()` with DWLS estimation
//! - GenomicSEM sandwich SEs computed from lavaan's delta/WLS.V
//! - Model chi-square from the eigen-decomposition formula
//!
//! The Rust SEM engine is run on the same S/V inputs and compared to the
//! R golden values within tolerance.
//!
//! Point estimates (loadings, variances) should match to ~1e-2 relative;
//! sandwich SEs match to ~5e-2 relative (sensitive to numerical Jacobian).

use std::fs;

use faer::Mat;
use serde::Deserialize;
use serde_json::Value;

use genomic_sem::*;

const GOLDEN_DIR: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures/golden");

// ── Helpers ──────────────────────────────────────────────────────────────

fn load_json(name: &str) -> Value {
    let path = format!("{GOLDEN_DIR}/{name}");
    let s = fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {}: {e}", path));
    serde_json::from_str(&s).unwrap_or_else(|e| panic!("parse JSON {}: {e}", path))
}

/// Parse a JSON 2D array into a faer Mat<f64>.
fn json_to_mat(v: &Value) -> Mat<f64> {
    let rows = v.as_array().expect("expected 2D array");
    let n = rows.len();
    let m = rows[0].as_array().expect("row is array").len();
    let mut mat = Mat::zeros(n, m);
    for i in 0..n {
        let row = rows[i].as_array().unwrap();
        for j in 0..m {
            mat[(i, j)] = row[j].as_f64().unwrap();
        }
    }
    mat
}

/// Parse a JSON 1D array into Vec<f64>.
fn json_to_vec(v: &Value) -> Vec<f64> {
    v.as_array()
        .expect("expected 1D array")
        .iter()
        .map(|x| x.as_f64().unwrap_or(f64::NAN))
        .collect()
}

/// Relative tolerance check: |a - b| <= rel * max(|b|, abs) + abs.
fn close(a: f64, b: f64, rel: f64, abs: f64) -> bool {
    if a.is_nan() && b.is_nan() {
        return true;
    }
    if a.is_nan() || b.is_nan() {
        return false;
    }
    (a - b).abs() <= rel * b.abs().max(1e-12) + abs
}

/// Build a Covstruc from the JSON scenario.
fn scenario_to_covstruc(scen: &Value) -> utils::Covstruc {
    let s = json_to_mat(&scen["S"]);
    let k = s.nrows();
    let z = k * (k + 1) / 2;
    let v_diag = json_to_vec(&scen["V_diag"]);
    let v = linalg::diag_from_vec(&v_diag);

    utils::Covstruc {
        v,
        s,
        i_mat: Mat::<f64>::identity(k, k),
        n: Mat::zeros(1, z),
        m: 100_000.0,
        v_stand: None,
        s_stand: None,
    }
}

/// Extract the lavaan golden parameter estimates for free parameters only.
struct GoldenParams {
    lhs: Vec<String>,
    op: Vec<String>,
    rhs: Vec<String>,
    est: Vec<f64>,
    se: Vec<f64>,
}

fn golden_params(scen: &Value) -> GoldenParams {
    let lhs: Vec<String> = scen["par_lhs"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_str().unwrap().to_string())
        .collect();
    let op: Vec<String> = scen["par_op"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_str().unwrap().to_string())
        .collect();
    let rhs: Vec<String> = scen["par_rhs"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_str().unwrap().to_string())
        .collect();
    let free: Vec<i64> = scen["par_free"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_i64().unwrap())
        .collect();
    let est_all = json_to_vec(&scen["par_est"]);
    let se_all = json_to_vec(&scen["sandwich_SE"]);

    // Keep only free parameters (free > 0), in order of free index
    let mut indices: Vec<usize> = (0..free.len()).filter(|&i| free[i] > 0).collect();
    indices.sort_by_key(|&i| free[i]);

    // sandwich_SE is indexed by free-parameter position (0-based), not by
    // table row. Map each table index to its SE position: free_idx - 1.
    GoldenParams {
        lhs: indices.iter().map(|&i| lhs[i].clone()).collect(),
        op: indices.iter().map(|&i| op[i].clone()).collect(),
        rhs: indices.iter().map(|&i| rhs[i].clone()).collect(),
        est: indices.iter().map(|&i| est_all[i]).collect(),
        se: indices
            .iter()
            .map(|&i| {
                let se_idx = (free[i] - 1) as usize;
                if se_idx < se_all.len() {
                    se_all[se_idx]
                } else {
                    f64::NAN
                }
            })
            .collect(),
    }
}

// =====================================================================
// Scenario 1: 3-trait saturated one-factor
// =====================================================================

#[test]
fn xval_scenario1_parameter_recovery() {
    let scen = load_json("scenario1_one_factor_3trait.json");
    let covstruc = scenario_to_covstruc(&scen);

    // Run Rust SEM
    let config = usermodel::UserModelConfig {
        model: scen["model"].as_str().unwrap().to_string(),
        ..Default::default()
    };
    let result = usermodel::usermodel(&covstruc, &config).unwrap();

    // The model is saturated (df=0), so loadings should be recovered exactly.
    // Compare each loading against the known true values.
    let loading_results: Vec<&usermodel::ParamResult> =
        result.results.iter().filter(|r| r.op == "=~").collect();
    assert_eq!(loading_results.len(), 3, "Expected 3 factor loadings");

    let true_loadings = json_to_vec(&scen["true_loadings"]);
    for (i, r) in loading_results.iter().enumerate() {
        // Exact match expected for saturated model: machine precision
        assert!(
            close(r.unstand_est, true_loadings[i], 1e-6, 1e-8),
            "Loading {}: Rust={:.10} vs true={:.10}",
            i,
            r.unstand_est,
            true_loadings[i]
        );
    }

    // Compare model-implied covariance against lavaan's: machine precision
    let golden_implied = json_to_mat(&scen["implied"]);
    for i in 0..3 {
        for j in 0..3 {
            assert!(
                close(
                    result.sem_implied[(i, j)],
                    golden_implied[(i, j)],
                    1e-6,
                    1e-9
                ),
                "Implied[{},{}]: Rust={:.10} vs lavaan={:.10}",
                i,
                j,
                result.sem_implied[(i, j)],
                golden_implied[(i, j)]
            );
        }
    }
}

#[test]
fn xval_scenario1_chisq() {
    let scen = load_json("scenario1_one_factor_3trait.json");
    let golden_chisq = scen["chisq"].as_f64().unwrap();

    // For a saturated model, chi-square should be ~0
    assert!(
        golden_chisq.abs() < 1e-10,
        "Golden chi-sq: {}",
        golden_chisq
    );
}

#[test]
fn xval_scenario1_df() {
    let scen = load_json("scenario1_one_factor_3trait.json");
    let golden_df = scen["df"].as_i64().unwrap();
    assert_eq!(golden_df, 0, "3-trait one-factor = saturated (df=0)");
}

// =====================================================================
// Scenario 2: 5-trait one-factor model (df=5)
// =====================================================================

#[test]
fn xval_scenario2_implied_covariance() {
    let scen = load_json("scenario2_one_factor_5trait.json");
    let covstruc = scenario_to_covstruc(&scen);
    let golden_implied = json_to_mat(&scen["implied"]);

    let config = usermodel::UserModelConfig {
        model: scen["model"].as_str().unwrap().to_string(),
        ..Default::default()
    };
    let result = usermodel::usermodel(&covstruc, &config).unwrap();

    let k = golden_implied.nrows();
    for i in 0..k {
        for j in 0..k {
            assert!(
                close(
                    result.sem_implied[(i, j)],
                    golden_implied[(i, j)],
                    1e-6,
                    1e-9
                ),
                "Implied[{},{}]: Rust={:.10} vs lavaan={:.10}",
                i,
                j,
                result.sem_implied[(i, j)],
                golden_implied[(i, j)]
            );
        }
    }
}

/// Find a parameter in the golden set matching (lhs, op, rhs).
fn find_golden<'a>(golden: &'a GoldenParams, lhs: &str, op: &str, rhs: &str) -> Option<(f64, f64)> {
    for i in 0..golden.lhs.len() {
        if golden.lhs[i] == lhs && golden.op[i] == op && golden.rhs[i] == rhs {
            return Some((golden.est[i], golden.se[i]));
        }
    }
    None
}

#[test]
fn xval_scenario2_loading_estimates() {
    let scen = load_json("scenario2_one_factor_5trait.json");
    let covstruc = scenario_to_covstruc(&scen);
    let golden = golden_params(&scen);

    let config = usermodel::UserModelConfig {
        model: scen["model"].as_str().unwrap().to_string(),
        ..Default::default()
    };
    let result = usermodel::usermodel(&covstruc, &config).unwrap();

    // Compare each loading estimate against lavaan golden by matching (lhs,op,rhs)
    let n_traits = scen["n_traits"].as_u64().unwrap() as usize;
    for t in 1..=n_traits {
        let varname = format!("V{}", t);
        let golden_est = find_golden(&golden, "F1", "=~", &varname);
        let rust_est = result
            .results
            .iter()
            .find(|r| r.lhs == "F1" && r.op == "=~" && r.rhs == varname);

        match (golden_est, rust_est) {
            (Some((ge, _)), Some(re)) => {
                // Machine precision match: Rust optimizer converges to same point as lavaan
                assert!(
                    close(re.unstand_est, ge, 1e-5, 1e-8),
                    "Loading F1=~{}: Rust={:.10} vs lavaan={:.10}",
                    varname,
                    re.unstand_est,
                    ge
                );
            }
            _ => { /* skip if not found in both */ }
        }
    }
}

#[test]
fn xval_scenario2_residual_variances() {
    let scen = load_json("scenario2_one_factor_5trait.json");
    let covstruc = scenario_to_covstruc(&scen);
    let golden = golden_params(&scen);

    let config = usermodel::UserModelConfig {
        model: scen["model"].as_str().unwrap().to_string(),
        ..Default::default()
    };
    let result = usermodel::usermodel(&covstruc, &config).unwrap();

    let n_traits = scen["n_traits"].as_u64().unwrap() as usize;
    for t in 1..=n_traits {
        let varname = format!("V{}", t);
        let golden_est = find_golden(&golden, &varname, "~~", &varname);
        let rust_est = result
            .results
            .iter()
            .find(|r| r.lhs == varname && r.op == "~~" && r.rhs == varname);

        match (golden_est, rust_est) {
            (Some((ge, _)), Some(re)) => {
                // Machine precision match
                assert!(
                    close(re.unstand_est, ge, 1e-5, 1e-8),
                    "Resid var {}~~{}: Rust={:.10} vs lavaan={:.10}",
                    varname,
                    varname,
                    re.unstand_est,
                    ge
                );
            }
            _ => { /* skip if not found in both */ }
        }
    }
}

#[test]
fn xval_scenario2_df_and_srmr() {
    let scen = load_json("scenario2_one_factor_5trait.json");
    let golden_df = scen["df"].as_i64().unwrap();
    let golden_srmr = scen["srmr"].as_f64().unwrap();

    // df should be 5 (5*6/2 - 10 = 5)
    assert_eq!(golden_df, 5);

    // SRMR should be small for a well-fitting model
    assert!(golden_srmr < 0.01, "Golden SRMR: {}", golden_srmr);
}

// =====================================================================
// Scenario 3: 4-trait two-factor model
// =====================================================================

#[test]
fn xval_scenario3_implied_covariance() {
    let scen = load_json("scenario3_two_factor_4trait.json");
    let covstruc = scenario_to_covstruc(&scen);
    let golden_implied = json_to_mat(&scen["implied"]);

    let config = usermodel::UserModelConfig {
        model: scen["model"].as_str().unwrap().to_string(),
        ..Default::default()
    };
    let result = usermodel::usermodel(&covstruc, &config).unwrap();

    let k = golden_implied.nrows();
    for i in 0..k {
        for j in 0..k {
            assert!(
                close(
                    result.sem_implied[(i, j)],
                    golden_implied[(i, j)],
                    1e-6,
                    1e-9
                ),
                "Implied[{},{}]: Rust={:.10} vs lavaan={:.10}",
                i,
                j,
                result.sem_implied[(i, j)],
                golden_implied[(i, j)]
            );
        }
    }
}

#[test]
fn xval_scenario3_factor_loadings() {
    // NOTE: The two-factor model with 4 indicators (2 per factor) and all
    // loadings free (NA*) is underidentified (11 free params, 10 observed
    // statistics, df = -1). With `optim.force.converged = TRUE`, lavaan
    // still produces a solution, but the individual parameter estimates
    // are NOT unique — only the model-implied covariance matrix is unique.
    //
    // Therefore, we validate the implied covariance (unique) rather than
    // individual loadings (non-unique for this specification).
    let scen = load_json("scenario3_two_factor_4trait.json");
    let covstruc = scenario_to_covstruc(&scen);
    let golden_implied = json_to_mat(&scen["implied"]);

    let config = usermodel::UserModelConfig {
        model: scen["model"].as_str().unwrap().to_string(),
        ..Default::default()
    };
    let result = usermodel::usermodel(&covstruc, &config).unwrap();

    // The implied covariance must match lavaan regardless of parameterization
    let k = golden_implied.nrows();
    for i in 0..k {
        for j in 0..k {
            assert!(
                close(
                    result.sem_implied[(i, j)],
                    golden_implied[(i, j)],
                    1e-6,
                    1e-9
                ),
                "Implied[{},{}]: Rust={:.10} vs lavaan={:.10}",
                i,
                j,
                result.sem_implied[(i, j)],
                golden_implied[(i, j)]
            );
        }
    }

    // Also verify the residual variances match (these ARE identified since
    // they equal S[i,i] - λᵢ²·ψ, and S[i,i] is observed)
    let golden = golden_params(&scen);
    for var in &["V1", "V2", "V3", "V4"] {
        let golden_est = find_golden(&golden, var, "~~", var);
        let rust_est = result
            .results
            .iter()
            .find(|r| r.lhs == *var && r.op == "~~" && r.rhs == *var);
        match (golden_est, rust_est) {
            (Some((ge, _)), Some(re)) => {
                // Residual variances are identified: θ_i = S[i,i] - Σ[i,i] + θ_i
                // Machine precision expected since implied cov matches.
                assert!(
                    close(re.unstand_est, ge, 1e-6, 1e-8),
                    "Resid {}~~{}: Rust={:.10} vs lavaan={:.10}",
                    var,
                    var,
                    re.unstand_est,
                    ge
                );
            }
            _ => {}
        }
    }
}

// =====================================================================
// Scenario 4: nearPD cross-validation
// =====================================================================

#[test]
fn xval_scenario4_near_pd() {
    let scen = load_json("scenario4_near_pd.json");
    let input = json_to_mat(&scen["input"]);
    let golden_output = json_to_mat(&scen["output"]);
    let golden_eigenvalues = json_to_vec(&scen["output_eigenvalues"]);

    // Run Rust nearPD
    let rust_output = near_pd::near_pd(&input);

    // Check that Rust output is SPD
    assert!(
        near_pd::is_spd(&rust_output),
        "Rust nearPD output should be SPD"
    );

    // Compare eigenvalues (both should have all-positive eigenvalues)
    let (rust_eigvals, _) = linalg::eigen_sym(&rust_output);
    for &ge in &golden_eigenvalues {
        assert!(
            ge >= -1e-10,
            "Golden eigenvalue should be non-negative: {}",
            ge
        );
    }
    for &re in &rust_eigvals {
        assert!(
            re >= -1e-10,
            "Rust eigenvalue should be non-negative: {}",
            re
        );
    }

    // Check that the output is close to the R Matrix::nearPD output
    // (Different nearPD implementations may converge to slightly different
    // nearest PD matrices, but they should be close in Frobenius norm)
    let mut frob_diff = 0.0;
    for i in 0..3 {
        for j in 0..3 {
            let d = rust_output[(i, j)] - golden_output[(i, j)];
            frob_diff += d * d;
        }
    }
    frob_diff = frob_diff.sqrt();
    assert!(
        frob_diff < 0.2,
        "nearPD Frobenius diff: {} (Rust vs Matrix::nearPD)",
        frob_diff
    );
}

// =====================================================================
// Scenario 5: Liability conversion
// =====================================================================

#[test]
fn xval_scenario5_liability_conversion() {
    let scen = load_json("scenario5_liability.json");
    let prevs = json_to_vec(&scen["population_prev"]);
    let samp_prev = scen["sample_prev"].as_f64().unwrap();
    let golden_factors = json_to_vec(&scen["conversion_factors"]);

    for (i, &pop_prev) in prevs.iter().enumerate() {
        let rust_cf = utils::liability_conversion_factor(pop_prev, samp_prev);
        assert!(
            close(rust_cf, golden_factors[i], 1e-4, 1e-6),
            "Liability conversion for prev={}: Rust={} vs R={}",
            pop_prev,
            rust_cf,
            golden_factors[i]
        );
    }
}
