//! R golden test for `mediation_weighted_binary` point estimates.
//!
//! Golden files are generated by `tests/xval/gen_weighted_mediation_binary_reference.R`
//! (one-shot rocker/r-ver:4.5.1 probe with R survey 4.5): the mediator model is
//! `svyglm(m2 ~ x2 + c1, gaussian)` and the outcome model is
//! `svyglm(y2 ~ x2 + m2 + c1, quasibinomial)`; the decomposition is evaluated
//! in R at the weighted covariate means. Only point estimates are compared —
//! bootstrap CIs use a Rust RNG stream that cannot be aligned with R's
//! (same convention as xval_weighted_mediation.rs).
//!
//! Run: `cargo test -p epi --test xval_weighted_mediation_binary`

use epi::bootstrap::BootstrapDesign;
use epi::mediation_weighted::{MediationWeightedOptions, mediation_weighted_binary};

fn read_data() -> std::collections::HashMap<String, Vec<f64>> {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/xval/mediation_binary_data.csv"
    );
    let text = std::fs::read_to_string(path)
        .unwrap_or_else(|_| panic!("mediation_binary_data.csv missing — run the probe"));
    let mut cols: std::collections::HashMap<String, Vec<f64>> = Default::default();
    let mut headers: Vec<String> = Vec::new();
    for (i, line) in text.lines().enumerate() {
        let fields: Vec<&str> = if line.starts_with('"') {
            line.split("\",\"").map(|f| f.trim_matches('"')).collect()
        } else {
            line.split(',').collect()
        };
        if i == 0 {
            headers = fields.iter().map(|s| s.to_string()).collect();
            for h in &headers {
                cols.insert(h.clone(), Vec::new());
            }
            continue;
        }
        for (h, f) in headers.iter().zip(&fields) {
            cols.get_mut(h).unwrap().push(f.parse::<f64>().unwrap());
        }
    }
    cols
}

#[test]
fn mediation_weighted_binary_matches_r() {
    let d = read_data();
    let ref_json = std::fs::read_to_string(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/xval/weighted_mediation_binary_reference.json"
    ))
    .expect("weighted_mediation_binary_reference.json missing");
    let r: serde_json::Value = serde_json::from_str(&ref_json).unwrap();
    let g = &r["mediation_binary"];

    let n = d["y2"].len();
    let strata: Vec<u64> = d["st2"].iter().map(|&v| v as u64).collect();
    let psu: Vec<u64> = d["psu2"].iter().map(|&v| v as u64).collect();
    let design = BootstrapDesign::with_clusters(&d["wt2"], Some(&strata), Some(&psu)).unwrap();
    assert_eq!(design.n(), n);

    let cov = [d["c1"].as_slice()];
    let opts = MediationWeightedOptions {
        n_bootstrap: 0,
        ..Default::default()
    };
    let res =
        mediation_weighted_binary(&d["x2"], &d["m2"], &d["y2"], &cov, &design, &opts).unwrap();

    let close = |a: f64, b: f64, tol: f64, what: &str| {
        assert!(
            (a - b).abs() <= tol,
            "{what}: rust {a} vs R {b} (|Δ| = {})",
            (a - b).abs()
        );
    };

    // Path coefficients.
    close(
        res.alpha_x,
        g["alpha"][1].as_f64().unwrap(),
        1e-6,
        "alpha_x",
    );
    close(res.beta_x, g["beta"][1].as_f64().unwrap(), 1e-6, "beta_x");
    close(res.beta_m, g["beta"][2].as_f64().unwrap(), 1e-6, "beta_m");
    close(
        res.m_under_control,
        g["m_under_control"].as_f64().unwrap(),
        1e-6,
        "m_under_control",
    );
    // Decomposition (log-odds scale, dx = 1, no interaction).
    close(res.cde, g["cde"].as_f64().unwrap(), 1e-5, "cde");
    close(res.nie, g["nie"].as_f64().unwrap(), 1e-5, "nie");
    close(res.te, g["te"].as_f64().unwrap(), 1e-5, "te");
    close(
        res.prop_mediated,
        g["prop_mediated"].as_f64().unwrap(),
        1e-4,
        "prop_mediated",
    );
    assert_eq!(res.n_obs, n);
    // No bootstrap replicates → NaN CIs, successful count 0.
    assert_eq!(res.n_bootstrap, 0);
}
