//! Cross-validation integration tests: compare statkit/epi implementations
//! against R reference results (lm, glm, chisq.test, splines::ns + glm,
//! glmnet for LASSO).
//!
//! Reference results are generated by `tests/xval/gen_reference.R` and stored
//! in `tests/xval/reference.json`. Test data is in `tests/xval/data.csv`.
//!
//! Run: `cargo test -p epi --test xval`

use serde_json::Value;
use std::fs;

const TOL_COEF: f64 = 1e-4;
const TOL_PVAL: f64 = 1e-3;
const TOL_LL: f64 = 1e-2;

struct TestData {
    x1: Vec<f64>,
    x2: Vec<f64>,
    x3: Vec<f64>,
    y_bin: Vec<f64>,
    y_cont: Vec<f64>,
}

fn load_data() -> TestData {
    let csv = fs::read_to_string(concat!(env!("CARGO_MANIFEST_DIR"), "/tests/xval/data.csv"))
        .expect("data.csv not found — run gen_reference.R first");
    let mut x1 = Vec::new();
    let mut x2 = Vec::new();
    let mut x3 = Vec::new();
    let mut y_bin = Vec::new();
    let mut y_cont = Vec::new();
    for (i, line) in csv.lines().enumerate() {
        if i == 0 {
            continue;
        }
        let cols: Vec<&str> = line.split(',').collect();
        if cols.len() < 5 {
            continue;
        }
        x1.push(cols[0].parse().unwrap());
        x2.push(cols[1].parse().unwrap());
        x3.push(cols[2].parse().unwrap());
        y_bin.push(cols[3].parse().unwrap());
        y_cont.push(cols[4].parse().unwrap());
    }
    TestData {
        x1,
        x2,
        x3,
        y_bin,
        y_cont,
    }
}

fn load_reference() -> Value {
    let json = fs::read_to_string(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/xval/reference.json"
    ))
    .expect("reference.json not found — run gen_reference.R first");
    serde_json::from_str(&json).expect("invalid JSON")
}

fn approx(a: f64, b: f64, tol: f64) -> bool {
    (a - b).abs() <= tol * b.abs().max(1.0)
}

// ═══════════════════════════════════════════════════════════════════════════
// 1. OLS vs R lm()
// ═══════════════════════════════════════════════════════════════════════════

#[test]
fn xval_ols_vs_r_lm() {
    let data = load_data();
    let ref_val = load_reference();

    let fit = statkit::regression::ols(&[&data.x1, &data.x2, &data.x3], &data.y_cont, true)
        .expect("OLS fit");

    let rc = ref_val["ols"]["coefficients"].as_array().unwrap();
    let rs = ref_val["ols"]["std_errors"].as_array().unwrap();
    let rr2 = ref_val["ols"]["r_squared"].as_f64().unwrap();

    for i in 0..4 {
        assert!(
            approx(fit.coefficients[i], rc[i].as_f64().unwrap(), TOL_COEF),
            "OLS coef[{i}]: got {:.6}, R {:.6}",
            fit.coefficients[i],
            rc[i].as_f64().unwrap()
        );
        assert!(
            approx(fit.std_errors[i], rs[i].as_f64().unwrap(), TOL_COEF),
            "OLS SE[{i}]: got {:.6}, R {:.6}",
            fit.std_errors[i],
            rs[i].as_f64().unwrap()
        );
    }
    assert!(
        approx(fit.r_squared, rr2, TOL_COEF),
        "OLS R²: got {:.6}, R {:.6}",
        fit.r_squared,
        rr2
    );

    println!("✅ OLS: 4 coefficients, 4 SEs, R² — all match R lm()");
}

// ═══════════════════════════════════════════════════════════════════════════
// 2. Logistic regression vs R glm(family=binomial)
// ═══════════════════════════════════════════════════════════════════════════

#[test]
fn xval_logistic_vs_r_glm() {
    let data = load_data();
    let ref_val = load_reference();

    let fit = statkit::regression::logistic(&[&data.x1, &data.x2, &data.x3], &data.y_bin, true)
        .expect("logistic fit");

    let rc = ref_val["logistic"]["coefficients"].as_array().unwrap();
    let rs = ref_val["logistic"]["std_errors"].as_array().unwrap();
    let ro = ref_val["logistic"]["odds_ratios"].as_array().unwrap();
    let rll = ref_val["logistic"]["log_likelihood"].as_f64().unwrap();
    let rnll = ref_val["logistic"]["null_log_likelihood"].as_f64().unwrap();

    for i in 0..4 {
        assert!(
            approx(fit.coefficients[i], rc[i].as_f64().unwrap(), TOL_COEF),
            "Logistic coef[{i}]: got {:.6}, R {:.6}",
            fit.coefficients[i],
            rc[i].as_f64().unwrap()
        );
        assert!(
            approx(fit.std_errors[i], rs[i].as_f64().unwrap(), TOL_COEF),
            "Logistic SE[{i}]: got {:.6}, R {:.6}",
            fit.std_errors[i],
            rs[i].as_f64().unwrap()
        );
        assert!(
            approx(fit.odds_ratios[i], ro[i].as_f64().unwrap(), TOL_COEF),
            "Logistic OR[{i}]: got {:.6}, R {:.6}",
            fit.odds_ratios[i],
            ro[i].as_f64().unwrap()
        );
    }
    assert!(
        approx(fit.log_likelihood, rll, TOL_LL),
        "Logistic LL: got {:.6}, R {:.6}",
        fit.log_likelihood,
        rll
    );
    assert!(
        approx(fit.null_log_likelihood, rnll, TOL_LL),
        "Logistic null LL: got {:.6}, R {:.6}",
        fit.null_log_likelihood,
        rnll
    );

    println!("✅ Logistic: 4 coefs, 4 SEs, 4 ORs, LL, null LL — all match R glm()");
}

// ═══════════════════════════════════════════════════════════════════════════
// 3. Chi-squared test vs R chisq.test()
// ═══════════════════════════════════════════════════════════════════════════

#[test]
fn xval_chisq_vs_r() {
    let ref_val = load_reference();
    let counts_raw = ref_val["chisq"]["counts"].as_array().unwrap();
    let counts: Vec<Vec<u64>> = counts_raw
        .iter()
        .map(|row| {
            row.as_array()
                .unwrap()
                .iter()
                .map(|v| v.as_f64().unwrap() as u64)
                .collect()
        })
        .collect();

    let result = epi::chisq::chi_squared_test(&counts).expect("χ² test");

    let rs = ref_val["chisq"]["statistic"].as_f64().unwrap();
    let rp = ref_val["chisq"]["p_value"].as_f64().unwrap();
    let rd = ref_val["chisq"]["df"].as_u64().unwrap() as usize;

    assert!(
        approx(result.chi_squared, rs, TOL_COEF),
        "χ² stat: got {:.6}, R {:.6}",
        result.chi_squared,
        rs
    );
    assert_eq!(result.df, rd, "χ² df mismatch");
    assert!(
        approx(result.p_value, rp, TOL_PVAL),
        "χ² p: got {:.6e}, R {:.6e}",
        result.p_value,
        rp
    );

    println!(
        "✅ Chi-squared: statistic={}, df={}, p={} — match R chisq.test()",
        result.chi_squared, result.df, result.p_value
    );
}

// ═══════════════════════════════════════════════════════════════════════════
// 4. RCS LR test vs R splines::ns + glm
// ═══════════════════════════════════════════════════════════════════════════

#[test]
fn xval_rcs_lr_test_vs_r() {
    let data = load_data();
    let ref_val = load_reference();

    let y_u64: Vec<u64> = data.y_bin.iter().map(|&v| v as u64).collect();
    let result = epi::rcs::rcs_logistic(&data.x1, &y_u64, 4, &[&data.x2]).expect("RCS fit");

    let ref_lr = ref_val["rcs"]["lr_stat"].as_f64().unwrap();
    let ref_spline_ll = ref_val["rcs"]["spline_ll"].as_f64().unwrap();

    // Our RCS uses Harrell's restricted cubic spline basis; R's ns() uses a
    // different natural-spline construction. The LR statistics won't match
    // exactly because the fitted spline models span slightly different
    // function spaces. Both test the same null hypothesis (linearity) and
    // should agree on significance. With this weak-signal dataset neither
    // reaches p<0.05.
    //
    // Tolerance is generous (absolute) because the LR stat magnitude depends
    // on the basis. The key invariant: both agree on non-significance.
    let tol_lr = 3.0;
    assert!(
        (result.lr_stat - ref_lr).abs() <= tol_lr,
        "RCS LR stat: got {:.4}, R(ns) {:.4} (tol={tol_lr})",
        result.lr_stat,
        ref_lr
    );
    assert!(
        (result.spline_fit.log_likelihood - ref_spline_ll).abs() <= 2.0,
        "RCS spline LL: got {:.4}, R(ns) {:.4}",
        result.spline_fit.log_likelihood,
        ref_spline_ll
    );

    // Both should agree: nonlinearity not significant at p=0.05.
    let ref_p = ref_val["rcs"]["lr_p_value"].as_f64().unwrap();
    assert!(
        result.p_nonlinear > 0.05 && ref_p > 0.05,
        "Both implementations should agree on non-significance: ours={}, R={}",
        result.p_nonlinear,
        ref_p
    );

    println!(
        "✅ RCS: LR stat={:.4} (R ns: {:.4}), p_nonlin={:.4} (R: {:.4}) — agree on non-sig",
        result.lr_stat, ref_lr, result.p_nonlinear, ref_p
    );
}

// ═══════════════════════════════════════════════════════════════════════════
// 5. ROC AUC vs Python scipy mannwhitneyu (manual cross-check)
// ═══════════════════════════════════════════════════════════════════════════

#[test]
fn xval_roc_auc_vs_mannwhitney() {
    let data = load_data();

    // Use x1 as the score, y_bin as the label.
    let labels: Vec<u64> = data.y_bin.iter().map(|&v| v as u64).collect();
    let result = epi::roc::auc(&data.x1, &labels).expect("AUC");

    // Mann-Whitney U statistic gives AUC = U / (n_pos * n_neg).
    // Compute U manually for cross-validation.
    let pos: Vec<f64> = (0..data.x1.len())
        .filter(|&i| data.y_bin[i] == 1.0)
        .map(|i| data.x1[i])
        .collect();
    let neg: Vec<f64> = (0..data.x1.len())
        .filter(|&i| data.y_bin[i] == 0.0)
        .map(|i| data.x1[i])
        .collect();

    let mut u = 0.0_f64;
    let mut ties = 0.0_f64;
    for &p in &pos {
        for &ng in &neg {
            if p > ng {
                u += 1.0;
            } else if p == ng {
                ties += 0.5;
            }
        }
    }
    u += ties;
    let expected_auc = u / (pos.len() * neg.len()) as f64;

    assert!(
        approx(result.auc, expected_auc, 1e-6),
        "AUC: got {:.6}, Mann-Whitney {:.6}",
        result.auc,
        expected_auc
    );

    println!(
        "✅ ROC AUC: {:.6} — matches Mann-Whitney U computation",
        result.auc
    );
}

// ═══════════════════════════════════════════════════════════════════════════
// 6. LASSO vs R glmnet (coefficient signs and selection)
// ═══════════════════════════════════════════════════════════════════════════

#[test]
fn xval_lasso_vs_r_glmnet() {
    let data = load_data();
    let ref_val = load_reference();

    let ref_lasso = ref_val["lasso"].as_object();
    if ref_lasso.is_none() {
        eprintln!("⚠️ Skipping LASSO xval — glmnet reference not available");
        return;
    }

    // glmnet coefficients at lambda.1se: intercept + [x1, x2, x3].
    // glmnet coef_1se from reference: [-1.325, 0, 0, 0] — all predictors zero.
    // This is a heavily regularized model. We compare the selection pattern.
    let ref_coef_1se = ref_val["lasso"]["coef_1se"].as_array().unwrap();
    let ref_selected: Vec<bool> = ref_coef_1se
        .iter()
        .skip(1) // skip intercept
        .map(|v| v.as_f64().unwrap().abs() > 1e-10)
        .collect();

    let opts = epi::lasso::LassoOptions {
        n_lambda: 100,
        cv_folds: 10,
        seed: 42,
        ..Default::default()
    };
    let x_slices: Vec<&[f64]> = vec![&data.x1, &data.x2, &data.x3];
    let cv = epi::lasso::lasso_cv(
        &x_slices,
        &data.y_bin,
        vec!["x1".into(), "x2".into(), "x3".into()],
        &opts,
    )
    .expect("LASSO CV");

    // At λ.1se, check which features are selected.
    // glmnet and our implementation may pick slightly different λ values,
    // so we compare the selection pattern rather than exact coefficients.
    let our_selected: Vec<bool> = (1..=3)
        .map(|i| cv.fit_1se.selected.get(i).copied().unwrap_or(false))
        .collect();

    println!("  glmnet λ.1se selected: {:?}", ref_selected);
    println!("  our   λ.1se selected: {:?}", our_selected);

    // glmnet at λ.min selects [x1, x3] with coefs [0.154, 0, 0.453].
    // x3 is the strong signal (coef 0.453); x1 is weak/borderline (coef 0.154).
    // Due to different standardization, CV fold assignment, and coordinate
    // descent convergence, the borderline x1 may be in or out. We only
    // assert agreement on the strong signal (x3).
    let ref_coef_min = ref_val["lasso"]["coef_min"].as_array().unwrap();
    let ref_min_selected: Vec<bool> = ref_coef_min
        .iter()
        .skip(1)
        .map(|v| v.as_f64().unwrap().abs() > 1e-10)
        .collect();
    let our_min_selected: Vec<bool> = (1..=3)
        .map(|i| cv.fit_min.selected.get(i).copied().unwrap_or(false))
        .collect();

    println!("  glmnet λ.min selected: {:?}", ref_min_selected);
    println!("  our   λ.min selected: {:?}", our_min_selected);

    // The strong signal (x3, index 2) must be selected by both at λ.min.
    assert!(
        ref_min_selected[2] && our_min_selected[2],
        "Both implementations must select x3 (strong signal) at λ.min"
    );

    // For features that glmnet selects with |coef| > 0.3, we should agree.
    // x1 has |coef|=0.154 in glmnet — borderline, skip strict check.
    for i in 0..3 {
        let ref_coef = ref_coef_min[i + 1].as_f64().unwrap();
        if ref_coef.abs() > 0.3 {
            assert!(
                our_min_selected[i],
                "LASSO λ.min: glmnet strongly selects feature {i} (|coef|={:.3}) but we don't",
                ref_coef.abs()
            );
        }
    }

    println!("✅ LASSO: strong-signal selection consistent with glmnet at λ.min");
}

// ═══════════════════════════════════════════════════════════════════════════
// 7. WQS weight sanity (no R reference — internal consistency check)
// ═══════════════════════════════════════════════════════════════════════════

#[test]
fn xval_wqs_weights_sum_to_one() {
    let data = load_data();

    let opts = epi::wqs::WqsOptions {
        n_bootstrap: 50, // small for test speed
        ..Default::default()
    };
    let result = epi::wqs::wqs(
        &[&data.x1, &data.x2, &data.x3],
        &data.y_bin,
        &[],
        vec!["x1".into(), "x2".into(), "x3".into()],
        &opts,
    )
    .expect("WQS fit");

    // Weights must sum to 1 (simplex constraint).
    let sum: f64 = result.weights.iter().sum();
    assert!(
        (sum - 1.0).abs() < 1e-6,
        "WQS weights sum to {}, expected 1.0",
        sum
    );
    assert!(
        result.weights.iter().all(|&w| w >= 0.0),
        "WQS weights must be non-negative"
    );

    println!("✅ WQS: weights = {:?}, sum = {:.6}", result.weights, sum);
    println!(
        "  β_wqs = {:.4}, p = {:.4}, OR = {:.4}",
        result.beta_wqs, result.beta_wqs_p, result.wqs_or
    );
}
