//! Cross-validation tests against susieR 0.16.6 golden outputs.
//!
//! Each test loads a JSON file from `fixtures/golden/`, reconstructs the
//! RSS input, runs `susie::susie_rss`, and compares the output to the
//! R reference within a tolerance.
//!
//! Golden data was generated by `fixtures/gen_golden.R` using the same
//! simulation seeds as susieR's own reference tests
//! (`tests/testthat/reference/test_susie_rss_reference.R`).

use faer::Mat;
use serde::{Deserialize, Deserializer};

/// Deserialize a value that might be a scalar or a single-element array into f64.
fn flex_f64<'de, D: Deserializer<'de>>(d: D) -> Result<f64, D::Error> {
    let v = serde_json::Value::deserialize(d)?;
    match &v {
        serde_json::Value::Number(n) => Ok(n.as_f64().unwrap_or(f64::NAN)),
        serde_json::Value::Array(a) if a.len() == 1 => Ok(a[0].as_f64().unwrap_or(f64::NAN)),
        _ => Ok(f64::NAN),
    }
}

/// Deserialize a bool that might be a scalar or a single-element array.
fn flex_bool<'de, D: Deserializer<'de>>(d: D) -> Result<bool, D::Error> {
    let v = serde_json::Value::deserialize(d)?;
    match &v {
        serde_json::Value::Bool(b) => Ok(*b),
        serde_json::Value::Array(a) if a.len() == 1 => Ok(a[0].as_bool().unwrap_or(false)),
        _ => Ok(false),
    }
}

/// Deserialize a Vec<f64> that might be a scalar (unboxed) or an array.
fn flex_vec_f64<'de, D: Deserializer<'de>>(d: D) -> Result<Vec<f64>, D::Error> {
    let v = serde_json::Value::deserialize(d)?;
    match v {
        serde_json::Value::Number(n) => Ok(vec![n.as_f64().unwrap_or(f64::NAN)]),
        serde_json::Value::Array(a) => Ok(a
            .into_iter()
            .map(|x| x.as_f64().unwrap_or(f64::NAN))
            .collect()),
        _ => Ok(vec![]),
    }
}

/// Deserialize a Vec<Vec<f64>> that might be 1D (unboxed) or 2D.
fn flex_vec2_f64<'de, D: Deserializer<'de>>(d: D) -> Result<Vec<Vec<f64>>, D::Error> {
    let v = serde_json::Value::deserialize(d)?;
    match v {
        serde_json::Value::Array(a) => {
            // Check if first element is itself an array or a scalar
            if a.is_empty() {
                return Ok(vec![]);
            }
            match &a[0] {
                serde_json::Value::Array(_) => {
                    // Already 2D
                    Ok(a.into_iter()
                        .map(|row| match row {
                            serde_json::Value::Array(vals) => vals
                                .into_iter()
                                .map(|v| v.as_f64().unwrap_or(f64::NAN))
                                .collect(),
                            _ => vec![],
                        })
                        .collect())
                }
                serde_json::Value::Number(_) => {
                    // 1D array → wrap as single row
                    Ok(vec![
                        a.into_iter()
                            .map(|v| v.as_f64().unwrap_or(f64::NAN))
                            .collect(),
                    ])
                }
                _ => Ok(vec![]),
            }
        }
        _ => Ok(vec![]),
    }
}

// ─── JSON deserialization types ──────────────────────────────────────────────

#[derive(Debug, Deserialize)]
#[allow(dead_code)] // Golden JSON contains fields not asserted by every case.
struct GoldenPayload {
    name: String,
    args: serde_json::Value,
    input: GoldenInput,
    fit: GoldenFit,
}

#[derive(Debug, Deserialize)]
#[allow(dead_code)]
struct GoldenInput {
    z: Vec<f64>,
    #[serde(rename = "R")]
    r: Vec<Vec<f64>>, // p×p row-major (jsonlite matrix="rowmajor")
    n: serde_json::Value,
    bhat: Option<Vec<f64>>,
    shat: Option<Vec<f64>>,
    var_y: Option<f64>,
    p: usize,
    prior_weights: Option<Vec<f64>>,
}

#[derive(Debug, Deserialize)]
#[allow(dead_code)]
struct GoldenFit {
    #[serde(deserialize_with = "flex_vec2_f64")]
    alpha: Vec<Vec<f64>>,
    #[serde(deserialize_with = "flex_vec2_f64")]
    mu: Vec<Vec<f64>>,
    #[serde(deserialize_with = "flex_vec2_f64")]
    mu2: Vec<Vec<f64>>,
    #[serde(rename = "V", deserialize_with = "flex_vec_f64")]
    v: Vec<f64>,
    #[serde(deserialize_with = "flex_vec2_f64", default)]
    lbf_variable: Vec<Vec<f64>>,
    #[serde(deserialize_with = "flex_vec_f64")]
    lbf: Vec<f64>,
    #[serde(rename = "KL", deserialize_with = "flex_vec_f64")]
    kl: Vec<f64>,
    #[serde(deserialize_with = "flex_f64")]
    sigma2: f64,
    #[serde(deserialize_with = "flex_vec_f64")]
    elbo: Vec<f64>,
    #[serde(deserialize_with = "flex_f64", default)]
    niter: f64,
    #[serde(deserialize_with = "flex_bool", default)]
    converged: bool,
    #[serde(deserialize_with = "flex_vec_f64")]
    pip: Vec<f64>,
}

// ─── helpers ─────────────────────────────────────────────────────────────────

fn load_golden(name: &str) -> GoldenPayload {
    // CARGO_MANIFEST_DIR is the crate root (bio_crates/susie/).
    // Fixtures live at <workspace>/fixtures/golden/.
    let manifest = env!("CARGO_MANIFEST_DIR");
    let path = format!("{}/../../fixtures/golden/{}.json", manifest, name);
    let data =
        std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("Cannot read {}: {}", path, e));
    serde_json::from_str(&data).unwrap_or_else(|e| panic!("Cannot parse {}: {}", path, e))
}

fn r_to_mat(r: &[Vec<f64>]) -> Mat<f64> {
    let p = r.len();
    let mut m = Mat::zeros(p, p);
    for i in 0..p {
        for j in 0..p {
            m[(i, j)] = r[i][j];
        }
    }
    m
}

fn json_to_f64(v: &serde_json::Value) -> Option<f64> {
    match v {
        serde_json::Value::Number(n) => n.as_f64(),
        serde_json::Value::Array(a) if a.len() == 1 => a[0].as_f64(),
        serde_json::Value::Null => None,
        _ => None,
    }
}

/// Extract a scalar arg value from JSON (handles both scalar and [scalar]).
fn json_scalar(v: &serde_json::Value) -> Option<f64> {
    json_to_f64(v)
}

/// Build the RssInput from a golden payload.
fn build_input(g: &GoldenPayload) -> susie::RssInput {
    let args = &g.args;
    let r = r_to_mat(&g.input.r);

    // Only pass n if the R side actually passed it in args (z_non scenarios omit n)
    let n = if args.get("n").is_some() {
        json_to_f64(&g.input.n)
    } else {
        None
    };

    let mut input = susie::RssInput {
        r,
        n,
        l: 10,
        ..Default::default()
    };

    // z vs bhat/shat — check args to decide which input mode the R side used.
    // In the golden JSON, args$bhat is either `true` (placeholder, never used)
    // or the actual data vector (when bhat was passed to susie_rss).
    let uses_bhat = match args.get("bhat") {
        Some(serde_json::Value::Array(a)) if !a.is_empty() => true,
        _ => false,
    };
    if uses_bhat {
        input.bhat = g.input.bhat.clone();
        input.shat = g.input.shat.clone();
        input.var_y = g.input.var_y;
    } else {
        input.z = Some(g.input.z.clone());
    }

    // Parse args for overrides
    let jnum = |key: &str| -> Option<f64> { args.get(key).and_then(json_scalar) };
    let jbool = |key: &str| -> Option<bool> {
        match args.get(key) {
            Some(serde_json::Value::Bool(b)) => Some(*b),
            Some(serde_json::Value::Array(a)) if a.len() == 1 => a[0].as_bool(),
            _ => None,
        }
    };
    let jstr = |key: &str| -> Option<String> {
        match args.get(key) {
            Some(serde_json::Value::String(s)) => Some(s.clone()),
            Some(serde_json::Value::Array(a)) if a.len() == 1 => a[0].as_str().map(String::from),
            _ => None,
        }
    };

    if let Some(l) = jnum("L") {
        input.l = l as usize;
    }
    if let Some(spv) = jnum("scaled_prior_variance") {
        input.scaled_prior_variance = spv;
    }
    if let Some(b) = jbool("estimate_prior_variance") {
        input.estimate_prior_variance = b;
    }
    if let Some(b) = jbool("estimate_residual_variance") {
        input.estimate_residual_variance = b;
    }
    if let Some(rv) = jnum("residual_variance") {
        input.residual_variance = Some(rv);
    }
    if let Some(cov) = jnum("coverage") {
        input.coverage = cov;
    }
    if let Some(mac) = jnum("min_abs_corr") {
        input.min_abs_corr = Some(mac);
    }
    if let Some(nt) = jnum("check_null_threshold") {
        input.check_null_threshold = nt;
    }
    if let Some(nw) = jnum("null_weight") {
        input.null_weight = nw;
    }
    if let Some(zm) = jstr("z_method") {
        input.z_method = if zm == "score" {
            susie::ZMethod::Score
        } else {
            susie::ZMethod::Wald
        };
    }
    if let Some(pm) = jstr("estimate_prior_method") {
        input.estimate_prior_method = match pm.as_str() {
            "EM" => susie::PriorMethod::Em,
            "simple" => susie::PriorMethod::Simple,
            _ => susie::PriorMethod::Optim,
        };
    }

    // Prior weights
    if let Some(pw) = &g.input.prior_weights {
        if !pw.is_empty() {
            input.prior_weights = Some(pw.clone());
        }
    }

    input
}

// ─── comparison helpers ──────────────────────────────────────────────────────

/// Tolerance for cross-validation. 1e-4 is appropriate for cross-language
/// comparison (R/BLAS vs Rust/faer) — the z-only path (n=2, V=50) amplifies
/// floating-point differences beyond pure-algorithmic precision.
const TOL: f64 = 1e-4;

fn max_abs_diff(a: &[f64], b: &[f64]) -> f64 {
    a.iter()
        .zip(b.iter())
        .map(|(a, b)| (a - b).abs())
        .fold(0.0_f64, f64::max)
}

fn max_abs_diff_2d(a: &[Vec<f64>], b: &[Vec<f64>]) -> f64 {
    a.iter()
        .zip(b.iter())
        .map(|(a, b)| max_abs_diff(a, b))
        .fold(0.0_f64, f64::max)
}

fn assert_fit_close(name: &str, fit: &susie::SusieFit, golden: &GoldenFit) {
    let d_alpha = max_abs_diff_2d(&fit.alpha, &golden.alpha);
    let d_mu = max_abs_diff_2d(&fit.mu, &golden.mu);
    let d_mu2 = max_abs_diff_2d(&fit.mu2, &golden.mu2);
    let d_sigma2 = (fit.sigma2 - golden.sigma2).abs();
    let d_pip = max_abs_diff(&fit.pip, &golden.pip);

    // V / lbf / KL are sensitive to the null-threshold check (V≈0 boundary).
    // When one side zeros an effect (V=0) and the other keeps a small V,
    // the difference is large in absolute terms but the alpha/pip are barely
    // affected. Use a larger tolerance for these boundary-sensitive quantities.
    let d_v = max_abs_diff(&fit.v, &golden.v);
    let d_lbf = max_abs_diff(&fit.lbf, &golden.lbf);
    let d_kl = max_abs_diff(&fit.kl, &golden.kl);

    let elbo_golden = golden.elbo.last().copied().unwrap_or(f64::NAN);
    let elbo_rust = fit.elbo.last().copied().unwrap_or(f64::NAN);
    let d_elbo = (elbo_rust - elbo_golden).abs();

    eprintln!(
        "  {:<30} α={:.2e} μ={:.2e} μ²={:.2e} V={:.2e} lbf={:.2e} KL={:.2e} σ²={:.2e} pip={:.2e} elbo={:.2e} (R:{:.4} Rust:{:.4})",
        name,
        d_alpha,
        d_mu,
        d_mu2,
        d_v,
        d_lbf,
        d_kl,
        d_sigma2,
        d_pip,
        d_elbo,
        elbo_golden,
        elbo_rust
    );

    assert!(
        d_alpha < TOL,
        "{}: alpha diff {:.2e} >= {}",
        name,
        d_alpha,
        TOL
    );
    // V/lbf/KL: allow up to 0.2 difference (null-threshold boundary sensitivity)
    assert!(d_v < 0.2, "{}: V diff {:.2e} >= 0.2", name, d_v);
    assert!(d_lbf < 0.2, "{}: lbf diff {:.2e} >= 0.2", name, d_lbf);
    assert!(d_kl < 0.2, "{}: KL diff {:.2e} >= 0.2", name, d_kl);
    assert!(
        d_sigma2 < TOL,
        "{}: sigma2 diff {:.2e} >= {}",
        name,
        d_sigma2,
        TOL
    );
    assert!(d_pip < TOL, "{}: pip diff {:.2e} >= {}", name, d_pip, TOL);
    // elbo: allow small relative error for null-threshold boundary effects
    let elbo_tol = (elbo_golden.abs() * 1e-3).max(TOL);
    assert!(
        d_elbo < elbo_tol,
        "{}: elbo diff {:.2e} >= {:.2e}",
        name,
        d_elbo,
        elbo_tol
    );
}

// ─── test runner ─────────────────────────────────────────────────────────────

fn run_golden(name: &str) {
    let g = load_golden(name);
    let input = build_input(&g);
    let fit = susie::susie_rss(&input).expect("susie_rss failed");
    assert_fit_close(name, &fit, &g.fit);
}

// ─── tests ───────────────────────────────────────────────────────────────────

#[allow(non_snake_case)]
mod tests {
    use super::*;

    #[test]
    fn z_n_optim() {
        run_golden("z_n_optim");
    }
    #[test]
    fn z_n_simple() {
        run_golden("z_n_simple");
    }
    #[test]
    fn z_n_EM() {
        run_golden("z_n_EM");
    }
    #[test]
    fn z_non_optim() {
        run_golden("z_non_optim");
    }
    #[test]
    fn z_non_simple() {
        run_golden("z_non_simple");
    }
    #[test]
    fn z_non_EM() {
        run_golden("z_non_EM");
    }
    #[test]
    fn L1_optim() {
        run_golden("L1_optim");
    }
    #[test]
    fn L5_optim() {
        run_golden("L5_optim");
    }
    #[test]
    fn L1_EM() {
        run_golden("L1_EM");
    }
    #[test]
    fn L5_EM() {
        run_golden("L5_EM");
    }
    #[test]
    fn L1_simple() {
        run_golden("L1_simple");
    }
    #[test]
    fn L5_simple() {
        run_golden("L5_simple");
    }
    #[test]
    fn fixV_optim() {
        run_golden("fixV_optim");
    }
    #[test]
    fn fixV_simple() {
        run_golden("fixV_simple");
    }
    #[test]
    fn estR_var_optim() {
        run_golden("estR_var_optim");
    }
    #[test]
    fn estR_var_simple() {
        run_golden("estR_var_simple");
    }
    #[test]
    fn fixR_var_optim() {
        run_golden("fixR_var_optim");
    }
    #[test]
    fn fixR_var_simple() {
        run_golden("fixR_var_simple");
    }
    #[test]
    fn scaleV05_optim() {
        run_golden("scaleV05_optim");
    }
    #[test]
    fn scaleV05_simple() {
        run_golden("scaleV05_simple");
    }
    #[test]
    fn cov99_optim() {
        run_golden("cov99_optim");
    }
    #[test]
    fn cov99_simple() {
        run_golden("cov99_simple");
    }
    #[test]
    fn mincorr07_optim() {
        run_golden("mincorr07_optim");
    }
    #[test]
    fn mincorr07_simple() {
        run_golden("mincorr07_simple");
    }
    #[test]
    fn nullthresh_optim() {
        run_golden("nullthresh_optim");
    }
    #[test]
    fn nullthresh_simple() {
        run_golden("nullthresh_simple");
    }
    #[test]
    fn nullW_optim() {
        run_golden("nullW_optim");
    }
    #[test]
    fn nullW_simple() {
        run_golden("nullW_simple");
    }
    #[test]
    fn zscore_score() {
        run_golden("zscore_score");
    }
    #[test]
    fn bhat_shat_optim() {
        run_golden("bhat_shat_optim");
    }
    #[test]
    fn bhat_shat_simple() {
        run_golden("bhat_shat_simple");
    }
}
