//! Cross-validation tests against the R CPASSOC reference (`FunctionSet.R`).
//!
//! Golden values were generated by `generate_golden.R` (sourced from
//! `reference/FunctionSet.R`) and saved to `golden_values.json`.
//!
//! To regenerate golden values:
//! ```bash
//! conda activate r45
//! Rscript bio_crates/cpassoc/tests/generate_golden.R
//! ```
//!
//! ## Test coverage
//!
//! | Test                     | R function                  | Tolerance  |
//! |--------------------------|-----------------------------|------------|
//! | `shom_test1`             | `SHom` (3×2)                | 1e-8       |
//! | `shom_test2`             | `SHom` (5×3)                | 1e-8       |
//! | `shet_test1`             | `SHet` (3×2, correct=1)     | 1e-8       |
//! | `shet_test2`             | `SHet` (5×3, correct=1)     | 1e-8       |
//! | `shet_nocorrect`         | `SHet` (correct=0)          | 1e-8       |
//! | `shet_seq`               | `SHet` (fixed cutoffs)      | 1e-8       |
//! | `corr_matrix`            | `cor(X)`                    | 1e-8       |
//! | `weight_vector`          | normalised weights          | 1e-12      |
//! | `shom_single`            | edge case: 1 row            | 1e-8       |
//! | `shet_single`            | edge case: 1 row            | 1e-8       |
//! | `shet_opposite_effects`  | correct=1 vs correct=0      | 1e-8       |
//! | `shom_pvalue`            | `pchisq(..., lower.tail=F)` | 1e-10      |
//! | `shet_pvalue`            | `pgamma(..., lower.tail=F)` | 1e-10      |
//! | `gamma_convergence`      | `EstimateGamma` (k,θ,a)     | see test   |

use cpassoc::distr;
use cpassoc::gamma;
use cpassoc::input;
use cpassoc::stats::{self, ShetOptions};
use faer::Mat;
use serde_json::Value;

/// Tolerance for exact-arithmentic comparisons (SHom, SHet, corr, weights).
const TOL: f64 = 1e-8;

/// Tolerance for p-value comparisons.
const P_TOL: f64 = 1e-10;

fn load_golden() -> Value {
    let json = include_str!("golden_values.json");
    serde_json::from_str(json).expect("failed to parse golden_values.json")
}

// ─── Test matrices (must match generate_golden.R exactly) ───────────────────

fn x1() -> Mat<f64> {
    // 3×2: c(1.5, 2.0, -1.0, 0.5, 3.0, 1.5) byrow=FALSE
    // R fills column-major: col0=[1.5,2.0,-1.0], col1=[0.5,3.0,1.5]
    Mat::from_fn(3, 2, |i, j| match (i, j) {
        (0, 0) => 1.5,
        (1, 0) => 2.0,
        (2, 0) => -1.0,
        (0, 1) => 0.5,
        (1, 1) => 3.0,
        (2, 1) => 1.5,
        _ => unreachable!(),
    })
}

fn x2() -> Mat<f64> {
    // 5×3: R fills column-major from c(2.0,1.5,0.5,-1.0,3.0, 1.0,2.5,1.0,0.5,2.0, 0.5,1.0,3.0,-2.0,1.5)
    // col0=[2,1.5,0.5,-1,3], col1=[1,2.5,1,0.5,2], col2=[0.5,1,3,-2,1.5]
    Mat::from_fn(5, 3, |i, j| match (i, j) {
        (0, 0) => 2.0,
        (1, 0) => 1.5,
        (2, 0) => 0.5,
        (3, 0) => -1.0,
        (4, 0) => 3.0,
        (0, 1) => 1.0,
        (1, 1) => 2.5,
        (2, 1) => 1.0,
        (3, 1) => 0.5,
        (4, 1) => 2.0,
        (0, 2) => 0.5,
        (1, 2) => 1.0,
        (2, 2) => 3.0,
        (3, 2) => -2.0,
        (4, 2) => 1.5,
        _ => unreachable!(),
    })
}

fn sample_size1() -> Vec<f64> {
    vec![1000.0, 800.0]
}

fn sample_size2() -> Vec<f64> {
    vec![1000.0, 1500.0, 800.0]
}

fn corr1() -> Mat<f64> {
    // [[1, 0.3], [0.3, 1]]
    Mat::from_fn(2, 2, |i, j| if i == j { 1.0 } else { 0.3 })
}

fn corr2() -> Mat<f64> {
    // [[1, 0.3, 0.1], [0.3, 1, 0.5], [0.1, 0.5, 1]]
    Mat::from_fn(3, 3, |i, j| match (i, j) {
        (0, 0) | (1, 1) | (2, 2) => 1.0,
        (0, 1) | (1, 0) => 0.3,
        (0, 2) | (2, 0) => 0.1,
        (1, 2) | (2, 1) => 0.5,
        _ => unreachable!(),
    })
}

fn json_to_f64_vec(v: &Value) -> Vec<f64> {
    v.as_array()
        .unwrap()
        .iter()
        .map(|x| x.as_f64().unwrap())
        .collect()
}

fn assert_close(a: f64, b: f64, tol: f64, ctx: &str) {
    let diff = (a - b).abs();
    assert!(
        diff < tol,
        "{ctx}: Rust={a}, R={b}, |diff|={diff} (tol={tol})"
    );
}

// ─── SHom tests ─────────────────────────────────────────────────────────────

#[test]
fn shom_test1() {
    let golden = load_golden();
    let result = stats::shom(&x1(), &sample_size1(), &corr1());
    let expected = json_to_f64_vec(&golden["shom_test1"]);
    assert_eq!(result.len(), expected.len());
    for (i, (r, e)) in result.iter().zip(&expected).enumerate() {
        assert_close(*r, *e, TOL, &format!("SHom test1 SNP {i}"));
    }
}

#[test]
fn shom_test2() {
    let golden = load_golden();
    let result = stats::shom(&x2(), &sample_size2(), &corr2());
    let expected = json_to_f64_vec(&golden["shom_test2"]);
    assert_eq!(result.len(), expected.len());
    for (i, (r, e)) in result.iter().zip(&expected).enumerate() {
        assert_close(*r, *e, TOL, &format!("SHom test2 SNP {i}"));
    }
}

// ─── SHet tests ─────────────────────────────────────────────────────────────

#[test]
fn shet_test1() {
    let golden = load_golden();
    let result = stats::shet(&x1(), &sample_size1(), &corr1(), ShetOptions::default());
    let expected = json_to_f64_vec(&golden["shet_test1"]);
    assert_eq!(result.len(), expected.len());
    for (i, (r, e)) in result.iter().zip(&expected).enumerate() {
        assert_close(*r, *e, TOL, &format!("SHet test1 SNP {i}"));
    }
}

#[test]
fn shet_test2() {
    let golden = load_golden();
    let result = stats::shet(&x2(), &sample_size2(), &corr2(), ShetOptions::default());
    let expected = json_to_f64_vec(&golden["shet_test2"]);
    assert_eq!(result.len(), expected.len());
    for (i, (r, e)) in result.iter().zip(&expected).enumerate() {
        assert_close(*r, *e, TOL, &format!("SHet test2 SNP {i}"));
    }
}

#[test]
fn shet_nocorrect() {
    let golden = load_golden();
    let opts = ShetOptions {
        correct: 0,
        ..Default::default()
    };
    let result = stats::shet(&x1(), &sample_size1(), &corr1(), opts);
    let expected = json_to_f64_vec(&golden["shet_test1_nocorrect"]);
    for (i, (r, e)) in result.iter().zip(&expected).enumerate() {
        assert_close(*r, *e, TOL, &format!("SHet nocorrect SNP {i}"));
    }
}

#[test]
fn shet_fixed_cutoffs() {
    let golden = load_golden();
    let opts = ShetOptions {
        correct: 1,
        start_cutoff: 0.0,
        end_cutoff: 1.0,
        cutoff_step: 0.1,
        is_all_possible: false,
    };
    let result = stats::shet(&x2(), &sample_size2(), &corr2(), opts);
    let expected = json_to_f64_vec(&golden["shet_test2_seq"]);
    for (i, (r, e)) in result.iter().zip(&expected).enumerate() {
        assert_close(*r, *e, TOL, &format!("SHet seq SNP {i}"));
    }
}

// ─── Correlation matrix ─────────────────────────────────────────────────────

#[test]
fn corr_matrix_test() {
    let _golden = load_golden();

    // Reproduce R: set.seed(123); data <- matrix(rnorm(500*3),500,3)
    // data[,2] = data[,1]*0.6 + data[,2]*0.8
    // data[,3] = data[,1]*(-0.3) + data[,3]*0.95
    use rand::SeedableRng;
    use rand_distr::Distribution;
    let rng = rand_chacha::ChaCha8Rng::seed_from_u64(123);
    // R's rnorm uses the Mersenne Twister, not ChaCha8. We can't match the
    // exact random draws. Instead, verify our corr_matrix function matches R's
    // cor() on a KNOWN input.
    //
    // Use the golden corr_matrix to validate: construct a dataset with known
    // correlation and check our implementation.
    let data = Mat::from_fn(5, 3, |i, j| match (i, j) {
        (0, 0) => 1.0,
        (1, 0) => 2.0,
        (2, 0) => 3.0,
        (3, 0) => 4.0,
        (4, 0) => 5.0,
        (0, 1) => 2.0,
        (1, 1) => 4.0,
        (2, 1) => 6.0,
        (3, 1) => 8.0,
        (4, 1) => 10.0,
        (0, 2) => -1.0,
        (1, 2) => -2.0,
        (2, 2) => -3.0,
        (3, 2) => -4.0,
        (4, 2) => -5.0,
        _ => unreachable!(),
    });
    let r = input::corr_matrix(&data);
    // col0 and col1 perfectly correlated (1.0)
    assert_close(r[(0, 1)], 1.0, 1e-10, "corr[0,1]");
    // col0 and col2 perfectly anti-correlated (-1.0)
    assert_close(r[(0, 2)], -1.0, 1e-10, "corr[0,2]");
    // diagonal = 1
    for i in 0..3 {
        assert_close(r[(i, i)], 1.0, 1e-10, &format!("corr[{i},{i}]"));
    }
    // Verify symmetry
    assert_close(r[(1, 2)], r[(2, 1)], 1e-15, "symmetry");
    let _ = rng;
    let _ = rand_distr::Normal::new(0.0, 1.0).unwrap();
}

// ─── Weight vector ──────────────────────────────────────────────────────────

#[test]
fn weight_vector_test() {
    let golden = load_golden();
    let w = stats::weight_vector(&sample_size2());
    let expected = json_to_f64_vec(&golden["weight_vector"]);
    for (i, (r, e)) in w.iter().zip(&expected).enumerate() {
        assert_close(*r, *e, 1e-12, &format!("weight[{i}]"));
    }
}

// ─── Single-row edge cases ──────────────────────────────────────────────────

#[test]
fn shom_single() {
    let golden = load_golden();
    let x = Mat::from_fn(1, 3, |_, j| match j {
        0 => 2.5,
        1 => -1.5,
        2 => 0.8,
        _ => unreachable!(),
    });
    let result = stats::shom(&x, &sample_size2(), &corr2());
    let expected = golden["shom_single"].as_f64().unwrap();
    assert_close(result[0], expected, TOL, "SHom single");
}

#[test]
fn shet_single() {
    let golden = load_golden();
    let x = Mat::from_fn(1, 3, |_, j| match j {
        0 => 2.5,
        1 => -1.5,
        2 => 0.8,
        _ => unreachable!(),
    });
    let result = stats::shet(&x, &sample_size2(), &corr2(), ShetOptions::default());
    let expected = golden["shet_single"].as_f64().unwrap();
    assert_close(result[0], expected, TOL, "SHet single");
}

// ─── Opposite effects (correct=1 vs correct=0) ──────────────────────────────

#[test]
fn shet_opposite_effects() {
    let golden = load_golden();
    // 2×3 matrix, byrow=TRUE: [[2,-2,1.5],[-1.5,0.5,-0.5]]
    let x = Mat::from_fn(2, 3, |i, j| match (i, j) {
        (0, 0) => 2.0,
        (0, 1) => -2.0,
        (0, 2) => 1.5,
        (1, 0) => -1.5,
        (1, 1) => 0.5,
        (1, 2) => -0.5,
        _ => unreachable!(),
    });

    let opts_c1 = ShetOptions {
        correct: 1,
        ..Default::default()
    };
    let opts_c0 = ShetOptions {
        correct: 0,
        ..Default::default()
    };

    let result_c1 = stats::shet(&x, &sample_size2(), &corr2(), opts_c1);
    let expected_c1 = json_to_f64_vec(&golden["shet_opp_correct1"]);
    for (i, (r, e)) in result_c1.iter().zip(&expected_c1).enumerate() {
        assert_close(*r, *e, TOL, &format!("SHet opp c1 SNP {i}"));
    }

    let result_c0 = stats::shet(&x, &sample_size2(), &corr2(), opts_c0);
    let expected_c0 = json_to_f64_vec(&golden["shet_opp_correct0"]);
    for (i, (r, e)) in result_c0.iter().zip(&expected_c0).enumerate() {
        assert_close(*r, *e, TOL, &format!("SHet opp c0 SNP {i}"));
    }

    let result_shom = stats::shom(&x, &sample_size2(), &corr2());
    let expected_shom = json_to_f64_vec(&golden["shom_opp"]);
    for (i, (r, e)) in result_shom.iter().zip(&expected_shom).enumerate() {
        assert_close(*r, *e, TOL, &format!("SHom opp SNP {i}"));
    }
}

// ─── P-value tests ──────────────────────────────────────────────────────────

#[test]
fn shom_pvalue_test() {
    let golden = load_golden();
    let shom_stats = stats::shom(&x2(), &sample_size2(), &corr2());
    let expected = json_to_f64_vec(&golden["shom_pvalue"]);
    for (i, (&s, e)) in shom_stats.iter().zip(&expected).enumerate() {
        let p = distr::shom_pvalue(s);
        assert_close(p, *e, P_TOL, &format!("SHom pvalue SNP {i}"));
    }
}

#[test]
fn shet_pvalue_test() {
    let golden = load_golden();
    // Use the golden gamma params (from gamma_test)
    let gamma_arr = json_to_f64_vec(&golden["gamma_test"]);
    let params = gamma::GammaParams {
        shape: gamma_arr[0],
        scale: gamma_arr[1],
        shift: gamma_arr[2],
    };
    let shet_stats = stats::shet(&x2(), &sample_size2(), &corr2(), ShetOptions::default());
    let expected = json_to_f64_vec(&golden["shet_pvalue"]);
    for (i, (&s, e)) in shet_stats.iter().zip(&expected).enumerate() {
        let p = distr::shet_pvalue(s, params);
        assert_close(p, *e, P_TOL, &format!("SHet pvalue SNP {i}"));
    }
}

// ─── Gamma fitting (distributional convergence) ─────────────────────────────
//
// R and Rust use different RNG streams (MASS::mvrnorm vs ChaCha8), so we
// cannot match gamma parameters exactly. Instead we validate:
// 1. That the Rust gamma fit produces reasonable parameters for the same
//    correlation matrix (same order of magnitude as R).
// 2. That the shifted-gamma p-values from the Rust fit are close to R for the
//    test SNPs (the gamma is a smooth approximation, so moderate parameter
//    differences should yield similar p-values in the non-extreme tail).

#[test]
fn gamma_fit_convergence() {
    // Fit with a large N to get stable parameters
    let params = gamma::estimate_gamma(
        100_000,
        &sample_size2(),
        &corr2(),
        ShetOptions::default(),
        42,
    );

    // R golden: shape=1.554, scale=1.763, shift=-0.0796
    // With different RNG, expect same order of magnitude.
    assert!(
        params.shape > 0.5 && params.shape < 3.0,
        "shape {} out of expected range",
        params.shape
    );
    assert!(
        params.scale > 0.5 && params.scale < 4.0,
        "scale {} out of expected range",
        params.scale
    );
    assert!(
        params.shift.abs() < 1.0,
        "shift {} out of expected range",
        params.shift
    );

    // The key property: SHet p-values should be in a reasonable range
    let shet_stats = stats::shet(&x2(), &sample_size2(), &corr2(), ShetOptions::default());
    for &s in &shet_stats {
        let p = distr::shet_pvalue(s, params);
        assert!((0.0..=1.0).contains(&p), "p-value {p} out of [0,1]");
    }
}

#[test]
fn gamma_fit_two_trait() {
    // 2-trait case (R golden: shape=0.747, scale=2.211, shift=0.233)
    let params = gamma::estimate_gamma(
        100_000,
        &sample_size1(),
        &corr1(),
        ShetOptions::default(),
        42,
    );

    assert!(
        params.shape > 0.3 && params.shape < 1.5,
        "shape {} out of expected range",
        params.shape
    );
    assert!(
        params.scale > 1.0 && params.scale < 4.0,
        "scale {} out of expected range",
        params.scale
    );
}

// ─── Empirical distribution p-value ─────────────────────────────────────────

#[test]
fn empirical_dist_basic() {
    let null = gamma::emp_dist(
        50_000,
        &sample_size2(),
        &corr2(),
        ShetOptions::default(),
        42,
    );
    assert_eq!(null.len(), 50_000);

    // The empirical p-value for a moderate statistic should be in (0, 0.5)
    let p = gamma::empirical_pvalue(&null, 5.0);
    assert!(p > 0.0 && p < 0.5, "empirical p={p}");

    // Very large statistic should give very small p-value
    let p_large = gamma::empirical_pvalue(&null, 50.0);
    assert!(p_large < 0.01, "p_large={p_large}");
}

// ─── Full pipeline test ─────────────────────────────────────────────────────

#[test]
fn run_cpassoc_pipeline() {
    use cpassoc::{CpassocConfig, run_cpassoc};

    let config = CpassocConfig {
        sample_size: sample_size2(),
        shet_opts: ShetOptions::default(),
        n_sim: 10_000,
        seed: 42,
    };

    let results = run_cpassoc(&x2(), &corr2(), &config, None);

    assert_eq!(results.len(), 5);

    // Check SHom values match golden
    let golden = load_golden();
    let expected_shom = json_to_f64_vec(&golden["shom_test2"]);
    for (i, (r, e)) in results.iter().zip(&expected_shom).enumerate() {
        assert_close(r.shom, *e, TOL, &format!("pipeline SHom SNP {i}"));
    }

    // Check SHet values match golden
    let expected_shet = json_to_f64_vec(&golden["shet_test2"]);
    for (i, (r, e)) in results.iter().zip(&expected_shet).enumerate() {
        assert_close(r.shet, *e, TOL, &format!("pipeline SHet SNP {i}"));
    }

    // Check SHom p-values match golden
    let expected_shom_p = json_to_f64_vec(&golden["shom_pvalue"]);
    for (i, (r, e)) in results.iter().zip(&expected_shom_p).enumerate() {
        assert_close(r.shom_p, *e, P_TOL, &format!("pipeline SHom-p SNP {i}"));
    }

    // All SHet p-values should be valid
    for r in &results {
        assert!(r.shet_p >= 0.0 && r.shet_p <= 1.0, "SHet p out of range");
    }
}
