//! End-to-end cross-validation on **real GWAS summary statistics**.
//!
//! Z-scores were extracted from 3 GWAS VCFs (chr1:155–156 Mb):
//!   - `ebi-a-GCST90018877` (N=461823)
//!   - `ebi-a-GCST90018864` (N=484121)
//!   - `ebi-a-GCST90018890` (N=483078)
//!
//! Golden values were generated by `generate_real_golden.R` running
//! `FunctionSet.R` (SHom, SHet, cor, EstimateGamma, p-values).
//!
//! To regenerate:
//! ```bash
//! python3 bio_crates/cpassoc/tests/extract_real_gwas.py   # extract Z-scores
//! conda activate r45
//! Rscript bio_crates/cpassoc/tests/generate_real_golden.R  # run R reference
//! ```

use cpassoc::distr;
use cpassoc::gamma;
use cpassoc::input;
use cpassoc::stats::{self, ShetOptions};
use faer::Mat;
use serde_json::Value;

/// Tolerance for exact-arithmetic comparisons.
const TOL: f64 = 1e-6;

/// Tolerance for p-value comparisons.
const P_TOL: f64 = 1e-8;

fn load_golden() -> Value {
    let json = include_str!("real_gwas_golden.json");
    serde_json::from_str(json).expect("failed to parse real_gwas_golden.json")
}

fn load_data() -> (Mat<f64>, Vec<String>) {
    let csv = include_str!("real_gwas_zscores.csv");
    let mut lines = csv.lines();
    let header: Vec<&str> = lines.next().unwrap().split(',').collect();
    assert_eq!(header.len(), 4, "expected rsid + 3 traits");

    let mut ids = Vec::new();
    let mut col0 = Vec::new();
    let mut col1 = Vec::new();
    let mut col2 = Vec::new();

    for line in lines {
        if line.is_empty() {
            continue;
        }
        let parts: Vec<&str> = line.split(',').collect();
        ids.push(parts[0].to_string());
        col0.push(parts[1].parse::<f64>().unwrap());
        col1.push(parts[2].parse::<f64>().unwrap());
        col2.push(parts[3].parse::<f64>().unwrap());
    }

    let m = col0.len();
    let mat = Mat::from_fn(m, 3, |i, j| match j {
        0 => col0[i],
        1 => col1[i],
        2 => col2[i],
        _ => unreachable!(),
    });
    (mat, ids)
}

fn json_to_f64_vec(v: &Value) -> Vec<f64> {
    v.as_array()
        .unwrap()
        .iter()
        .map(|x| x.as_f64().unwrap())
        .collect()
}

#[allow(dead_code)]
fn json_to_string_vec(v: &Value) -> Vec<String> {
    v.as_array()
        .unwrap()
        .iter()
        .map(|x| x.as_str().unwrap().to_string())
        .collect()
}

fn sample_size() -> Vec<f64> {
    vec![461823.0, 484121.0, 483078.0]
}

/// Reconstruct the K×K correlation matrix from row-major golden values.
fn golden_corr(golden: &Value) -> Mat<f64> {
    let flat = json_to_f64_vec(&golden["corr_matrix"]);
    Mat::from_fn(3, 3, |i, j| flat[i * 3 + j])
}

fn assert_close(a: f64, b: f64, tol: f64, ctx: &str) {
    let diff = (a - b).abs();
    assert!(
        diff < tol,
        "{ctx}: Rust={a}, R={b}, |diff|={diff} (tol={tol})"
    );
}

// ─── Correlation matrix ─────────────────────────────────────────────────────

#[test]
fn real_corr_matrix() {
    let golden = load_golden();
    let (x, _) = load_data();
    let r_rust = input::corr_matrix(&x);
    let r_r = golden_corr(&golden);
    for i in 0..3 {
        for j in 0..3 {
            assert_close(r_rust[(i, j)], r_r[(i, j)], TOL, &format!("corr[{i},{j}]"));
        }
    }
}

// ─── SHom ───────────────────────────────────────────────────────────────────

#[test]
fn real_shom() {
    let golden = load_golden();
    let (x, _) = load_data();
    let corr = golden_corr(&golden); // use golden corr to isolate SHom
    let result = stats::shom(&x, &sample_size(), &corr);
    let expected = json_to_f64_vec(&golden["shom_stats"]);
    assert_eq!(result.len(), expected.len());
    let mut max_diff = 0.0_f64;
    for (i, (r, e)) in result.iter().zip(&expected).enumerate() {
        let diff = (r - e).abs();
        max_diff = max_diff.max(diff);
        assert!(diff < TOL, "SHom SNP {i}: Rust={r}, R={e}, diff={diff}");
    }
    eprintln!("real SHom max |diff| = {max_diff:.2e}");
}

// ─── SHet ───────────────────────────────────────────────────────────────────

#[test]
fn real_shet() {
    let golden = load_golden();
    let (x, _) = load_data();
    let corr = golden_corr(&golden);
    let result = stats::shet(&x, &sample_size(), &corr, ShetOptions::default());
    let expected = json_to_f64_vec(&golden["shet_stats"]);
    assert_eq!(result.len(), expected.len());
    let mut max_diff = 0.0_f64;
    for (i, (r, e)) in result.iter().zip(&expected).enumerate() {
        let diff = (r - e).abs();
        max_diff = max_diff.max(diff);
        assert!(diff < TOL, "SHet SNP {i}: Rust={r}, R={e}, diff={diff}");
    }
    eprintln!("real SHet max |diff| = {max_diff:.2e}");
}

// ─── SHom p-values ──────────────────────────────────────────────────────────

#[test]
fn real_shom_pvalue() {
    let golden = load_golden();
    let (x, _) = load_data();
    let corr = golden_corr(&golden);
    let shom_stats = stats::shom(&x, &sample_size(), &corr);
    let expected = json_to_f64_vec(&golden["shom_pvalue"]);
    let mut max_diff = 0.0_f64;
    for (i, (&s, e)) in shom_stats.iter().zip(&expected).enumerate() {
        let p = distr::shom_pvalue(s);
        let diff = (p - e).abs();
        max_diff = max_diff.max(diff);
        assert!(diff < P_TOL, "SHom-p SNP {i}: Rust={p}, R={e}, diff={diff}");
    }
    eprintln!("real SHom pvalue max |diff| = {max_diff:.2e}");
}

// ─── SHet p-values (using R gamma params) ───────────────────────────────────

#[test]
fn real_shet_pvalue() {
    let golden = load_golden();
    let (x, _) = load_data();
    let corr = golden_corr(&golden);

    // Use the golden gamma params to isolate the pgamma computation
    let gamma_arr = json_to_f64_vec(&golden["gamma_params"]);
    let params = gamma::GammaParams {
        shape: gamma_arr[0],
        scale: gamma_arr[1],
        shift: gamma_arr[2],
    };

    let shet_stats = stats::shet(&x, &sample_size(), &corr, ShetOptions::default());
    let expected = json_to_f64_vec(&golden["shet_pvalue"]);
    let mut max_diff = 0.0_f64;
    for (i, (&s, e)) in shet_stats.iter().zip(&expected).enumerate() {
        let p = distr::shet_pvalue(s, params);
        let diff = (p - e).abs();
        max_diff = max_diff.max(diff);
        assert!(diff < P_TOL, "SHet-p SNP {i}: Rust={p}, R={e}, diff={diff}");
    }
    eprintln!("real SHet pvalue max |diff| = {max_diff:.2e}");
}

// ─── Full pipeline with Rust-estimated gamma ────────────────────────────────
//
// Gamma parameters depend on the RNG stream (R's Mersenne Twister vs ChaCha8),
// so we check that Rust-estimated gamma gives p-values in the same ballpark.

#[test]
fn real_pipeline_rust_gamma() {
    let golden = load_golden();
    let (x, ids) = load_data();
    let corr = input::corr_matrix(&x);

    // Use golden gamma for comparison reference
    let gamma_arr = json_to_f64_vec(&golden["gamma_params"]);
    let r_params = gamma::GammaParams {
        shape: gamma_arr[0],
        scale: gamma_arr[1],
        shift: gamma_arr[2],
    };

    // Rust gamma (using more simulations for stability)
    let rust_params =
        gamma::estimate_gamma(50_000, &sample_size(), &corr, ShetOptions::default(), 42);

    eprintln!(
        "R  gamma: shape={:.4} scale={:.4} shift={:.4}",
        r_params.shape, r_params.scale, r_params.shift
    );
    eprintln!(
        "Rust gamma: shape={:.4} scale={:.4} shift={:.4}",
        rust_params.shape, rust_params.scale, rust_params.shift
    );

    // Gamma parameters should be in the same ballpark
    assert!(
        (rust_params.shape - r_params.shape).abs() / r_params.shape < 0.5,
        "shape mismatch: Rust={} vs R={}",
        rust_params.shape,
        r_params.shape
    );
    assert!(
        (rust_params.scale - r_params.scale).abs() / r_params.scale < 0.5,
        "scale mismatch: Rust={} vs R={}",
        rust_params.scale,
        r_params.scale
    );

    // Check that p-values for known significant SNPs are comparable
    let shet_stats = stats::shet(&x, &sample_size(), &corr, ShetOptions::default());
    let expected_shet_p = json_to_f64_vec(&golden["shet_pvalue"]);

    let mut max_p_diff = 0.0_f64;
    let n_sig = expected_shet_p.iter().filter(|&&p| p < 0.05).count();
    let mut rust_sig_agree = 0;
    for (i, (&s, &e_p)) in shet_stats.iter().zip(&expected_shet_p).enumerate() {
        let rust_p = distr::shet_pvalue(s, rust_params);
        let diff = (rust_p - e_p).abs();
        max_p_diff = max_p_diff.max(diff);
        // For significance calls at α=0.05, both should agree on most SNPs
        let r_sig = e_p < 0.05;
        let rust_sig = rust_p < 0.05;
        if r_sig == rust_sig {
            rust_sig_agree += 1;
        }
        let _ = i;
    }

    let agreement = rust_sig_agree as f64 / shet_stats.len() as f64;
    eprintln!(
        "SHet p-value significance (alpha=0.05) agreement: {}/{} = {:.4}",
        rust_sig_agree,
        shet_stats.len(),
        agreement
    );
    eprintln!("Max p-value diff (Rust gamma vs R gamma): {max_p_diff:.2e}");
    eprintln!("R significant SNPs (p<0.05): {n_sig}");

    // At least 90% of significance calls should agree
    assert!(
        agreement > 0.90,
        "significance agreement {:.4} < 0.90",
        agreement
    );
    let _ = ids;
}
