//! Golden cross-validation: rdlocrand Rust vs R.
//!
//! Generated by sourcing rdlocrand_fun.R + rdrandinf.R in R (v2.0)
//! on Senate election data (1297 obs, window [-1, 1]).

use std::io::BufReader;
use rdlocrand::{rdrandinf, RdRandInfConfig};

fn load_senate() -> (Vec<f64>, Vec<f64>) {
    let path = "tests/senate_randinf.csv";
    let file = std::fs::File::open(path).unwrap_or_else(|e| panic!("Cannot open {path}: {e}"));
    let mut rdr = csv::ReaderBuilder::new().from_reader(BufReader::new(file));
    let mut y = Vec::new();
    let mut r = Vec::new();
    for result in rdr.records() {
        let record = result.unwrap();
        y.push(record.get(0).unwrap().parse::<f64>().unwrap());
        r.push(record.get(1).unwrap().parse::<f64>().unwrap());
    }
    (y, r)
}

fn rel_err(a: f64, b: f64) -> f64 {
    if a.abs() < 1e-30 && b.abs() < 1e-30 { return 0.0; }
    (a - b).abs() / a.abs().max(b.abs())
}

#[test]
fn xval_rdrandinf_obs_stat() {
    let (y, r) = load_senate();

    let result = rdrandinf(&RdRandInfConfig {
        y: y.clone(),
        r: r.clone(),
        cutoff: 0.0,
        wl: -1.0,
        wr: 1.0,
        statistic: "diffmeans".into(),
        nulltau: 0.0,
        reps: 0, // Skip permutations for deterministic comparison
        ..Default::default()
    }).unwrap();

    // R reference: obs_stat = 10.45693915555556
    let r_obs_stat = 10.45693915555556;
    let tol = 1e-6;
    assert!(rel_err(result.obs_stat, r_obs_stat) < tol,
        "obs_stat: Rust={:.10e} vs R={:.10e}", result.obs_stat, r_obs_stat);
}

#[test]
fn xval_rdrandinf_asy_pvalue() {
    let (y, r) = load_senate();

    let result = rdrandinf(&RdRandInfConfig {
        y, r,
        cutoff: 0.0,
        wl: -1.0,
        wr: 1.0,
        statistic: "diffmeans".into(),
        nulltau: 0.0,
        reps: 0, // Skip permutations
        ..Default::default()
    }).unwrap();

    // R reference: asy_pvalue = 5.587946296197011e-06
    // For such tiny p-values (~1e-6), small SE differences get amplified
    // enormously on the p-value scale. Both should be < 1e-4 (very significant).
    let r_asy_pvalue: f64 = 5.587946296197011e-06;
    assert!(result.asy_pvalue < 1e-4,
        "asy_pvalue should be very small: Rust={:.6e} vs R={:.6e}",
        result.asy_pvalue, r_asy_pvalue);
    // Same order of magnitude
    assert!((result.asy_pvalue.log10() - r_asy_pvalue.log10()).abs() < 0.5_f64,
        "asy_pvalue should be same order of magnitude: Rust={:.2e} vs R={:.2e}",
        result.asy_pvalue, r_asy_pvalue);
}

#[test]
fn xval_rdrandinf_window() {
    let (y, r) = load_senate();

    let result = rdrandinf(&RdRandInfConfig {
        y, r,
        cutoff: 0.0,
        wl: -1.0,
        wr: 1.0,
        statistic: "diffmeans".into(),
        reps: 0,
        ..Default::default()
    }).unwrap();

    // Window [-1, 1] should capture a specific number of observations
    // R reference: n_window, n_treat, n_ctrl (from window output)
    // The R code shows these as NA in the output format, but internally
    // the window [-1,1] captures observations with R between -1 and 1
    assert!(result.n_window > 0, "should have observations in window");
    assert_eq!(result.window, (-1.0, 1.0));
    assert!(result.n_treat > 0 && result.n_ctrl > 0);
}

#[test]
fn xval_rdrandinf_permutation() {
    let (y, r) = load_senate();

    // Run with permutations
    let result = rdrandinf(&RdRandInfConfig {
        y, r,
        cutoff: 0.0,
        wl: -1.0,
        wr: 1.0,
        statistic: "diffmeans".into(),
        nulltau: 0.0,
        reps: 500,
        seed: 42,
        ..Default::default()
    }).unwrap();

    // R reference: p_value = 0 (all permutations gave smaller stat)
    // Our RNG differs, but for such a large observed stat, p should be very small
    assert!(result.p_value < 0.01,
        "permutation p-value should be very small for large effect: {}",
        result.p_value);
}
