//! Golden cross-validation: Rust vs R reference output.
//!
//! Generated by `Rscript tests/gen_golden.R` using R rdrobust 4.1.0 +
//! rdpower 3.0 on the Senate dataset (1297 complete-case obs).
//!
//! These tests verify numerical agreement between the Rust port and
//! the original R implementation.

use std::io::BufReader;

use rdpower::{rdmde, rdpower, rdsampsi, RdPowerConfig, RdSampsiConfig};
use rdrobust::{rdrobust, Kernel, RdRobustConfig};

fn load_senate() -> (Vec<f64>, Vec<f64>) {
    let path = "tests/rdpower_senate.csv";
    let file = std::fs::File::open(path)
        .unwrap_or_else(|e| panic!("Cannot open {path}: {e}"));
    let reader = BufReader::new(file);
    let mut rdr = csv::ReaderBuilder::new().from_reader(reader);
    let mut y = Vec::new();
    let mut r = Vec::new();
    for result in rdr.records() {
        let record = result.unwrap();
        let outcome: f64 = record.get(9).unwrap().parse().unwrap_or(f64::NAN);
        let margin: f64 = record.get(5).unwrap().parse().unwrap_or(f64::NAN);
        if outcome.is_finite() && margin.is_finite() {
            y.push(outcome);
            r.push(margin);
        }
    }
    (y, r)
}

/// Relative error: |a-b| / max(|a|, |b|), or absolute if both near zero.
fn rel_err(a: f64, b: f64) -> f64 {
    let abs_diff = (a - b).abs();
    let max_abs = a.abs().max(b.abs());
    if max_abs < 1e-30 {
        abs_diff
    } else {
        abs_diff / max_abs
    }
}

// =====================================================================
// rdrobust: Rust vs R (rdrobust 4.1.0)
// =====================================================================

#[test]
fn xval_rdrobust_tau_and_se() {
    let (y, r) = load_senate();
    let cfg = RdRobustConfig {
        y, x: r, c: 0.0, p: 1, q: 2, deriv: 0,
        kernel: Kernel::Triangular,
        bwselect: "mserd".into(),
        vce: "nn".into(), level: 95.0,
        stdvars: false,
        ..Default::default()
    };
    let out = rdrobust(&cfg).unwrap();

    // --- R reference values ---
    let r_tau_cl = 7.414130630172039;
    let r_tau_bc = 7.506502101051396;
    let r_se_cl  = 1.458716133447212;
    let r_se_rb  = 1.741258539530723;

    let tol = 1e-6; // 1 ppm relative tolerance
    assert!(rel_err(out.tau_cl, r_tau_cl) < tol,
        "tau_cl: Rust={:.10e} vs R={:.10e} (rel_err={:.2e})",
        out.tau_cl, r_tau_cl, rel_err(out.tau_cl, r_tau_cl));
    assert!(rel_err(out.tau_bc, r_tau_bc) < tol,
        "tau_bc: Rust={:.10e} vs R={:.10e} (rel_err={:.2e})",
        out.tau_bc, r_tau_bc, rel_err(out.tau_bc, r_tau_bc));
    assert!(rel_err(out.se_cl, r_se_cl) < tol,
        "se_cl: Rust={:.10e} vs R={:.10e} (rel_err={:.2e})",
        out.se_cl, r_se_cl, rel_err(out.se_cl, r_se_cl));
    assert!(rel_err(out.se_rb, r_se_rb) < tol,
        "se_rb: Rust={:.10e} vs R={:.10e} (rel_err={:.2e})",
        out.se_rb, r_se_rb, rel_err(out.se_rb, r_se_rb));
}

#[test]
fn xval_rdrobust_bandwidths() {
    let (y, r) = load_senate();
    let cfg = RdRobustConfig {
        y, x: r, c: 0.0,
        kernel: Kernel::Triangular,
        bwselect: "mserd".into(),
        vce: "nn".into(),
        stdvars: false,
        ..Default::default()
    };
    let out = rdrobust(&cfg).unwrap();

    // --- R reference ---
    let r_h_l = 17.75439559014681;
    let r_h_r = 17.75439559014681;
    let r_b_l = 28.02808466728455;
    let r_b_r = 28.02808466728455;

    let tol = 1e-4; // bandwidth selection has more numerical sensitivity
    assert!(rel_err(out.h_l, r_h_l) < tol,
        "h_l: Rust={:.10e} vs R={:.10e}", out.h_l, r_h_l);
    assert!(rel_err(out.h_r, r_h_r) < tol,
        "h_r: Rust={:.10e} vs R={:.10e}", out.h_r, r_h_r);
    assert!(rel_err(out.b_l, r_b_l) < tol,
        "b_l: Rust={:.10e} vs R={:.10e}", out.b_l, r_b_l);
    assert!(rel_err(out.b_r, r_b_r) < tol,
        "b_r: Rust={:.10e} vs R={:.10e}", out.b_r, r_b_r);
}

#[test]
fn xval_rdrobust_sample_sizes() {
    let (y, r) = load_senate();
    let cfg = RdRobustConfig {
        y, x: r, c: 0.0,
        kernel: Kernel::Triangular,
        vce: "nn".into(),
        stdvars: false,
        ..Default::default()
    };
    let out = rdrobust(&cfg).unwrap();

    // --- R reference (exact integer match) ---
    assert_eq!(out.n_l, 595, "n_l mismatch");
    assert_eq!(out.n_r, 702, "n_r mismatch");
    assert_eq!(out.n_h_l, 360, "n_h_l mismatch");
    assert_eq!(out.n_h_r, 323, "n_h_r mismatch");
}

#[test]
fn xval_rdrobust_bias() {
    let (y, r) = load_senate();
    let cfg = RdRobustConfig {
        y, x: r, c: 0.0,
        kernel: Kernel::Triangular,
        vce: "nn".into(),
        stdvars: false,
        ..Default::default()
    };
    let out = rdrobust(&cfg).unwrap();

    // --- R reference ---
    let r_bias_l = 0.2943599824525762;
    let r_bias_r = 0.2019885115732194;

    let tol = 1e-4;
    assert!(rel_err(out.bias_l, r_bias_l) < tol,
        "bias_l: Rust={:.10e} vs R={:.10e}", out.bias_l, r_bias_l);
    assert!(rel_err(out.bias_r, r_bias_r) < tol,
        "bias_r: Rust={:.10e} vs R={:.10e}", out.bias_r, r_bias_r);
}

// =====================================================================
// rdpower: Rust vs R (rdpower 3.0)
// =====================================================================

#[test]
fn xval_rdpower_tau5() {
    let (y, r) = load_senate();
    let cfg = RdPowerConfig {
        y, r, cutoff: 0.0, tau: Some(5.0), alpha: 0.05, p: 1,
        ..Default::default()
    };
    let out = rdpower(&cfg).unwrap();

    // --- R reference ---
    let r_power_rbc  = 0.8189905549293736;
    let r_power_conv = 0.9646945482572080;
    let r_se_rbc     = 1.741258539530723;
    let r_se_conv    = 1.458716133447212;

    let tol = 1e-4;
    assert!(rel_err(out.power_rbc, r_power_rbc) < tol,
        "power_rbc: Rust={:.10e} vs R={:.10e}", out.power_rbc, r_power_rbc);
    assert!(rel_err(out.power_conv, r_power_conv) < tol,
        "power_conv: Rust={:.10e} vs R={:.10e}", out.power_conv, r_power_conv);
    assert!(rel_err(out.se_rbc, r_se_rbc) < tol,
        "se_rbc: Rust={:.10e} vs R={:.10e}", out.se_rbc, r_se_rbc);
    assert!(rel_err(out.se_conv, r_se_conv) < tol,
        "se_conv: Rust={:.10e} vs R={:.10e}", out.se_conv, r_se_conv);
}

// =====================================================================
// rdsampsi: Rust vs R
// =====================================================================

#[test]
fn xval_rdsampsi_tau5_beta80() {
    let (y, r) = load_senate();
    let cfg = RdSampsiConfig {
        y, r, cutoff: 0.0, tau: Some(5.0), alpha: 0.05, beta: 0.8,
        ..Default::default()
    };
    let out = rdsampsi(&cfg).unwrap();

    // --- R reference ---
    let r_sampsi_h_tot = 657usize;
    let r_sampsi_h_l   = 366usize;
    let r_sampsi_h_r   = 291usize;

    // Sample sizes should match exactly or be within ±2 (rounding differences)
    assert!((out.sampsi_h_tot as i64 - r_sampsi_h_tot as i64).abs() <= 5,
        "sampsi_h_tot: Rust={} vs R={}", out.sampsi_h_tot, r_sampsi_h_tot);
    assert!((out.sampsi_h_l as i64 - r_sampsi_h_l as i64).abs() <= 5,
        "sampsi_h_l: Rust={} vs R={}", out.sampsi_h_l, r_sampsi_h_l);
    assert!((out.sampsi_h_r as i64 - r_sampsi_h_r as i64).abs() <= 5,
        "sampsi_h_r: Rust={} vs R={}", out.sampsi_h_r, r_sampsi_h_r);
}
