use std::path::{Path, PathBuf};

use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

/// An immutable reference-data bundle stored in the authoritative object VFS.
#[derive(Debug, Clone, PartialEq, Eq, JsonSchema, Deserialize, Serialize)]
pub struct PanelRef {
    pub id: String,
    pub digest: String,
    pub source: String,
    pub mount_path: String,
}

/// A panel materialized into the shared panel cache.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CachedPanel {
    pub id: String,
    pub digest: String,
    pub host_path: PathBuf,
    pub mount_path: String,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WorkspaceRef {
    pub host_path: PathBuf,
    pub container_workdir: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, JsonSchema, Deserialize, Serialize)]
#[serde(rename_all = "kebab-case")]
pub enum PullPolicy {
    #[default]
    Missing,
    Always,
    Newer,
    Never,
}

/// Network profile of an ephemeral container.
///
/// `Isolated` runs with no network devices at all (`podman --network none`).
/// `Egress` uses the host's default container networking.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, JsonSchema, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum ContainerNetwork {
    #[default]
    Isolated,
    Egress,
}

impl ContainerNetwork {
    /// Parse a spec-level network name. `none` is accepted as a legacy
    /// spelling of `isolated`; `cluster` was removed together with the k3s
    /// backend and is rejected explicitly.
    pub fn parse(value: &str) -> Result<Self, String> {
        match value.trim().to_ascii_lowercase().as_str() {
            "isolated" | "none" => Ok(Self::Isolated),
            "egress" => Ok(Self::Egress),
            "cluster" => Err(
                "network profile `cluster` was removed with the k3s backend; use `isolated` or `egress`"
                    .into(),
            ),
            other => Err(format!(
                "network must be `isolated` or `egress`; got `{other}`"
            )),
        }
    }
}

/// GPU passthrough request, rendered as Podman's `--gpus` value.
///
/// GPU access is strictly opt-in: the default adds no flag at all, so a
/// container sees GPUs only when its spec asks for them. The host must expose
/// the devices through the container device interface — for rootless Podman
/// that means the nvidia-container-toolkit CDI spec generated by
/// `nvidia-ctk cdi generate` — otherwise `podman create` fails.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub enum GpuRequest {
    /// No GPU passthrough (no `--gpus` flag).
    #[default]
    None,
    /// All host GPUs (`--gpus all`).
    All,
    /// The first `n` host GPUs (`--gpus n`).
    Count(u32),
    /// Specific devices by index or UUID (`--gpus device=0,2`).
    Devices(String),
}

impl GpuRequest {
    /// Parse a spec-level GPU request: `all`, a positive device count, or
    /// `device=<comma-separated indices or UUIDs>`.
    pub fn parse(value: &str) -> Result<Self, String> {
        let value = value.trim();
        if value.is_empty() {
            return Err("gpus cannot be empty".into());
        }
        if value.eq_ignore_ascii_case("all") {
            return Ok(Self::All);
        }
        if let Ok(count) = value.parse::<u32>() {
            if count == 0 {
                return Err("gpus count must be positive".into());
            }
            return Ok(Self::Count(count));
        }
        if let Some(ids) = value.strip_prefix("device=") {
            let valid = !ids.is_empty()
                && ids.split(',').all(|id| {
                    !id.is_empty() && id.chars().all(|c| c.is_ascii_alphanumeric() || c == '-')
                });
            if valid {
                return Ok(Self::Devices(ids.to_string()));
            }
            return Err(format!(
                "gpus device list must be comma-separated indices or UUIDs; got `{ids}`"
            ));
        }
        Err(format!(
            "gpus must be `all`, a positive count, or `device=<ids>`; got `{value}`"
        ))
    }

    /// The value passed to Podman's `--gpus` flag, or `None` when the request
    /// needs no flag.
    pub fn podman_value(&self) -> Option<String> {
        match self {
            Self::None => None,
            Self::All => Some("all".into()),
            Self::Count(count) => Some(count.to_string()),
            Self::Devices(ids) => Some(format!("device={ids}")),
        }
    }
}

#[derive(Debug, Clone)]
pub struct ContainerRunRequest {
    pub image: String,
    pub command: Vec<String>,
    pub workspace: WorkspaceRef,
    pub env: Vec<(String, String)>,
    pub panels: Vec<CachedPanel>,
    pub network: ContainerNetwork,
    pub read_only_rootfs: bool,
    pub pull_policy: PullPolicy,
    pub cpus: Option<f64>,
    pub memory: Option<String>,
    pub pids_limit: Option<i64>,
    pub shm_size: Option<String>,
    pub gpus: GpuRequest,
    pub user: Option<String>,
    pub timeout_secs: u64,
    pub name: String,
}

#[derive(Debug, Clone)]
pub struct ContainerRunResult {
    pub exit_code: i32,
    pub stdout: String,
    pub stderr: String,
}

impl PanelRef {
    pub fn validate(&self) -> Result<(), String> {
        if self.id.trim().is_empty() {
            return Err("panel `id` cannot be empty".into());
        }
        if !self.digest.starts_with("sha256:") || self.digest.len() != 71 {
            return Err(format!("panel `{}` has invalid digest", self.id));
        }
        if self.source.contains('\0') || self.source.trim() == "/" {
            return Err(format!("panel `{}` has invalid source", self.id));
        }
        if !Path::new(&self.mount_path).is_absolute() || self.mount_path == "/" {
            return Err(format!("panel `{}` has invalid mount path", self.id));
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn legacy_none_parses_as_isolated_and_cluster_is_rejected() {
        assert_eq!(
            ContainerNetwork::parse("isolated").unwrap(),
            ContainerNetwork::Isolated
        );
        assert_eq!(
            ContainerNetwork::parse(" none ").unwrap(),
            ContainerNetwork::Isolated
        );
        assert_eq!(
            ContainerNetwork::parse("egress").unwrap(),
            ContainerNetwork::Egress
        );
        let cluster = ContainerNetwork::parse("cluster").unwrap_err();
        assert!(cluster.contains("removed with the k3s backend"));
        assert!(ContainerNetwork::parse("host").is_err());
    }

    #[test]
    fn gpu_requests_parse_the_three_spelling() {
        assert_eq!(GpuRequest::parse("all").unwrap(), GpuRequest::All);
        assert_eq!(GpuRequest::parse(" ALL ").unwrap(), GpuRequest::All);
        assert_eq!(GpuRequest::parse("2").unwrap(), GpuRequest::Count(2));
        assert_eq!(
            GpuRequest::parse("device=0,2").unwrap(),
            GpuRequest::Devices("0,2".into())
        );
        assert_eq!(
            GpuRequest::parse("device=GPU-62c5").unwrap(),
            GpuRequest::Devices("GPU-62c5".into())
        );
        assert_eq!(GpuRequest::parse("").unwrap_err(), "gpus cannot be empty");
        assert!(GpuRequest::parse("0").is_err());
        assert!(GpuRequest::parse("-1").is_err());
        assert!(GpuRequest::parse("device=").is_err());
        assert!(GpuRequest::parse("device=0,,2").is_err());
        assert!(GpuRequest::parse("device=0;rm").is_err());
        assert!(GpuRequest::parse("--foo").is_err());
    }

    #[test]
    fn gpu_requests_render_podman_values_only_when_set() {
        assert_eq!(GpuRequest::None.podman_value(), None);
        assert_eq!(GpuRequest::All.podman_value(), Some("all".into()));
        assert_eq!(GpuRequest::Count(1).podman_value(), Some("1".into()));
        assert_eq!(
            GpuRequest::Devices("0,3".into()).podman_value(),
            Some("device=0,3".into())
        );
    }
}
